import { saveExercise } from '@/lib/save-exercise';
import { priceInPounds } from '@/lib/investment-fx';
import { siteTools } from '@/lib/site-tools';
import { catalog,siteRead,siteWrite } from '@/lib/site-crud';
import { revalidatePath } from 'next/cache';
import { investmentSnapshotSchema,investmentsSchema,appendSnapshot,investmentChange } from '@/lib/investments';
import { updateProfile } from '@/lib/profile-store';
import { randomUUID } from 'node:crypto';
import { NextResponse } from 'next/server';
import { checkinActionSchema, dailySummary, eventBase, mealActionSchema, saveActionEvent, waterActionSchema } from '@/lib/gpt-action';
import { readAccessToken } from '@/lib/mcp-oauth';
import { createClient } from '@supabase/supabase-js';
import { diarySchema } from '@/lib/diary-fields';
import { applyCardReport,financePlan } from '@/lib/credit-card';
import { upsertExam,readExams,markers } from '@/lib/exams';
import { addLot,readHoldings } from '@/lib/holdings';
import { livePortfolio } from '@/lib/portfolio-data';
import { prepareDogMeal,prepareDogActivity,prepareFoodBag,upsertById,dogNutrients } from '@/lib/dog-food';
import { upsertDogItem,readDog,upcomingCare,dogLists,ageLabel,weightSummary } from '@/lib/dog';
import { mcpRecordResult,mcpSavePlayer,mcpCreateSeason,mcpAddImage,leagueSummary,readLeague } from '@/lib/tennis-league';

export const runtime = 'nodejs';

const toolList = [
 ...siteTools,
 {name:'registrar_diario',title:'Registrar check-in, atividade, fezes, água, vitaminas ou remédio',description:'Registra os seis tipos do botão Registrar com data e horário. Aceita múltiplas escolhas nos grupos. Use exatamente as opções configuradas (consulte o recurso configuracoes: diary.topics, routines e medicines). Tópicos personalizados vão em custom = {id_do_tópico:[opções]}. Para alterar ou remover depois, consulte os itens e use as ferramentas genéricas do site com o ID. Não registre sono, exercício ou tênis aqui.',inputSchema:{type:'object',required:['kind','occurred_at'],properties:{kind:{type:'string',enum:['checkin','activity','bowel','water','vitamins','medication']},occurred_at:{type:'string',description:'Data e horário ISO 8601 com fuso de Londres.'},mental:{type:'array',items:{type:'string'}},emotions:{type:'array',items:{type:'string'}},emotion_notes:{type:'string'},body:{type:'array',items:{type:'string'}},body_notes:{type:'string'},digestion:{type:'array',items:{type:'string'}},activities:{type:'array',items:{type:'string'}},interest:{type:'string'},quantity:{type:'array',items:{type:'string'}},consistency:{type:'array',items:{type:'string'}},routines:{type:'array',items:{type:'string'}},medicines:{type:'array',items:{type:'object',required:['name','composition'],properties:{name:{type:'string',description:'Nome como na lista de remédios das configurações.'},composition:{type:'string'},dose:{type:'string'}}}},volume_ml:{type:'number',minimum:1,maximum:10000},custom:{type:'object',additionalProperties:{type:'array',items:{type:'string'}}},notes:{type:'string'}}},annotations:{readOnlyHint:false,destructiveHint:false,openWorldHint:false},securitySchemes:[{type:'oauth2',scopes:['health:write']}]},
{"name": "consultar_investimentos", "title": "Consultar investimentos e histórico", "description": "Consulta IDs, valores e histórico dos investimentos. Use antes de registrar novos prints para reutilizar os IDs. Variação de saldo não é rentabilidade: aportes e resgates alteram o valor. Não some moedas diferentes.", "inputSchema": {"type": "object", "properties": {}}, "annotations": {"readOnlyHint": true, "destructiveHint": false, "openWorldHint": false}, "securitySchemes": [{"type": "oauth2", "scopes": ["health:read"]}]},{"name": "registrar_investimentos", "title": "Registrar atualização dos investimentos", "description": "Ao receber prints de investimentos, registre separadamente cada posição legível com valor total, conta, moeda e data de referência. Consulte os IDs existentes antes. Não invente valores, não preencha ausências com zero e não trate preço unitário como saldo. Peça esclarecimento se moeda, conta ou data estiverem ambíguas. Use ID único para esta atualização e reutilize-o em retries. Preserva histórico, aceita prints parciais. Só confirme após saved=true.", "inputSchema": {"type": "object", "required": ["id", "as_of", "items"], "properties": {"id": {"type": "string", "description": "ID único da atualização; repetir o mesmo em tentativas da mesma gravação."}, "as_of": {"type": "string", "description": "Data/hora de referência ISO 8601 com fuso."}, "items": {"type": "array", "minItems": 1, "maxItems": 200, "items": {"type": "object", "required": ["asset_id", "name", "account", "currency", "value"], "properties": {"asset_id": {"type": "string", "description": "Identificador estável do investimento + conta + moeda. Consulte o histórico e reutilize o mesmo ID."}, "name": {"type": "string"}, "asset_type": {"type":"string","enum":["Cripto","Ações","ETFs","Fundos","Renda fixa","Caixa","Outros"]}, "account": {"type": "string"}, "currency": {"type": "string", "description": "Código ISO, como GBP, BRL ou USD."}, "value": {"type": "number", "minimum": 0, "description": "Valor total atual da posição, não preço unitário."}, "net_flow": {"type": ["number", "null"], "description": "Aporte líquido positivo ou resgate negativo desde a atualização anterior. Só informe se conhecido; não estime."}}}}, "notes": {"type": "string"}}}, "annotations": {"readOnlyHint": false, "destructiveHint": false, "openWorldHint": false}, "securitySchemes": [{"type": "oauth2", "scopes": ["health:write"]}]},
  {name:'registrar_cartao_credito',title:'Registrar valor do cartão de crédito',description:'Registra o valor atual da fatura do cartão de crédito (balance, em £) e/ou o saldo atual da conta corrente (checking_balance, em £). Cada valor da fatura entra no histórico do gráfico do Financeiro; um novo envio na mesma data substitui o daquela data. Não invente valores. Só confirme após saved=true. Para corrigir limite, dia de vencimento, margem ou juros use editar_dados_site no recurso cartao_credito.',inputSchema:{type:'object',properties:{balance:{type:'number',minimum:0,description:'Valor atual a pagar do cartão, em libras.'},checking_balance:{type:'number',description:'Saldo atual da conta corrente, em libras.'},date:{type:'string',description:'AAAA-MM-DD. Omita para hoje (Europe/London).'},notes:{type:'string'},id:{type:'string',description:'Opcional. Omita para usar um registro por data.'}}},annotations:{readOnlyHint:false,destructiveHint:false,openWorldHint:false},securitySchemes:[{type:'oauth2',scopes:['health:write']}]},
  {name:'previsao_financeira',title:'Consultar previsão financeira e caixa',description:'Retorna a fatura atual do cartão, quanto ter na conta corrente para os débitos automáticos dos próximos 10 dias (com margem), quanto pode ser pago no cartão agora mantendo a margem, e a previsão mês a mês dos próximos 12 meses. Valores derivados: para mudar, edite financeiro, cartao_credito ou carro.',inputSchema:{type:'object',properties:{date:{type:'string',description:'AAAA-MM-DD. Omita para hoje.'}}},annotations:{readOnlyHint:true,destructiveHint:false,openWorldHint:false},securitySchemes:[{type:'oauth2',scopes:['health:read']}]},
  {name:'registrar_resultado_liga',title:'Registrar resultado da liga de tênis',description:'Registra ou corrige o resultado de um confronto da liga (um por par de jogadores na temporada). home/away aceitam id ou nome (ex.: "Felipe", "Gilbert Flook"). Sets do ponto de vista de home. Ao ler a foto da tabela box, a linha é o jogador home e a coluna o away; células espelhadas são o mesmo jogo, registre só uma vez. Omita season_id para a temporada atual. Só confirme após saved=true.',inputSchema:{type:'object',properties:{season_id:{type:'string'},home:{type:'string'},away:{type:'string'},home_sets:{type:'integer',minimum:0,maximum:5},away_sets:{type:'integer',minimum:0,maximum:5},score:{type:'string',description:'Games por set do ponto de vista de home, ex.: 6-4 3-6 10-8.'},date:{type:'string',description:'AAAA-MM-DD, se conhecida.'},notes:{type:'string'}},required:['home','away','home_sets','away_sets']},annotations:{readOnlyHint:false,destructiveHint:false,openWorldHint:false},securitySchemes:[{type:'oauth2',scopes:['health:write']}]},
  {name:'salvar_jogador_liga',title:'Cadastrar ou editar jogador da liga',description:'Cria ou atualiza um jogador (procura por id ou nome). Campos: name, nickname, country (ISO 2 letras, ex.: BR, GB, IN, PL), photo (URL HTTPS ou data:image/jpeg;base64 até ~120 KB), sex, hand (Destro/Canhoto), backhand (Uma mão/Duas mãos), racket, strings, level, favouriteShot, favouritePlayer, since, notes. Campos omitidos são mantidos. Nunca grave telefone ou e-mail: a página da liga é pública.',inputSchema:{type:'object',properties:{id:{type:'string'},name:{type:'string'},nickname:{type:'string'},country:{type:'string'},photo:{type:'string'},sex:{type:'string'},hand:{type:'string',enum:['','Destro','Canhoto']},backhand:{type:'string',enum:['','Uma mão','Duas mãos']},racket:{type:'string'},strings:{type:'string'},level:{type:'string'},favouriteShot:{type:'string'},favouritePlayer:{type:'string'},since:{type:'string'},notes:{type:'string'}}},annotations:{readOnlyHint:false,destructiveHint:false,openWorldHint:false},securitySchemes:[{type:'oauth2',scopes:['health:write']}]},
  {name:'criar_temporada_liga',title:'Criar temporada da liga',description:'Cria a temporada trimestral (jan–mar, abr–jun, jul–set, out–dez) que contém start (padrão: hoje). Copia o box da temporada mais recente, salvo se players (nomes ou ids) for informado.',inputSchema:{type:'object',properties:{start:{type:'string'},name:{type:'string'},division:{type:'string'},league:{type:'string'},players:{type:'array',items:{type:'string'}},copy_players_from:{type:'string'}}},annotations:{readOnlyHint:false,destructiveHint:false,openWorldHint:false},securitySchemes:[{type:'oauth2',scopes:['health:write']}]},
  {name:'adicionar_imagem_liga',title:'Adicionar imagem à temporada da liga',description:'Guarda uma imagem (foto da tabela, do grupo, troféu) na temporada. url = URL HTTPS ou data:image/jpeg;base64 comprimida (até ~1 MB). Omita season_id para a temporada atual.',inputSchema:{type:'object',properties:{season_id:{type:'string'},url:{type:'string'},caption:{type:'string'},date:{type:'string'},id:{type:'string'}},required:['url']},annotations:{readOnlyHint:false,destructiveHint:false,openWorldHint:false},securitySchemes:[{type:'oauth2',scopes:['health:write']}]},
  {name:'registrar_exame',title:'Registrar exame ou consulta',description:'Salva um exame (sangue, urina, imagem, check-up) ou consulta com TODOS os marcadores do laudo. Para cada marcador informe name, value (número, use ponto decimal), unit, low/high da faixa de referência do próprio laudo (null quando só houver um limite) e reference com o texto original. Converta vírgula decimal para ponto. Mesmo date+title (ou id) atualiza o exame em vez de duplicar. next = data do próximo exame/retorno (entra nos vencimentos).',inputSchema:{type:'object',properties:{id:{type:'string'},date:{type:'string',description:'YYYY-MM-DD da coleta'},kind:{type:'string',enum:['Exame de sangue','Exame de urina','Imagem','Consulta','Check-up','Outro']},title:{type:'string'},lab:{type:'string'},doctor:{type:'string'},next:{type:'string'},nextNote:{type:'string'},notes:{type:'string'},url:{type:'string'},results:{type:'array',items:{type:'object',properties:{id:{type:'string'},name:{type:'string',description:'Nome do marcador como no laudo, ex.: Vitamina D (25-OH), Ferritina, Colesterol LDL'},group:{type:'string',enum:['Vitaminas','Minerais e ferro','Lipídios','Glicose','Hemograma','Tireoide e hormônios','Rins','Fígado','Inflamação','Urina','Outros']},value:{type:['number','null']},text:{type:'string',description:'Resultado qualitativo (ex.: Negativo) quando não houver número'},unit:{type:'string'},low:{type:['number','null'],description:'Limite inferior da referência'},high:{type:['number','null'],description:'Limite superior da referência'},reference:{type:'string',description:'Texto original da faixa de referência'},notes:{type:'string'}},required:['name']}}},required:['date','title']},annotations:{readOnlyHint:false,destructiveHint:false,openWorldHint:false},securitySchemes:[{type:'oauth2',scopes:['health:write']}]},
  {name:'consultar_exames',title:'Consultar exames',description:'Lista exames e consultas com ids e o último valor de cada marcador (status baixo/normal/alto e variação).',inputSchema:{type:'object',properties:{}},annotations:{readOnlyHint:true,destructiveHint:false,openWorldHint:false},securitySchemes:[{type:'oauth2',scopes:['health:read']}]},
  {name:'registrar_caju',title:'Registrar cuidado do Caju',description:'Adiciona ou atualiza (mesmo id) um item do cachorro Caju. list: vaccines {name,date,next,vet,batch,notes}, parasites {kind (Vermífugo/Antipulgas e carrapatos/Coleira/Outro),product,date,next,dose,notes}, weights {date,kg,notes}, visits {date,reason,vet,diagnosis,cost,next,notes}, medications {name,dose,everyDays,times,start,end,lastGiven,stock,active,notes}, grooming {kind (Banho/Tosa/Unhas/Dentes/Ouvidos/Outro),date,next,place,cost,notes}, dates {name,date,yearly,notes}. Datas YYYY-MM-DD; next entra nos vencimentos. Para dar um remédio agora, envie medications com o id e lastGiven = hoje. Para a ficha (raça, chip, veterinário, seguro, ração) use editar_dados_site com resource caju.',inputSchema:{type:'object',properties:{list:{type:'string',enum:['vaccines', 'parasites', 'weights', 'visits', 'medications', 'grooming', 'dates']},item:{type:'object'}},required:['list','item']},annotations:{readOnlyHint:false,destructiveHint:false,openWorldHint:false},securitySchemes:[{type:'oauth2',scopes:['health:write']}]},
  {name:'consultar_caju',title:'Consultar Caju',description:'Ficha do Caju, idade, peso, próximos cuidados (vacinas, vermífugo, remédios, retornos) e todas as listas com ids.',inputSchema:{type:'object',properties:{}},annotations:{readOnlyHint:true,destructiveHint:false,openWorldHint:false},securitySchemes:[{type:'oauth2',scopes:['health:read']}]},
  {name:'registrar_comida_caju',title:'Registrar comida do Caju',description:'Registra uma refeição do cachorro Caju como as suas: horário, itens com gramas e nutrientes por 100 g (energia, proteína, gordura, fibra, minerais, vitaminas, ômegas). Para a ração cadastrada, envie food_id (veja consultar_caju → foodBags) e os nutrientes vêm do saco. Mesmo id substitui.',inputSchema:{type:'object',required:['occurred_at','items'],properties:{id:{type:'string'},occurred_at:{type:'string',description:'ISO 8601 com fuso de Londres'},name:{type:'string',description:'Café da manhã, Jantar, Petisco…'},items:{type:'array',items:{type:'object',required:['grams'],properties:{name:{type:'string'},grams:{type:'number'},food_id:{type:'string'},nutrition:{type:'object',description:'Por 100 g de alimento. Chaves: '+dogNutrients.map(n=>`${n[0]} (${n[2]})`).join(', ')+'. Converta % em g/100 g, mg/kg em mg/100 g (÷10), UI/kg em UI/100 g (÷10).'}}}},notes:{type:'string'}}},annotations:{readOnlyHint:false,destructiveHint:false,openWorldHint:false},securitySchemes:[{type:'oauth2',scopes:['health:write']}]},
  {name:'registrar_atividade_caju',title:'Registrar atividade do Caju',description:'Registra o exercício do dia que fizemos juntos (ou só do Caju): minutos, distância e passos. Caminhadas Outdoor Walk do Apple Watch já entram sozinhas no Caju — não as reenvie aqui; aqui vão os valores além delas (brincadeira, parque, corrida…). with_me=true (padrão) conta também nos meus exercícios. Mesmo id substitui.',inputSchema:{type:'object',required:['date','minutes'],properties:{id:{type:'string'},date:{type:'string'},kind:{type:'string',enum:['Passeio','Corrida','Brincadeira','Parque','Natação','Treino','Outro']},minutes:{type:'number'},distance_km:{type:'number'},steps:{type:'number'},with_me:{type:'boolean'},notes:{type:'string'}}},annotations:{readOnlyHint:false,destructiveHint:false,openWorldHint:false},securitySchemes:[{type:'oauth2',scopes:['health:write']}]},
  {name:'salvar_racao_caju',title:'Salvar ração ou alimento do Caju',description:'Cadastra ou atualiza a ração (ou petisco/suplemento) a partir das fotos do saco: brand, product, type, sizeKg, price, started, ingredients (lista completa), analysis (níveis de garantia como no saco), additives (aditivos por kg), feedingGuide, per100g (nutrientes convertidos para 100 g) e add_photos [{url:data:image/jpeg;base64 comprimida até ~300 KB, caption}] para guardar as fotos. Mesmo id ou mesma marca+produto atualiza.',inputSchema:{type:'object',required:['brand'],properties:{id:{type:'string'},brand:{type:'string'},product:{type:'string'},type:{type:'string',enum:['Ração seca','Ração úmida','Petisco','Natural','Suplemento','Outro']},sizeKg:{type:'number'},price:{type:'number'},started:{type:'string'},finished:{type:'string'},active:{type:'boolean'},ingredients:{type:'string'},analysis:{type:'string'},additives:{type:'string'},feedingGuide:{type:'string'},notes:{type:'string'},per100g:{type:'object',description:'Por 100 g de alimento. Chaves: '+dogNutrients.map(n=>`${n[0]} (${n[2]})`).join(', ')+'. Converta % em g/100 g, mg/kg em mg/100 g (÷10), UI/kg em UI/100 g (÷10).'},add_photos:{type:'array',items:{type:'object',properties:{url:{type:'string'},caption:{type:'string'}}}}}},annotations:{readOnlyHint:false,destructiveHint:false,openWorldHint:false},securitySchemes:[{type:'oauth2',scopes:['health:write']}]},
  {name:'registrar_compra_ativo',title:'Registrar compra de investimento',description:'Adiciona uma compra (lote) a um ativo da carteira ao vivo; cria o ativo se não existir (informe name, symbol e source). Informe quantity, ou amount (valor investido) e price (preço do ativo na compra), e a currency. A cotação passa a ser buscada sozinha e um snapshot entra no histórico toda semana. Para corrigir quantidades use editar_dados_site com resource carteira.',inputSchema:{type:'object',properties:{holding_id:{type:'string'},name:{type:'string'},symbol:{type:'string',description:'Ticker do Yahoo Finance (QBTS, URNU.L) ou cripto (BTC, ETH)'},source:{type:'string',enum:['yahoo','coingecko','manual']},account:{type:'string'},type:{type:'string',enum:['Cripto','Ações','ETFs','Fundos','Renda fixa','Caixa','Outros']},asset_currency:{type:'string',description:'Moeda em que o ativo é cotado'},date:{type:'string'},quantity:{type:'number'},amount:{type:'number'},price:{type:'number'},currency:{type:'string'},notes:{type:'string'}}},annotations:{readOnlyHint:false,destructiveHint:false,openWorldHint:false},securitySchemes:[{type:'oauth2',scopes:['health:write']}]},
  {name:'consultar_carteira',title:'Consultar carteira ao vivo',description:'Ativos, quantidades, preço médio, cotação atual, valor em libras e resultado de cada investimento.',inputSchema:{type:'object',properties:{}},annotations:{readOnlyHint:true,destructiveHint:false,openWorldHint:false},securitySchemes:[{type:'oauth2',scopes:['health:read']}]},
  {name:'registrar_varios',title:'Registrar vários itens de uma vez',description:'Executa várias gravações numa ÚNICA chamada (uma só confirmação no ChatGPT). Use SEMPRE que um envio gerar mais de uma gravação (ex.: foto do Apple Fitness → exercício + resumo do dia; refeição + água; exame + próxima data; comida e atividade do Caju). Faça antes as consultas necessárias (são leitura e não pedem confirmação) e depois mande todas as gravações aqui, em ordem. operations = [{tool: nome de uma ferramenta de gravação, arguments: os mesmos argumentos que ela receberia}]. Exclusões não são aceitas aqui. Cada operação é executada e o resultado volta por item; uma falha não desfaz as anteriores.',inputSchema:{type:'object',required:['operations'],properties:{operations:{type:'array',minItems:1,maxItems:25,items:{type:'object',required:['tool','arguments'],properties:{tool:{type:'string'},arguments:{type:'object'}}}}}},annotations:{readOnlyHint:false,destructiveHint:false,openWorldHint:false},securitySchemes:[{type:'oauth2',scopes:['health:write']}]},
  {name:'consultar_liga',title:'Consultar liga de tênis',description:'Retorna jogadores, temporadas, classificação, status (jogos feitos, dias restantes) e confrontos pendentes. Use antes de editar para obter ids.',inputSchema:{type:'object',properties:{season_id:{type:'string'}}},annotations:{readOnlyHint:true,destructiveHint:false,openWorldHint:false},securitySchemes:[{type:'oauth2',scopes:['health:read']}]},
  { name: 'registrar_agua', title: 'Registrar água', description: 'Registra água ingerida. Para os atalhos do dashboard, use preset "copo" (650 ml) ou "garrafa" (590 ml), sem pedir os mililitros. Use volume_ml somente para outro volume informado pelo usuário.', inputSchema: { type: 'object', properties: { preset: { type: 'string', enum: ['copo', 'garrafa'], description: 'Atalho fixo: copo = 650 ml; garrafa = 590 ml.' }, volume_ml: { type: 'number', minimum: 1, maximum: 10000, description: 'Use apenas quando não for copo nem garrafa.' }, occurred_at: { type: 'string', description: 'Data e hora em ISO 8601. Omita para agora.' }, notes: { type: 'string' } } }, annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false }, securitySchemes: [{ type: 'oauth2', scopes: ['health:write'] }] },
  { name: 'registrar_checkin', title: 'Registrar check-in', description: 'Registra sono, energia, humor, atividade e observações de um check-in confirmado.', inputSchema: { type: 'object', properties: { preset: { type: 'string' }, scores: { type: 'object' }, activity: { type: 'string' }, moods: { type: 'array', items: { type: 'string' } }, environment: { type: 'array', items: { type: 'string' } }, occurred_at: { type: 'string' }, notes: { type: 'string' } } }, annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false }, securitySchemes: [{ type: 'oauth2', scopes: ['health:write'] }] },
  { name: 'registrar_refeicao', title: 'Registrar refeição', description: 'Registra uma refeição confirmada. Separe todos os ingredientes em itens individuais e preencha TODOS os nutrientes por 100 g: macros, vitaminas e minerais. Não use null e não omita campos. Quando a porção ou nutrição vier de descrição ou foto, faça a melhor estimativa e use estimated=true. Use estimated=false somente com rótulo ou valor informado pelo usuário.', inputSchema: { type: 'object', required: ['name', 'items'], properties: { name: { type: 'string' }, meal_type: { type: 'string' }, items: { type: 'array', items: { type: 'object', required: ['name', 'grams', 'nutrition'], properties: { name: { type: 'string' }, grams: { type: 'number', minimum: 1 }, nutrition: { type: 'object', required: ['calories','protein','carbs','fat','saturated_fat','fibre','sugar','sodium','vitamin_a','vitamin_c','vitamin_d','vitamin_b12','folate','calcium','iron','magnesium','potassium','zinc'], properties: { calories: { type: 'number', minimum: 0, description: 'kcal por 100 g' }, protein: { type: 'number', minimum: 0, description: 'g por 100 g' }, carbs: { type: 'number', minimum: 0, description: 'g por 100 g' }, fat: { type: 'number', minimum: 0, description: 'g por 100 g' }, saturated_fat: { type: 'number', minimum: 0, description: 'g por 100 g' }, fibre: { type: 'number', minimum: 0, description: 'g por 100 g' }, sugar: { type: 'number', minimum: 0, description: 'g por 100 g' }, sodium: { type: 'number', minimum: 0, description: 'mg por 100 g' }, vitamin_a: { type: 'number', minimum: 0, description: 'µg por 100 g' }, vitamin_c: { type: 'number', minimum: 0, description: 'mg por 100 g' }, vitamin_d: { type: 'number', minimum: 0, description: 'µg por 100 g' }, vitamin_b12: { type: 'number', minimum: 0, description: 'µg por 100 g' }, folate: { type: 'number', minimum: 0, description: 'µg por 100 g' }, calcium: { type: 'number', minimum: 0, description: 'mg por 100 g' }, iron: { type: 'number', minimum: 0, description: 'mg por 100 g' }, magnesium: { type: 'number', minimum: 0, description: 'mg por 100 g' }, potassium: { type: 'number', minimum: 0, description: 'mg por 100 g' }, zinc: { type: 'number', minimum: 0, description: 'mg por 100 g' } } } } } }, hunger: { type: 'number', minimum: 0, maximum: 10 }, satiety: { type: 'number', minimum: 0, maximum: 10 }, estimated: { type: 'boolean', description: 'true para valores inferidos ou estimados; false apenas para dados confirmados.' }, occurred_at: { type: 'string' }, notes: { type: 'string' } } }, annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false }, securitySchemes: [{ type: 'oauth2', scopes: ['health:write'] }] },
  { name: 'consultar_resumo_diario', title: 'Consultar resumo diário', description: 'Consulta água, refeições, metas e eventos de uma data.', inputSchema: { type: 'object', properties: { date: { type: 'string', description: 'Data AAAA-MM-DD. Omita para hoje.' } } }, annotations: { readOnlyHint: true, destructiveHint: false, openWorldHint: false }, securitySchemes: [{ type: 'oauth2', scopes: ['health:read'] }] },
  { name: 'registrar_sono', title: 'Registrar sono', description: 'Registra sono manualmente ou a partir de uma imagem do Apple Health/Watch. Extraia tudo que estiver legível: duração, horários, acordado, REM, Core, profundo, frequência cardíaca, respiração, SpO2 e observações. Preserve valores ausentes como ausentes.', inputSchema: { type: 'object', required: ['date','data'], properties: { date: { type: 'string' }, data: { type: 'object' }, notes: { type: 'string' } } }, annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false }, securitySchemes: [{ type: 'oauth2', scopes: ['health:write'] }] },
  { name: 'registrar_exercicio', title: 'Registrar exercício', description: 'Registra dados Apple Fitness/Watch sem duplicar. Consulte consultar_itens(date) ANTES. Se o treino já existe (inclusive tennis), envie data.record_id com seu UUID para complementar preservando placar e check-in. Resumo dos anéis é OUTRO registro: data.kind=daily_metrics, snapshot_at, active_calories, total_calories, active_calories_goal, exercise_minutes, exercise_minutes_goal, stand_hours (horas com anel atingido, não duração), stand_hours_goal, idle_hours, steps, distance_km. Treino: kind=workout, activity_type, started_at/ended_at ISO com fuso, duration_seconds exatos, duration_minutes, calorias, heart_rate_average, heart_rate_zones [{zone,duration_seconds,min_bpm,max_bpm,max_bpm_exclusive}], post_workout_heart_rate [{elapsed_minutes,bpm}], watch_effort/watch_effort_label separados de effort subjetivo, location, weather {temperature_c,humidity_percent,air_quality_index}. Tênis (e outros esportes) pode trazer também heart_rate_max, heart_rate_min e tennis_stats {shots_total, forehands, backhands, serves, first_serve_percent, aces, double_faults, winners, unforced_errors, break_points_won, rallies, longest_rally, max_swing_speed_kmh} vindos do Apple Watch, SwingVision ou da sua anotação; envie apenas o que estiver visível. Caminhadas outdoor (activity_type Outdoor Walk) entram também na atividade do Caju automaticamente. Campos extras preservados. Tênis é salvo UMA vez e aparece em Saúde e Tênis pelo mesmo ID. Não somar calorias do treino ao total diário. Não inventar amostras de curvas nem tratar rótulos de escala como máximos. Reenvios: consulte e reutilize record_id; novos treinos com started_at têm ID estável.', inputSchema: { type: 'object', required: ['date','data'], properties: { date: { type: 'string' }, data: { type: 'object' }, notes: { type: 'string' } } }, annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false }, securitySchemes: [{ type: 'oauth2', scopes: ['health:write'] }] },
  { name: 'registrar_fezes', title: 'Registrar fezes', description: 'Registra fezes com quantidade, consistência pessoal de 0 a 10, horário, urgência, dor, gases, estufamento e observações.', inputSchema: { type: 'object', required: ['date','data'], properties: { date: { type: 'string' }, data: { type: 'object', required: ['quantidade','consistencia'] }, notes: { type: 'string' } } }, annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false }, securitySchemes: [{ type: 'oauth2', scopes: ['health:write'] }] },
  { name: 'registrar_suplementos', title: 'Registrar suplementos', description: 'Registra suplementos do dia ou noite e horário. Rotina diurna: vitamina D, vitamina E, ômega-3, CoQ10, selênio, vitamina C e glucosamina. Rotina noturna: magnésio e ashwagandha. Registre apenas o que o usuário confirmou ter tomado.', inputSchema: { type: 'object', required: ['date','period','items'], properties: { date: { type: 'string' }, period: { type: 'string', enum: ['dia','noite'] }, items: { type: 'array', items: { type: 'string' } }, notes: { type: 'string' } } }, annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false }, securitySchemes: [{ type: 'oauth2', scopes: ['health:write'] }] },
  { name: 'registrar_tenis', title: 'Registrar tênis', description: 'Registra treino ou jogo de tênis, inclusive dados pré e pós. Consulte os registros do dia primeiro; se já houver a sessão use data.record_id para atualizar o MESMO registro. Nunca crie uma cópia em exercícios: o mesmo ID aparece nas duas telas. Esforço do Watch em watch_effort; esforço subjetivo em effort. Para partidas, inclua outcome (vitória ou derrota) e sets como lista de objetos {felipe:number, adversario:number}; derive também score como, por exemplo, 6-2, 6-0. Inclua tipo, adversário/parceiro, duração, energia física, clareza, motivação, foco, esforço, sintomas, análise livre e todos os dados fornecidos. Para calendário com jogos futuros, use perfil_tenis.upcoming via consultar_dados_site e editar_dados_site; não crie resultados. Ao ler placar realizado, extraia cada set visível.', inputSchema: { type: 'object', required: ['date','data'], properties: { date: { type: 'string' }, data: { type: 'object' }, notes: { type: 'string' } } }, annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false }, securitySchemes: [{ type: 'oauth2', scopes: ['health:write'] }] },
  { name: 'planejar_semana', title: 'Planejar semana e metas', description: 'Quando o usuário enviar a agenda semanal ou foto do calendário, registre também jogos futuros em perfil_tenis.upcoming via ferramentas do site, sem duplicar partidas existentes. Extraia os compromissos e crie um plano para cada dia com tipo de dia e metas de água, calorias, proteína, carboidratos, gordura, gordura saturada e fibra adequadas à carga. Explique a lógica sem fazer diagnóstico.', inputSchema: { type: 'object', required: ['plans'], properties: { plans: { type: 'array', items: { type: 'object', required: ['date','day_type','targets','agenda'], properties: { date: { type: 'string' }, day_type: { type: 'string' }, targets: { type: 'object' }, agenda: { type: 'array', items: { type: 'string' } }, rationale: { type: 'string' } } } } } }, annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false }, securitySchemes: [{ type: 'oauth2', scopes: ['health:write'] }] },
  { name: 'meu_dia', title: 'Analisar meu dia', description: 'Use quando o usuário disser “Meu dia”. Consulta eventos, sono, exercício, suplementos, fezes, tênis e plano do dia. Depois de chamar, produza 3 a 5 insights concretos e cautelosos sobre padrões, recuperação, carga, hidratação e próximos passos; não apenas uma lista de totais e não faça diagnóstico médico.', inputSchema: { type: 'object', properties: { date: { type: 'string' } } }, annotations: { readOnlyHint: true, destructiveHint: false, openWorldHint: false }, securitySchemes: [{ type: 'oauth2', scopes: ['health:read'] }] },
  { name: 'consultar_itens', title: 'Consultar itens para editar', description: 'Lista eventos e registros de saúde de uma data, incluindo id, para localizar com segurança o item que o usuário quer corrigir ou excluir.', inputSchema: { type: 'object', properties: { date: { type: 'string', description: 'AAAA-MM-DD. Omita para hoje.' } } }, annotations: { readOnlyHint: true, destructiveHint: false, openWorldHint: false }, securitySchemes: [{ type: 'oauth2', scopes: ['health:read'] }] },
  { name: 'editar_item', title: 'Editar item', description: 'Edita um item existente depois de consultar_itens e identificar o id correto. O pedido explícito de alteração autoriza a edição; pergunte apenas se houver ambiguidade. Prefira editar_dados_site para editar qualquer campo com controle de versão. Para evento, data altera occurred_at e data mescla campos em data. Para registro, data mescla campos no payload e date altera a data do registro.', inputSchema: { type: 'object', required: ['collection','id'], properties: { collection: { type: 'string', enum: ['evento','registro'] }, id: { type: 'string' }, date: { type: 'string', description: 'AAAA-MM-DD, opcional para registro.' }, occurred_at: { type: 'string', description: 'ISO 8601, opcional para evento.' }, data: { type: 'object', description: 'Somente campos a atualizar; são mesclados aos dados atuais.' }, notes: { type: 'string' } } }, annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false }, securitySchemes: [{ type: 'oauth2', scopes: ['health:write'] }] },
  { name: 'excluir_item', title: 'Excluir item', description: 'Exclui permanentemente um evento ou registro de saúde identificado por consultar_itens. Use somente após confirmação explícita do usuário sobre o item a apagar.', inputSchema: { type: 'object', required: ['collection','id'], properties: { collection: { type: 'string', enum: ['evento','registro'] }, id: { type: 'string' } } }, annotations: { readOnlyHint: false, destructiveHint: true, openWorldHint: false }, securitySchemes: [{ type: 'oauth2', scopes: ['health:write'] }] },
];

function rpc(id: unknown, result: unknown) { return NextResponse.json({ jsonrpc: '2.0', id: id ?? null, result }); }
function rpcError(id: unknown, code: number, message: string) { return NextResponse.json({ jsonrpc: '2.0', id: id ?? null, error: { code, message } }); }

function authenticated(request: Request) {
  const header = request.headers.get('authorization');
  const token = header?.match(/^Bearer (.+)$/i)?.[1];
  const access = token ? readAccessToken(token) : null;
  return access?.sub === process.env.HEALTH_GPT_USER_ID ? access : null;
}

function challenge(request: Request) {
  const origin = new URL(request.url).origin;
  return new NextResponse(null, { status: 401, headers: { 'www-authenticate': `Bearer resource_metadata="${origin}/.well-known/oauth-protected-resource", scope="health:read health:write"` } });
}

function database() {
  const url = process.env.NEXT_PUBLIC_SUPABASE_URL;
  const key = process.env.SUPABASE_SERVICE_ROLE_KEY;
  if (!url || !key) throw new Error('O servidor ainda não foi configurado.');
  return createClient(url, key, { auth: { persistSession: false, autoRefreshToken: false } });
}

function textResult(value: unknown) { return { content: [{ type: 'text', text: JSON.stringify(value) }], structuredContent: value }; }
function input(value: unknown) { return value && typeof value === 'object' && !Array.isArray(value) ? value as Record<string, unknown> : {}; }
function dateFrom(value: unknown) { return typeof value === 'string' && /^\d{4}-\d{2}-\d{2}$/.test(value) ? value : new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/London',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date()); }
async function saveRecord(db: ReturnType<typeof database>, category: string, args: Record<string, unknown>) { const date=dateFrom(args.date); const result=await db.from('health_records').insert({ user_id: process.env.HEALTH_GPT_USER_ID!, category, recorded_on: date, recorded_at: new Date().toISOString(), payload: args.data ?? args, source: 'ChatGPT' }).select().single(); if(result.error) throw new Error(result.error.message); return result.data; }

async function callTool(name: string, argumentsValue: unknown) {
  const args = input(argumentsValue); const db = database(); const key = typeof args.idempotency_key === 'string' ? args.idempotency_key : randomUUID();
  if(name==='registrar_varios'){
   const ops=Array.isArray(args.operations)?args.operations.slice(0,25):[];if(!ops.length)throw new Error('Envie ao menos uma operação.');
   const results:unknown[]=[];
   for(const [i,op] of ops.entries()){const tool=toolList.find(t=>t.name===op?.tool);
    if(!tool||op.tool==='registrar_varios'||tool.annotations.destructiveHint||/^excluir/.test(op.tool)){results.push({index:i,tool:op?.tool,ok:false,error:'Ferramenta não permitida em lote.'});continue;}
    try{const r:any=await callTool(op.tool,op.arguments??{});results.push({index:i,tool:op.tool,ok:!r?.isError,result:r?.structuredContent??r?.content?.[0]?.text});}catch(e){results.push({index:i,tool:op.tool,ok:false,error:e instanceof Error?e.message:'Falhou.'});}}
   return textResult({done:results.filter((r:any)=>r.ok).length,failed:results.filter((r:any)=>!r.ok).length,results});
  }
  if(name==='estrutura_do_site')return textResult(catalog());
  if(name==='consultar_dados_site')return textResult(await siteRead(db,process.env.HEALTH_GPT_USER_ID!,args));
  if(name==='adicionar_dados_site'||name==='editar_dados_site'||name==='excluir_dados_site')return textResult(await siteWrite(db,process.env.HEALTH_GPT_USER_ID!,name==='adicionar_dados_site'?'add':name==='editar_dados_site'?'edit':'delete',args));
  if(name==='consultar_investimentos'){const result=await db.from('health_profiles').select('profile').eq('user_id',process.env.HEALTH_GPT_USER_ID!).maybeSingle();if(result.error)throw new Error('Não foi possível consultar os investimentos.');const history=investmentsSchema.parse(result.data?.profile?.personal_investments??[]);const ids=[...new Set(history.flatMap(s=>s.items.map(i=>i.asset_id)))];return textResult({history,assets:ids.map(id=>({asset_id:id,...investmentChange(history,id)}))});}
  if(name==='registrar_investimentos'){const snapshot=await priceInPounds(investmentSnapshotSchema.parse(args));const saved=await updateProfile(db,process.env.HEALTH_GPT_USER_ID!,profile=>({...profile,personal_investments:appendSnapshot(investmentsSchema.parse(profile.personal_investments??[]),snapshot)}));return textResult({saved:true,id:snapshot.id,snapshot:saved.personal_investments.find((s:any)=>s.id===snapshot.id)});}
  if(name==='registrar_resultado_liga'||name==='criar_temporada_liga'||name==='adicionar_imagem_liga'||name==='salvar_jogador_liga'){const today=dateFrom(undefined);let saved:any;await updateProfile(db,process.env.HEALTH_GPT_USER_ID!,profile=>{const stored=profile.personal_tennis_league;if(name==='salvar_jogador_liga'){const r=mcpSavePlayer(stored,args);saved={player:r.player};return {...profile,personal_tennis_league:r.league};}const league=name==='registrar_resultado_liga'?mcpRecordResult(stored,args,today):name==='criar_temporada_liga'?mcpCreateSeason(stored,args,today):mcpAddImage(stored,args,today);saved=leagueSummary(league,today,typeof args.season_id==='string'?args.season_id:undefined);return {...profile,personal_tennis_league:league};});return textResult({saved:true,...saved});}
  if(name==='registrar_exame'){let saved:any;await updateProfile(db,process.env.HEALTH_GPT_USER_ID!,profile=>{const r=upsertExam(profile.personal_exams,args);saved={created:r.created,exam:r.exam};return {...profile,personal_exams:r.exams};});revalidatePath('/','layout');return textResult({saved:true,...saved});}
  if(name==='registrar_caju'){const list=String(args.list);if(!(dogLists as readonly string[]).includes(list))throw new Error('list inválida.');let saved:any;await updateProfile(db,process.env.HEALTH_GPT_USER_ID!,profile=>{const r=upsertDogItem(profile.personal_dog,list as any,args.item??{});saved={created:r.created,item:r.item};return {...profile,personal_dog:r.dog};});revalidatePath('/','layout');return textResult({saved:true,list,...saved});}
  if(name==='consultar_exames'||name==='consultar_caju'){const result=await db.from('health_profiles').select('profile').eq('user_id',process.env.HEALTH_GPT_USER_ID!).maybeSingle();if(result.error)throw new Error('Não foi possível consultar.');const profile=result.data?.profile??{};const today=dateFrom(undefined);
   if(name==='consultar_exames'){const exams=readExams(profile.personal_exams);return textResult({exams,markers:markers(exams).map(m=>({name:m.name,group:m.group,unit:m.unit,latest:m.latest.value??m.latest.text,date:m.latest.date,low:m.latest.low,high:m.latest.high,status:m.status,change:m.change}))});}
   const dog=readDog(profile.personal_dog);return textResult({dog:{...dog,meals:dog.meals.slice(-30),foodBags:dog.foodBags.map(b=>({...b,photos:b.photos.map(p=>({caption:p.caption}))}))},age:ageLabel(dog.birth,today),weight:weightSummary(dog).latest,upcoming:upcomingCare(dog,today)});}
  if(name==='registrar_comida_caju'||name==='registrar_atividade_caju'||name==='salvar_racao_caju'){let saved:any;await updateProfile(db,process.env.HEALTH_GPT_USER_ID!,profile=>{const dog=readDog(profile.personal_dog);
   if(name==='registrar_comida_caju'){saved=prepareDogMeal({...args,source:'gpt'},dog.foodBags);return {...profile,personal_dog:{...dog,meals:upsertById(dog.meals,saved)}};}
   if(name==='registrar_atividade_caju'){saved=prepareDogActivity({...args,source:'gpt'});return {...profile,personal_dog:{...dog,activities:upsertById(dog.activities,saved)}};}
   saved=prepareFoodBag(args,dog.foodBags);return {...profile,personal_dog:{...dog,foodBags:upsertById(dog.foodBags,saved)}};});revalidatePath('/','layout');return textResult({saved:true,item:name==='salvar_racao_caju'?{...saved,photos:saved.photos.length}:saved});}
  if(name==='registrar_compra_ativo'){let saved:any;await updateProfile(db,process.env.HEALTH_GPT_USER_ID!,profile=>{const r=addLot(profile.personal_holdings,args);saved={holding:r.holding,lot:r.lot};return {...profile,personal_holdings:r.holdings};});revalidatePath('/','layout');return textResult({saved:true,...saved});}
  if(name==='consultar_carteira'){const result=await db.from('health_profiles').select('profile').eq('user_id',process.env.HEALTH_GPT_USER_ID!).maybeSingle();if(result.error)throw new Error('Não foi possível consultar a carteira.');const holdings=readHoldings(result.data?.profile?.personal_holdings);const live=await livePortfolio(holdings);return textResult({holdings,live:live.rows,total_gbp:live.rows.reduce((t,r)=>t+(r.valueGBP??0),0),updated_at:live.updatedAt});}
  if(name==='consultar_liga'){const result=await db.from('health_profiles').select('profile').eq('user_id',process.env.HEALTH_GPT_USER_ID!).maybeSingle();if(result.error)throw new Error('Não foi possível consultar a liga.');return textResult(leagueSummary(readLeague(result.data?.profile?.personal_tennis_league),dateFrom(undefined),typeof args.season_id==='string'?args.season_id:undefined));}
  if(name==='registrar_cartao_credito'){let card:unknown;await updateProfile(db,process.env.HEALTH_GPT_USER_ID!,profile=>{card=applyCardReport(profile.personal_credit_card,args,dateFrom(undefined));return {...profile,personal_credit_card:card};});return textResult({saved:true,cartao_credito:card});}
  if(name==='previsao_financeira'){const result=await db.from('health_profiles').select('profile').eq('user_id',process.env.HEALTH_GPT_USER_ID!).maybeSingle();if(result.error)throw new Error('Não foi possível consultar o financeiro.');return textResult(financePlan(result.data?.profile??{},dateFrom(args.date)));}
  if(name==='registrar_diario'){
    const value=diarySchema.parse(args);
    if(value.kind==='water'){const event=await saveActionEvent(db,eventBase('water',{volume:value.volume_ml!,beverage:'água'},value.occurred_at,value.notes),key);return textResult({saved:true,event});}
    const category=value.kind==='bowel'?'bowel':value.kind==='checkin'||value.kind==='activity'?'checkin_history':'supplement';
    const payload={...value,record_type:value.kind};const result=await db.from('health_records').insert({user_id:process.env.HEALTH_GPT_USER_ID!,category,recorded_on:new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/London',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date(value.occurred_at)),recorded_at:value.occurred_at,payload,source:'ChatGPT'}).select().single();if(result.error)throw new Error(result.error.message);return textResult({saved:true,record:result.data});
  }
  if (name === 'registrar_agua') {
    const presetVolumes: Record<string, number> = { copo: 650, garrafa: 590 };
    const preset = typeof args.preset === 'string' ? args.preset.toLowerCase() : undefined;
    const volume = preset ? presetVolumes[preset] : args.volume_ml;
    if (typeof volume !== 'number') throw new Error('Informe um copo, uma garrafa ou o volume em mililitros.');
    const value = waterActionSchema.parse({ ...args, volume_ml: volume, idempotency_key: key });
    const event = await saveActionEvent(db, eventBase('water', { volume: value.volume_ml, beverage: 'água' }, value.occurred_at, value.notes), value.idempotency_key);
    return textResult({ saved: true, event });
  }
  if (name === 'registrar_checkin') {
    const value = checkinActionSchema.parse({ ...args, idempotency_key: key });
    const event = await saveActionEvent(db, eventBase('checkin', { preset: value.preset, scores: value.scores, activity: value.activity ?? '', moods: value.moods, environment: value.environment }, value.occurred_at, value.notes), value.idempotency_key);
    return textResult({ saved: true, event });
  }
  if (name === 'registrar_refeicao') {
    const value = mealActionSchema.parse({ ...args, idempotency_key: key });
    const event = await saveActionEvent(db, eventBase('meal', { name: value.name, meal_type: value.meal_type, items: value.items, hunger: value.hunger, satiety: value.satiety }, value.occurred_at, value.notes, value.estimated), value.idempotency_key);
    return textResult({ saved: true, event });
  }
  if (name === 'consultar_resumo_diario') return textResult(await dailySummary(db, process.env.HEALTH_GPT_USER_ID!, typeof args.date === 'string' ? args.date : undefined));
  if (name === 'registrar_sono') return textResult({ saved: true, record: await saveRecord(db,'sleep',args) });
  if (name === 'registrar_exercicio') return textResult(await saveExercise(db,process.env.HEALTH_GPT_USER_ID!,args));
  if (name === 'registrar_fezes') return textResult({ saved: true, record: await saveRecord(db,'bowel',args) });
  if (name === 'registrar_suplementos') return textResult({ saved: true, record: await saveRecord(db,'supplement',args) });
  if (name === 'registrar_tenis') return textResult(await saveExercise(db,process.env.HEALTH_GPT_USER_ID!,args,true));
  if (name === 'planejar_semana') { const plans=Array.isArray(args.plans)?args.plans:[]; const saved=[]; for(const raw of plans){const plan=input(raw);const date=dateFrom(plan.date),dayType=String(plan.day_type??'customizado'),targets=input(plan.targets);const result=await db.from('day_plans').upsert({user_id:process.env.HEALTH_GPT_USER_ID!,local_date:date,day_type:dayType,targets,agenda:Array.isArray(plan.agenda)?plan.agenda:[],rationale:String(plan.rationale??'')},{onConflict:'user_id,local_date'}).select().single();if(result.error)throw new Error(result.error.message);const day=await db.from('days').upsert({user_id:process.env.HEALTH_GPT_USER_ID!,local_date:date,day_type:dayType,targets:Object.fromEntries(Object.entries(targets).filter(([key])=>key!=='sodium'))},{onConflict:'user_id,local_date'});if(day.error)throw new Error(day.error.message);if('sodium' in targets)await updateProfile(db,process.env.HEALTH_GPT_USER_ID!,p=>({...p,['personal_sodium_date_'+date]:targets.sodium}));saved.push(result.data);} return textResult({saved:true,plans:saved}); }
  if (name === 'consultar_itens') { const date=dateFrom(args.date);const [events,records]=await Promise.all([db.from('events').select('id,local_date,timestamp,type,data,notes,source').eq('user_id',process.env.HEALTH_GPT_USER_ID!).eq('local_date',date).order('timestamp'),db.from('health_records').select('id,category,recorded_on,recorded_at,payload,source').eq('user_id',process.env.HEALTH_GPT_USER_ID!).eq('recorded_on',date).order('recorded_at')]);if(events.error||records.error)throw new Error(events.error?.message??records.error?.message);return textResult({date,eventos:events.data,registros:records.data}); }
  if(name==='editar_item'||name==='excluir_item'){
   const resource=args.collection==='evento'?'eventos':args.collection==='registro'?'registros':null;if(!resource)throw new Error('Coleção inválida.');
   const read=await siteRead(db,process.env.HEALTH_GPT_USER_ID!,{resource,id:args.id,limit:1});const item=read.items?.[0];if(!item)throw new Error('Item não encontrado.');
   const operations:any[]=[];const escape=(key:string)=>key.replaceAll('~','~0').replaceAll('/','~1');
   for(const [field,value] of Object.entries(input(args.data)))operations.push({op:'add',path:`/${resource==='eventos'?'data':'payload'}/${escape(field)}`,value});
   if(typeof args.notes==='string')operations.push({op:'add',path:resource==='eventos'?'/notes':'/payload/notes',value:args.notes});
   if(typeof args.occurred_at==='string'&&resource==='eventos')operations.push({op:'replace',path:'/timestamp',value:args.occurred_at});
   if(typeof args.date==='string'&&resource==='registros')operations.push({op:'replace',path:'/recorded_on',value:args.date});
   return textResult(await siteWrite(db,process.env.HEALTH_GPT_USER_ID!,name==='excluir_item'?'delete':'edit',{resource,id:args.id,expected_version:item.version,operations}));
  }
  if (name === 'meu_dia') { const date=dateFrom(args.date);const [summary,records,plan]=await Promise.all([dailySummary(db,process.env.HEALTH_GPT_USER_ID!,date),db.from('health_records').select('category,recorded_at,payload,source').eq('user_id',process.env.HEALTH_GPT_USER_ID!).eq('recorded_on',date).order('recorded_at'),db.from('day_plans').select('*').eq('user_id',process.env.HEALTH_GPT_USER_ID!).eq('local_date',date).maybeSingle()]);if(records.error||plan.error)throw new Error(records.error?.message??plan.error?.message);return textResult({date,summary,health_records:records.data,plan:plan.data,analysis_instruction:'Compare carga planejada e realizada; conecte sono, exercício, digestão, refeições, hidratação e check-ins quando houver evidência. Diga também o que ainda não é possível concluir.'}); }
  throw new Error('Ferramenta não encontrada.');
}

export async function OPTIONS() { return new NextResponse(null, { status: 204, headers: { allow: 'POST, OPTIONS' } }); }

export async function POST(request: Request) {
  const access=authenticated(request);if (!access) return challenge(request);
  let body: { id?: unknown; method?: string; params?: any };
  try { body = await request.json(); } catch { return rpcError(null, -32700, 'JSON inválido.'); }
  if (body.method === 'initialize') return rpc(body.id, { protocolVersion: body.params?.protocolVersion ?? '2025-06-18', capabilities: { tools: {} }, serverInfo: { name: 'painel-do-felipe', version: '2.0.0' }, instructions: 'Use as ferramentas para consultar ou salvar dados. Quando um envio gerar mais de uma gravação, faça as consultas primeiro e mande TODAS as gravações juntas em registrar_varios (uma só confirmação). Para água, “copo” é sempre 650 ml e “garrafa” é sempre 590 ml; registre esses atalhos diretamente. Em refeições, separe cada ingrediente e registre nutrientes por 100 g, incluindo vitaminas e minerais. Se inferir porções ou nutrição a partir de texto ou imagem, salve como estimativa (estimated=true), nunca como valor exato. Para corrigir ou apagar um item, consulte primeiro os itens da data; identifique o item específico antes de editar ou excluir. O pedido explícito do usuário autoriza a operação: não peça confirmação novamente se o alvo e a mudança estiverem claros. Você pode consultar, adicionar, editar e excluir os dados de TODAS as áreas do site com estrutura_do_site, consultar_dados_site, adicionar_dados_site, editar_dados_site e excluir_dados_site. Descubra os campos com estrutura_do_site, consulte dados e versão antes de editar; nunca afirme sucesso sem retorno salvo. Totais, notas automáticas e gráficos são recalculados pelos dados de origem.' });
  if (body.method === 'notifications/initialized') return new NextResponse(null, { status: 202 });
  if (body.method === 'tools/list') return rpc(body.id, { tools: toolList });
  if (body.method === 'tools/call') {
    try { const name=body.params?.name;const required=toolList.find(tool=>tool.name===name)?.annotations.readOnlyHint?'health:read':'health:write';if(!access.scope.split(' ').includes(required))throw new Error('A conexão não tem permissão para esta operação.');const result=await callTool(name,body.params?.arguments);if(!toolList.find(tool=>tool.name===name)?.annotations.readOnlyHint)revalidatePath('/','layout');return rpc(body.id,result); }
    catch (error) { return rpc(body.id, { content: [{ type: 'text', text: error instanceof Error ? error.message : 'Não foi possível concluir a operação.' }], isError: true }); }
  }
  return rpcError(body.id, -32601, 'Método não suportado.');
}
