import { randomUUID } from 'node:crypto';
import { NextResponse } from 'next/server';
import { checkinActionSchema, dailySummary, eventBase, mealActionSchema, saveActionEvent, waterActionSchema } from '@/lib/gpt-action';
import { readAccessToken } from '@/lib/mcp-oauth';
import { createClient } from '@supabase/supabase-js';

export const runtime = 'nodejs';

const toolList = [
  { name: 'registrar_agua', title: 'Registrar água', description: 'Registra água ingerida. Para os atalhos do dashboard, use preset "copo" (650 ml) ou "garrafa" (590 ml), sem pedir os mililitros. Use volume_ml somente para outro volume informado pelo usuário.', inputSchema: { type: 'object', properties: { preset: { type: 'string', enum: ['copo', 'garrafa'], description: 'Atalho fixo: copo = 650 ml; garrafa = 590 ml.' }, volume_ml: { type: 'number', minimum: 1, maximum: 10000, description: 'Use apenas quando não for copo nem garrafa.' }, occurred_at: { type: 'string', description: 'Data e hora em ISO 8601. Omita para agora.' }, notes: { type: 'string' } } }, annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false }, securitySchemes: [{ type: 'oauth2', scopes: ['health:write'] }] },
  { name: 'registrar_checkin', title: 'Registrar check-in', description: 'Registra sono, energia, humor, atividade e observações de um check-in confirmado.', inputSchema: { type: 'object', properties: { preset: { type: 'string' }, scores: { type: 'object' }, activity: { type: 'string' }, moods: { type: 'array', items: { type: 'string' } }, environment: { type: 'array', items: { type: 'string' } }, occurred_at: { type: 'string' }, notes: { type: 'string' } } }, annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false }, securitySchemes: [{ type: 'oauth2', scopes: ['health:write'] }] },
  { name: 'registrar_refeicao', title: 'Registrar refeição', description: 'Registra uma refeição confirmada. Separe todos os ingredientes em itens individuais e preencha TODOS os nutrientes por 100 g: macros, vitaminas e minerais. Não use null e não omita campos. Quando a porção ou nutrição vier de descrição ou foto, faça a melhor estimativa e use estimated=true. Use estimated=false somente com rótulo ou valor informado pelo usuário.', inputSchema: { type: 'object', required: ['name', 'items'], properties: { name: { type: 'string' }, meal_type: { type: 'string' }, items: { type: 'array', items: { type: 'object', required: ['name', 'grams', 'nutrition'], properties: { name: { type: 'string' }, grams: { type: 'number', minimum: 1 }, nutrition: { type: 'object', required: ['calories','protein','carbs','fat','saturated_fat','fibre','sugar','sodium','vitamin_a','vitamin_c','vitamin_d','vitamin_b12','folate','calcium','iron','magnesium','potassium','zinc'], properties: { calories: { type: 'number', minimum: 0, description: 'kcal por 100 g' }, protein: { type: 'number', minimum: 0, description: 'g por 100 g' }, carbs: { type: 'number', minimum: 0, description: 'g por 100 g' }, fat: { type: 'number', minimum: 0, description: 'g por 100 g' }, saturated_fat: { type: 'number', minimum: 0, description: 'g por 100 g' }, fibre: { type: 'number', minimum: 0, description: 'g por 100 g' }, sugar: { type: 'number', minimum: 0, description: 'g por 100 g' }, sodium: { type: 'number', minimum: 0, description: 'mg por 100 g' }, vitamin_a: { type: 'number', minimum: 0, description: 'µg por 100 g' }, vitamin_c: { type: 'number', minimum: 0, description: 'mg por 100 g' }, vitamin_d: { type: 'number', minimum: 0, description: 'µg por 100 g' }, vitamin_b12: { type: 'number', minimum: 0, description: 'µg por 100 g' }, folate: { type: 'number', minimum: 0, description: 'µg por 100 g' }, calcium: { type: 'number', minimum: 0, description: 'mg por 100 g' }, iron: { type: 'number', minimum: 0, description: 'mg por 100 g' }, magnesium: { type: 'number', minimum: 0, description: 'mg por 100 g' }, potassium: { type: 'number', minimum: 0, description: 'mg por 100 g' }, zinc: { type: 'number', minimum: 0, description: 'mg por 100 g' } } } } } }, hunger: { type: 'number', minimum: 0, maximum: 10 }, satiety: { type: 'number', minimum: 0, maximum: 10 }, estimated: { type: 'boolean', description: 'true para valores inferidos ou estimados; false apenas para dados confirmados.' }, occurred_at: { type: 'string' }, notes: { type: 'string' } } }, annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false }, securitySchemes: [{ type: 'oauth2', scopes: ['health:write'] }] },
  { name: 'consultar_resumo_diario', title: 'Consultar resumo diário', description: 'Consulta água, refeições, metas e eventos de uma data.', inputSchema: { type: 'object', properties: { date: { type: 'string', description: 'Data AAAA-MM-DD. Omita para hoje.' } } }, annotations: { readOnlyHint: true, destructiveHint: false, openWorldHint: false }, securitySchemes: [{ type: 'oauth2', scopes: ['health:read'] }] },
  { name: 'registrar_sono', title: 'Registrar sono', description: 'Registra sono manualmente ou a partir de uma imagem do Apple Health/Watch. Extraia tudo que estiver legível: duração, horários, acordado, REM, Core, profundo, frequência cardíaca, respiração, SpO2 e observações. Preserve valores ausentes como ausentes.', inputSchema: { type: 'object', required: ['date','data'], properties: { date: { type: 'string' }, data: { type: 'object' }, notes: { type: 'string' } } }, annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false }, securitySchemes: [{ type: 'oauth2', scopes: ['health:write'] }] },
  { name: 'registrar_exercicio', title: 'Registrar exercício', description: 'Registra exercício manualmente ou a partir de imagem do Apple Fitness/Watch. Extraia todos os dados visíveis: modalidade, duração, calorias ativas e totais, distância, passos, FC, zonas, esforço e horários.', inputSchema: { type: 'object', required: ['date','data'], properties: { date: { type: 'string' }, data: { type: 'object' }, notes: { type: 'string' } } }, annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false }, securitySchemes: [{ type: 'oauth2', scopes: ['health:write'] }] },
  { name: 'registrar_fezes', title: 'Registrar fezes', description: 'Registra fezes com quantidade, consistência pessoal de 0 a 10, horário, urgência, dor, gases, estufamento e observações.', inputSchema: { type: 'object', required: ['date','data'], properties: { date: { type: 'string' }, data: { type: 'object', required: ['quantidade','consistencia'] }, notes: { type: 'string' } } }, annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false }, securitySchemes: [{ type: 'oauth2', scopes: ['health:write'] }] },
  { name: 'registrar_suplementos', title: 'Registrar suplementos', description: 'Registra suplementos do dia ou noite e horário. Rotina diurna: vitamina D, vitamina E, ômega-3, CoQ10, selênio, vitamina C e glucosamina. Rotina noturna: magnésio e ashwagandha. Registre apenas o que o usuário confirmou ter tomado.', inputSchema: { type: 'object', required: ['date','period','items'], properties: { date: { type: 'string' }, period: { type: 'string', enum: ['dia','noite'] }, items: { type: 'array', items: { type: 'string' } }, notes: { type: 'string' } } }, annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false }, securitySchemes: [{ type: 'oauth2', scopes: ['health:write'] }] },
  { name: 'registrar_tenis', title: 'Registrar tênis', description: 'Registra treino ou jogo de tênis, inclusive dados pré e pós. Para partidas, inclua outcome (vitória ou derrota) e sets como lista de objetos {felipe:number, adversario:number}; derive também score como, por exemplo, 6-2, 6-0. Inclua tipo, adversário/parceiro, duração, energia física, clareza, motivação, foco, esforço, sintomas, análise livre e todos os dados fornecidos. Ao ler foto de calendário ou placar, extraia cada set visível.', inputSchema: { type: 'object', required: ['date','data'], properties: { date: { type: 'string' }, data: { type: 'object' }, notes: { type: 'string' } } }, annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false }, securitySchemes: [{ type: 'oauth2', scopes: ['health:write'] }] },
  { name: 'planejar_semana', title: 'Planejar semana e metas', description: 'Quando o usuário enviar a agenda semanal ou foto do calendário, extraia os compromissos e crie um plano para cada dia com tipo de dia e metas de água, calorias, proteína, carboidratos, gordura, gordura saturada e fibra adequadas à carga. Explique a lógica sem fazer diagnóstico.', inputSchema: { type: 'object', required: ['plans'], properties: { plans: { type: 'array', items: { type: 'object', required: ['date','day_type','targets','agenda'], properties: { date: { type: 'string' }, day_type: { type: 'string' }, targets: { type: 'object' }, agenda: { type: 'array', items: { type: 'string' } }, rationale: { type: 'string' } } } } } }, annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false }, securitySchemes: [{ type: 'oauth2', scopes: ['health:write'] }] },
  { name: 'meu_dia', title: 'Analisar meu dia', description: 'Use quando o usuário disser “Meu dia”. Consulta eventos, sono, exercício, suplementos, fezes, tênis e plano do dia. Depois de chamar, produza 3 a 5 insights concretos e cautelosos sobre padrões, recuperação, carga, hidratação e próximos passos; não apenas uma lista de totais e não faça diagnóstico médico.', inputSchema: { type: 'object', properties: { date: { type: 'string' } } }, annotations: { readOnlyHint: true, destructiveHint: false, openWorldHint: false }, securitySchemes: [{ type: 'oauth2', scopes: ['health:read'] }] },
  { name: 'consultar_itens', title: 'Consultar itens para editar', description: 'Lista eventos e registros de saúde de uma data, incluindo id, para localizar com segurança o item que o usuário quer corrigir ou excluir.', inputSchema: { type: 'object', properties: { date: { type: 'string', description: 'AAAA-MM-DD. Omita para hoje.' } } }, annotations: { readOnlyHint: true, destructiveHint: false, openWorldHint: false }, securitySchemes: [{ type: 'oauth2', scopes: ['health:read'] }] },
  { name: 'editar_item', title: 'Editar item', description: 'Edita um item existente depois de consultar_itens e identificar o id correto. Antes de alterar, confirme com o usuário qual item e quais valores devem mudar. Para evento, data altera occurred_at e data mescla campos em data. Para registro, data mescla campos no payload e date altera a data do registro.', inputSchema: { type: 'object', required: ['collection','id'], properties: { collection: { type: 'string', enum: ['evento','registro'] }, id: { type: 'string' }, date: { type: 'string', description: 'AAAA-MM-DD, opcional para registro.' }, occurred_at: { type: 'string', description: 'ISO 8601, opcional para evento.' }, data: { type: 'object', description: 'Somente campos a atualizar; são mesclados aos dados atuais.' }, notes: { type: 'string' } } }, annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false }, securitySchemes: [{ type: 'oauth2', scopes: ['health:write'] }] },
  { name: 'excluir_item', title: 'Excluir item', description: 'Exclui permanentemente um evento ou registro de saúde identificado por consultar_itens. Use somente após confirmação explícita do usuário sobre o item a apagar.', inputSchema: { type: 'object', required: ['collection','id'], properties: { collection: { type: 'string', enum: ['evento','registro'] }, id: { type: 'string' } } }, annotations: { readOnlyHint: false, destructiveHint: true, openWorldHint: false }, securitySchemes: [{ type: 'oauth2', scopes: ['health:write'] }] },
];

function rpc(id: unknown, result: unknown) { return NextResponse.json({ jsonrpc: '2.0', id: id ?? null, result }); }
function rpcError(id: unknown, code: number, message: string) { return NextResponse.json({ jsonrpc: '2.0', id: id ?? null, error: { code, message } }); }

function authenticated(request: Request) {
  const header = request.headers.get('authorization');
  const token = header?.match(/^Bearer (.+)$/i)?.[1];
  const access = token ? readAccessToken(token) : null;
  return access?.sub === process.env.HEALTH_GPT_USER_ID ? access : null;
}

function challenge(request: Request) {
  const origin = new URL(request.url).origin;
  return new NextResponse(null, { status: 401, headers: { 'www-authenticate': `Bearer resource_metadata="${origin}/.well-known/oauth-protected-resource", scope="health:read health:write"` } });
}

function database() {
  const url = process.env.NEXT_PUBLIC_SUPABASE_URL;
  const key = process.env.SUPABASE_SERVICE_ROLE_KEY;
  if (!url || !key) throw new Error('O servidor ainda não foi configurado.');
  return createClient(url, key, { auth: { persistSession: false, autoRefreshToken: false } });
}

function textResult(value: unknown) { return { content: [{ type: 'text', text: JSON.stringify(value) }], structuredContent: value }; }
function input(value: unknown) { return value && typeof value === 'object' && !Array.isArray(value) ? value as Record<string, unknown> : {}; }
function dateFrom(value: unknown) { return typeof value === 'string' && /^\d{4}-\d{2}-\d{2}$/.test(value) ? value : new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/London',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date()); }
async function saveRecord(db: ReturnType<typeof database>, category: string, args: Record<string, unknown>) { const date=dateFrom(args.date); const result=await db.from('health_records').insert({ user_id: process.env.HEALTH_GPT_USER_ID!, category, recorded_on: date, recorded_at: new Date().toISOString(), payload: args.data ?? args, source: 'ChatGPT' }).select().single(); if(result.error) throw new Error(result.error.message); return result.data; }

async function callTool(name: string, argumentsValue: unknown) {
  const args = input(argumentsValue); const db = database(); const key = typeof args.idempotency_key === 'string' ? args.idempotency_key : randomUUID();
  if (name === 'registrar_agua') {
    const presetVolumes: Record<string, number> = { copo: 650, garrafa: 590 };
    const preset = typeof args.preset === 'string' ? args.preset.toLowerCase() : undefined;
    const volume = preset ? presetVolumes[preset] : args.volume_ml;
    if (typeof volume !== 'number') throw new Error('Informe um copo, uma garrafa ou o volume em mililitros.');
    const value = waterActionSchema.parse({ ...args, volume_ml: volume, idempotency_key: key });
    const event = await saveActionEvent(db, eventBase('water', { volume: value.volume_ml, beverage: 'água' }, value.occurred_at, value.notes), value.idempotency_key);
    return textResult({ saved: true, event });
  }
  if (name === 'registrar_checkin') {
    const value = checkinActionSchema.parse({ ...args, idempotency_key: key });
    const event = await saveActionEvent(db, eventBase('checkin', { preset: value.preset, scores: value.scores, activity: value.activity ?? '', moods: value.moods, environment: value.environment }, value.occurred_at, value.notes), value.idempotency_key);
    return textResult({ saved: true, event });
  }
  if (name === 'registrar_refeicao') {
    const value = mealActionSchema.parse({ ...args, idempotency_key: key });
    const event = await saveActionEvent(db, eventBase('meal', { name: value.name, meal_type: value.meal_type, items: value.items, hunger: value.hunger, satiety: value.satiety }, value.occurred_at, value.notes, value.estimated), value.idempotency_key);
    return textResult({ saved: true, event });
  }
  if (name === 'consultar_resumo_diario') return textResult(await dailySummary(db, process.env.HEALTH_GPT_USER_ID!, typeof args.date === 'string' ? args.date : undefined));
  if (name === 'registrar_sono') return textResult({ saved: true, record: await saveRecord(db,'sleep',args) });
  if (name === 'registrar_exercicio') return textResult({ saved: true, record: await saveRecord(db,'activity',args) });
  if (name === 'registrar_fezes') return textResult({ saved: true, record: await saveRecord(db,'bowel',args) });
  if (name === 'registrar_suplementos') return textResult({ saved: true, record: await saveRecord(db,'supplement',args) });
  if (name === 'registrar_tenis') return textResult({ saved: true, record: await saveRecord(db,'tennis',args) });
  if (name === 'planejar_semana') { const plans=Array.isArray(args.plans)?args.plans:[]; const saved=[]; for(const raw of plans){const plan=input(raw);const date=dateFrom(plan.date),dayType=String(plan.day_type??'customizado'),targets=input(plan.targets);const result=await db.from('day_plans').upsert({user_id:process.env.HEALTH_GPT_USER_ID!,local_date:date,day_type:dayType,targets,agenda:Array.isArray(plan.agenda)?plan.agenda:[],rationale:String(plan.rationale??'')},{onConflict:'user_id,local_date'}).select().single();if(result.error)throw new Error(result.error.message);const day=await db.from('days').upsert({user_id:process.env.HEALTH_GPT_USER_ID!,local_date:date,day_type:dayType,targets},{onConflict:'user_id,local_date'});if(day.error)throw new Error(day.error.message);saved.push(result.data);} return textResult({saved:true,plans:saved}); }
  if (name === 'consultar_itens') { const date=dateFrom(args.date);const [events,records]=await Promise.all([db.from('events').select('id,local_date,timestamp,type,data,notes,source').eq('user_id',process.env.HEALTH_GPT_USER_ID!).eq('local_date',date).order('timestamp'),db.from('health_records').select('id,category,recorded_on,recorded_at,payload,source').eq('user_id',process.env.HEALTH_GPT_USER_ID!).eq('recorded_on',date).order('recorded_at')]);if(events.error||records.error)throw new Error(events.error?.message??records.error?.message);return textResult({date,eventos:events.data,registros:records.data}); }
  if (name === 'editar_item') { const id=typeof args.id==='string'?args.id:'';if(!/^[0-9a-f-]{36}$/i.test(id))throw new Error('Identificador inválido. Consulte os itens novamente.');const collection=args.collection;if(collection==='evento'){const current=await db.from('events').select('*').eq('id',id).eq('user_id',process.env.HEALTH_GPT_USER_ID!).single();if(current.error||!current.data)throw new Error('Evento não encontrado.');const occurred=typeof args.occurred_at==='string'?new Date(args.occurred_at):null;if(occurred&&Number.isNaN(occurred.valueOf()))throw new Error('Horário inválido.');const update:any={data:{...input(current.data.data),...input(args.data)}};if(typeof args.notes==='string')update.notes=args.notes;if(occurred){update.timestamp=occurred.toISOString();update.local_date=dateFrom(update.timestamp.slice(0,10));}const result=await db.from('events').update(update).eq('id',id).eq('user_id',process.env.HEALTH_GPT_USER_ID!).select().single();if(result.error)throw new Error(result.error.message);return textResult({updated:true,item:result.data});}if(collection==='registro'){const current=await db.from('health_records').select('*').eq('id',id).eq('user_id',process.env.HEALTH_GPT_USER_ID!).single();if(current.error||!current.data)throw new Error('Registro não encontrado.');const update:any={payload:{...input(current.data.payload),...input(args.data)}};if(typeof args.notes==='string')update.payload.notes=args.notes;if(typeof args.date==='string')update.recorded_on=dateFrom(args.date);const result=await db.from('health_records').update(update).eq('id',id).eq('user_id',process.env.HEALTH_GPT_USER_ID!).select().single();if(result.error)throw new Error(result.error.message);return textResult({updated:true,item:result.data});}throw new Error('Coleção inválida.'); }
  if (name === 'excluir_item') { const id=typeof args.id==='string'?args.id:'';if(!/^[0-9a-f-]{36}$/i.test(id))throw new Error('Identificador inválido. Consulte os itens novamente.');const table=args.collection==='evento'?'events':args.collection==='registro'?'health_records':null;if(!table)throw new Error('Coleção inválida.');const result=await db.from(table).delete().eq('id',id).eq('user_id',process.env.HEALTH_GPT_USER_ID!);if(result.error)throw new Error(result.error.message);return textResult({deleted:true,id,collection:args.collection}); }
  if (name === 'meu_dia') { const date=dateFrom(args.date);const [summary,records,plan]=await Promise.all([dailySummary(db,process.env.HEALTH_GPT_USER_ID!,date),db.from('health_records').select('category,recorded_at,payload,source').eq('user_id',process.env.HEALTH_GPT_USER_ID!).eq('recorded_on',date).order('recorded_at'),db.from('day_plans').select('*').eq('user_id',process.env.HEALTH_GPT_USER_ID!).eq('local_date',date).maybeSingle()]);if(records.error||plan.error)throw new Error(records.error?.message??plan.error?.message);return textResult({date,summary,health_records:records.data,plan:plan.data,analysis_instruction:'Compare carga planejada e realizada; conecte sono, exercício, digestão, refeições, hidratação e check-ins quando houver evidência. Diga também o que ainda não é possível concluir.'}); }
  throw new Error('Ferramenta não encontrada.');
}

export async function OPTIONS() { return new NextResponse(null, { status: 204, headers: { allow: 'POST, OPTIONS' } }); }

export async function POST(request: Request) {
  if (!authenticated(request)) return challenge(request);
  let body: { id?: unknown; method?: string; params?: any };
  try { body = await request.json(); } catch { return rpcError(null, -32700, 'JSON inválido.'); }
  if (body.method === 'initialize') return rpc(body.id, { protocolVersion: body.params?.protocolVersion ?? '2025-06-18', capabilities: { tools: {} }, serverInfo: { name: 'saude-do-felipe', version: '1.2.0' }, instructions: 'Use as ferramentas para consultar ou salvar dados. Para água, “copo” é sempre 650 ml e “garrafa” é sempre 590 ml; registre esses atalhos diretamente. Em refeições, separe cada ingrediente e registre nutrientes por 100 g, incluindo vitaminas e minerais. Se inferir porções ou nutrição a partir de texto ou imagem, salve como estimativa (estimated=true), nunca como valor exato. Para corrigir ou apagar um item, consulte primeiro os itens da data; confirme o item específico antes de editar ou excluir.' });
  if (body.method === 'notifications/initialized') return new NextResponse(null, { status: 202 });
  if (body.method === 'tools/list') return rpc(body.id, { tools: toolList });
  if (body.method === 'tools/call') {
    try { return rpc(body.id, await callTool(body.params?.name, body.params?.arguments)); }
    catch (error) { return rpc(body.id, { content: [{ type: 'text', text: error instanceof Error ? error.message : 'Não foi possível concluir a operação.' }], isError: true }); }
  }
  return rpcError(body.id, -32601, 'Método não suportado.');
}
