import { AppShell } from '@/components/app-shell';
import { LifeInformation } from '@/components/life-information';
import { CarInformation } from '@/components/car-information';
import { FinanceDashboard,TravelDashboard } from '@/components/personal-dashboard';
import { HealthProfile } from '@/components/health-profile';
import { HeartPulse,Car,Wallet,Plane,ChevronDown } from 'lucide-react';
import { demoMeasurements,demoProfile } from '@/lib/demo-sections';
export const dynamic='force-dynamic';
export default function Page(){const personal=demoProfile();return <AppShell title="Minhas informações" active="minhas-informacoes" demo><div className="content"><div className="page-heading"><div><span className="eyebrow">DADOS PRIVADOS</span><h1>Minhas informações</h1><p>Saúde, carro e finanças. Seus detalhes organizados em um só lugar.</p></div></div><div className="information-sections"><details className="information-card tint-health"><summary><span className="information-icon"><HeartPulse strokeWidth={1.9} aria-hidden/></span><span><strong>Saúde</strong><small>Perfil, medidas corporais e histórico de saúde</small></span><ChevronDown className="expand-arrow"/></summary><div className="information-body"><HealthProfile initial={personal} measurements={demoMeasurements()}/></div></details><details className="information-card car-information-card"><summary><span className="information-icon"><Car strokeWidth={1.9} aria-hidden/></span><span><strong>Carro</strong><small>Seu Eclipse Cross, documentos e carros anteriores</small></span><ChevronDown className="expand-arrow"/></summary><div className="information-body"><CarInformation initial={personal.personal_car}/></div></details><details className="information-card tint-finance"><summary><span className="information-icon"><Wallet strokeWidth={1.9} aria-hidden/></span><span><strong>Financeiro</strong><small>Planejamento, despesas e formas de pagamento</small></span><ChevronDown className="expand-arrow"/></summary><div className="information-body"><FinanceDashboard initial={personal.personal_finance} headingLevel="h2"/></div></details><details className="information-card tint-travel"><summary><span className="information-icon"><Plane strokeWidth={1.9} aria-hidden/></span><span><strong>Viagens</strong><small>Lugares visitados, notas e lembranças</small></span><ChevronDown className="expand-arrow"/></summary><div className="information-body"><TravelDashboard initial={personal.personal_trips} headingLevel="h2"/></div></details><LifeInformation profile={personal}/></div></div></AppShell>}
