import { test } from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { PGlite } from '@electric-sql/pglite';
test('PostgreSQL migration: RLS, audit, timezone, validation and per-user targets',async()=>{
 const db=new PGlite();
 await db.exec(`create schema auth;create role anon;create role authenticated;
 create table auth.users(id uuid primary key);
 create function auth.uid() returns uuid language sql stable as $$ select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid $$;
 grant usage on schema auth to authenticated,anon;`);
 const sql=readFileSync('supabase/migrations/202609250001_core.sql','utf8').replace('create extension if not exists pgcrypto;','');
 await db.exec(sql);await db.exec(readFileSync('supabase/migrations/202609250002_snapshot_targets.sql','utf8'));
 const a='10000000-0000-4000-8000-000000000001',b='10000000-0000-4000-8000-000000000002';
 await db.query('insert into auth.users(id) values($1),($2)',[a,b]);
 assert.equal((await db.query<{count:number}>('select count(*)::int as count from public.target_templates')).rows[0].count,12);
 await db.exec(`set role authenticated;set request.jwt.claim.sub='${a}';`);
 assert.equal((await db.query<{count:number}>('select count(*)::int as count from public.target_templates')).rows[0].count,6);
 const result=await db.query<{id:string;local_date:string}>(`insert into public.events(user_id,timestamp,local_date,type,measurement_type,data) values($1,'2026-09-25T23:30Z','2000-01-01','water','measured','{"kind":"water","volume":650,"beverage":"água"}') returning id,local_date::text`,[a]);
 assert.equal((await db.query('select * from public.days')).rows.length,1);
 const id=result.rows[0].id;assert.match(String(result.rows[0].local_date),/2026-09-26/);
 await assert.rejects(()=>db.query(`insert into public.events(user_id,timestamp,local_date,type,measurement_type,data) values($1,now(),current_date,'water','measured','{"kind":"water","volume":1,"beverage":"água"}')`,[b]));
 await assert.rejects(()=>db.query(`insert into public.events(user_id,timestamp,local_date,type,measurement_type,data) values($1,now(),current_date,'water','measured','{"kind":"water","volume":-1,"beverage":"água"}')`,[a]));
 await db.exec(`set request.jwt.claim.sub='${b}';`);
 assert.equal((await db.query('select * from public.events')).rows.length,0);
 assert.equal((await db.query('update public.events set notes=$1 where id=$2 returning id',['intrusion',id])).rows.length,0);
 assert.equal((await db.query('delete from public.events where id=$1 returning id',[id])).rows.length,0);
 await db.exec(`set request.jwt.claim.sub='${a}';`);
 await db.query('update public.events set notes=$1 where id=$2',['Corrected',id]);
 assert.equal((await db.query('select * from public.event_revisions')).rows.length,1);
 await assert.rejects(()=>db.exec('delete from public.event_revisions'));
 await db.query('delete from public.events where id=$1',[id]);
 assert.equal((await db.query('select * from public.event_revisions')).rows.length,2);
 await db.query(`insert into public.checkin_drafts(user_id,payload) values($1,'{}')`,[a]);
 await db.query(`insert into public.events(user_id,timestamp,local_date,type,measurement_type,data) values($1,now(),current_date,'checkin','subjective','{"kind":"checkin","scores":{"anxiety":0,"stress":null}}')`,[a]);
 assert.equal((await db.query('select * from public.checkin_drafts')).rows.length,0);
 const checkin=(await db.query<{data:{scores:{anxiety:number;stress:null}}}>(`select data from public.events where type='checkin'`)).rows[0];assert.equal(checkin.data.scores.anxiety,0);assert.equal(checkin.data.scores.stress,null);
 await db.exec('reset role;set role anon;');await assert.rejects(()=>db.exec('select * from public.events'));
 await db.close();
});
