import {saveExercise} from '../lib/save-exercise';
import { test } from 'node:test';
import assert from 'node:assert/strict';
import { patchData,version,catalog,siteRead,siteWrite } from '../lib/site-crud';
function database(){const tables:Record<string,any[]>={health_profiles:[],health_records:[]};return {tables,from(table:string){const filters:((r:any)=>boolean)[]=[];let mode='read',data:any,one=false,range=[0,Infinity];const api:any={select(){return api;},eq(k:string,v:any){filters.push(r=>typeof r[k]==='object'?JSON.stringify(r[k])===v:r[k]===v);return api;},is(k:string,v:any){filters.push(r=>r[k]===v);return api;},order(){return api;},range(a:number,b:number){range=[a,b];return api;},maybeSingle(){one=true;return api;},single(){one=true;return api;},update(v:any){mode='update';data=v;return api;},insert(v:any){mode='insert';data=v;return api;},upsert(v:any){mode='upsert';data=v;return api;},delete(){mode='delete';return api;},then(resolve:any){let rows=tables[table]??(tables[table]=[]),found=rows.filter(r=>filters.every(f=>f(r)));if(mode==='insert'||mode==='upsert'){const row={updated_at:'initial',...data};rows.push(row);found=[row];}if(mode==='update')found.forEach(r=>Object.assign(r,data));if(mode==='delete')tables[table]=rows.filter(r=>!found.includes(r));resolve({data:one?structuredClone(found[0]??null):structuredClone(found.slice(range[0],range[1]+1)),error:null});}};return api;}};}
test('nested field editing preserves siblings and prevents prototype paths',()=>{const original={extra:{financing:{apr:'5.1',amount:'10000'}},rows:[{id:'a',value:10},{id:'b',value:20}]};const edited:any=patchData(original,[{op:'replace',path:'/extra/financing/apr',value:'4.5'},{op:'remove',path:'/rows/0'},{op:'add',path:'/rows/-',value:{id:'c',value:30}}]);assert.equal(edited.extra.financing.amount,'10000');assert.equal(original.extra.financing.apr,'5.1');assert.deepEqual(edited.rows.map((r:any)=>r.id),['b','c']);assert.throws(()=>patchData({},[{op:'add',path:'/__proto__/x',value:1}]));assert.equal(version({a:1,b:2}),version({b:2,a:1}));});
test('every personal section supports read, versioned save, field edit and clear without touching other sections',async()=>{const db:any=database();db.tables.health_profiles.push({user_id:'u',profile:{personal_car:{model:'Existing',registration:'ABC'},personal_preferences:{'Comida.Favoritas':'Arroz'}},updated_at:'old'});
 const read:any=await siteRead(db,'u',{resource:'carro'});await siteWrite(db,'u','edit',{resource:'carro',expected_version:read.version,operations:[{op:'replace',path:'/registration',value:'XYZ'}]});assert.equal(db.tables.health_profiles[0].profile.personal_car.registration,'XYZ');assert.equal(db.tables.health_profiles[0].profile.personal_preferences['Comida.Favoritas'],'Arroz');await assert.rejects(siteWrite(db,'u','edit',{resource:'carro',expected_version:read.version,operations:[{op:'replace',path:'/registration',value:'OLD'}]}));
 for(const resource of ['financeiro','cartao_credito','liga_tenis','investimentos','viagens','contas','documentos_datas','preferencias','resumo_perfil','perfil_saude']){const current:any=await siteRead(db,'u',{resource});const result=await siteWrite(db,'u','delete',{resource,expected_version:current.version});assert.equal(result.deleted,true);}
 assert.equal(db.tables.health_profiles[0].profile.personal_car.registration,'XYZ');
});
test('table edits and deletes are scoped to owner and read back saved fields',async()=>{const db:any=database();const id='5e933971-8591-49c8-8e13-b1e1fc357942';const data={category:'sleep',recorded_on:'2026-09-27',recorded_at:null,payload:{time_asleep_minutes:460,rem_minutes:120},source:'ChatGPT'};
 await siteWrite(db,'u','add',{resource:'registros',id,data});const read:any=await siteRead(db,'u',{resource:'registros',id});await assert.rejects(siteWrite(db,'another','delete',{resource:'registros',id,expected_version:read.items[0].version}));const edited=await siteWrite(db,'u','edit',{resource:'registros',id,expected_version:read.items[0].version,operations:[{op:'replace',path:'/payload/rem_minutes',value:130}]});assert.equal(edited.items[0].data.payload.time_asleep_minutes,460);assert.equal(edited.items[0].data.payload.rem_minutes,130);assert.equal((await siteWrite(db,'u','delete',{resource:'registros',id,expected_version:edited.items[0].version})).deleted,true);assert.equal(db.tables.health_records.length,0);
});
test('catalog covers editable areas and deep car fields',()=>{const c=catalog();assert.equal(c.resources.length,23);assert.ok(c.resources.some(r=>r.resource==='exames'));assert.ok(c.resources.some(r=>r.resource==='caju'));const car:any=c.resources.find(r=>r.resource==='carro');assert.ok(car.schema.properties.extra.properties.financing);assert.ok(car.schema.properties.previous);});
test('unknown fields cannot silently succeed and clear investment data remains empty',async()=>{const db:any=database();const car:any=await siteRead(db,'u',{resource:'carro'});await assert.rejects(siteWrite(db,'u','edit',{resource:'carro',expected_version:car.version,operations:[{op:'add',path:'/unknown_field',value:'ignored'}]}));const investments:any=await siteRead(db,'u',{resource:'investimentos'});await siteWrite(db,'u','delete',{resource:'investimentos',expected_version:investments.version});assert.deepEqual((await siteRead(db,'u',{resource:'investimentos'})).data,[]);});

test('exercise imports reuse identity and enrich a tennis record without replacing check-in or score',async()=>{const db:any=database();const first=await saveExercise(db,'u',{date:'2026-09-28',data:{activity_type:'Tênis',started_at:'2026-09-28T18:34:00+01:00',effort:4,score:'6-4'}});await saveExercise(db,'u',{date:'2026-09-28',data:{activity_type:'Tênis',started_at:'2026-09-28T18:34:00+01:00',active_calories:965}});assert.equal(db.tables.health_records.length,1);await saveExercise(db,'u',{date:'2026-09-28',data:{record_id:first.id,watch_effort:1,heart_rate_average:119}});assert.equal(db.tables.health_records[0].category,'tennis');assert.equal(db.tables.health_records[0].payload.effort,4);assert.equal(db.tables.health_records[0].payload.score,'6-4');assert.equal(db.tables.health_records[0].payload.watch_effort,1);await assert.rejects(saveExercise(db,'other',{date:'2026-09-28',data:{record_id:first.id,watch_effort:2}}));await saveExercise(db,'u',{date:'2026-09-28',data:{kind:'daily_metrics',total_calories:3069}});await saveExercise(db,'u',{date:'2026-09-28',data:{kind:'daily_metrics',steps:14899}});assert.equal(db.tables.health_records.length,2);assert.equal(db.tables.health_records[1].payload.total_calories,3069);});

test('credit card history can be added, corrected and removed through the generic site tools',async()=>{const db:any=database();
 const first:any=await siteRead(db,'u',{resource:'cartao_credito'});assert.equal(first.data.limit,6800);assert.equal(first.data.history[0].balance,6480);
 await siteWrite(db,'u','edit',{resource:'cartao_credito',expected_version:first.version,operations:[{op:'add',path:'/history/-',value:{id:'nov',date:'2026-11-01',balance:5000,notes:''}},{op:'replace',path:'/checkingBalance',value:2500}]});
 const second:any=await siteRead(db,'u',{resource:'cartao_credito'});assert.equal(second.data.history.length,2);assert.equal(second.data.checkingBalance,2500);
 await assert.rejects(siteWrite(db,'u','edit',{resource:'cartao_credito',expected_version:second.version,operations:[{op:'add',path:'/history/-',value:{id:'nov',date:'2026-11-02',balance:1,notes:''}}]}),/IDs duplicados/);
 await siteWrite(db,'u','edit',{resource:'cartao_credito',expected_version:second.version,operations:[{op:'replace',path:'/history/1/balance',value:4800},{op:'remove',path:'/history/0'}]});
 const third:any=await siteRead(db,'u',{resource:'cartao_credito'});assert.deepEqual(third.data.history.map((e:any)=>e.balance),[4800]);
});
