'use client';
import { useState } from 'react';
import { Activity, Check, Droplets, HeartPulse, Pill, SmilePlus, Sparkles } from 'lucide-react';
import { saveDiaryRecord } from '@/app/actions';
import { diaryLabels,diaryOptions,medicines,type DiaryInput } from '@/lib/diary-fields';
import { londonToISO } from '@/lib/domain';
import { Button } from './ui/button';

type Kind=DiaryInput['kind'];
const icons={checkin:SmilePlus,activity:Activity,bowel:HeartPulse,water:Droplets,vitamins:Sparkles,medication:Pill};
const nowLocal=()=>new Intl.DateTimeFormat('sv-SE',{timeZone:'Europe/London',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit'}).format(new Date()).replace(' ','T');
function Choices({title,values,selected,onChange,single=false}:{title:string;values:readonly string[];selected:string[];onChange:(value:string[])=>void;single?:boolean}){
 return <fieldset className="diary-choice"><legend>{title}</legend><div className="choice-chips tags">{values.map(value=><button type="button" className={selected.includes(value)?'selected':''} aria-pressed={selected.includes(value)} key={value} onClick={()=>onChange(single?[value]:selected.includes(value)?selected.filter(item=>item!==value):[...selected,value])}>{selected.includes(value)&&<Check size={14} strokeWidth={1.9} aria-hidden="true"/>}{value}</button>)}</div></fieldset>;
}
export function DiaryRegister({initialKind='checkin',date,onSaved,showTabs=true}:{initialKind?:Kind;date?:string;onSaved?:()=>void;showTabs?:boolean}){
 const initialWhen=date?(date===nowLocal().slice(0,10)?nowLocal():`${date}T12:00`):nowLocal();
 const [kind,setKind]=useState<Kind>(initialKind),[values,setValues]=useState<Record<string,string[]>>({}),[notes,setNotes]=useState(''),[emotionNotes,setEmotionNotes]=useState(''),[bodyNotes,setBodyNotes]=useState(''),[when,setWhen]=useState(initialWhen),[volume,setVolume]=useState(''),[doses,setDoses]=useState<Record<string,string>>({}),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState('');
 const set=(key:string)=>(next:string[])=>setValues(current=>({...current,[key]:next}));
 const submit=async(event:React.FormEvent)=>{event.preventDefault();setBusy(true);setError('');setMessage('');try{const occurred_at=londonToISO(when);const selectedMedicines=medicines.filter(item=>(values.medicines??[]).includes(item.name)).map(item=>({...item,dose:doses[item.name]||undefined}));await saveDiaryRecord({kind,occurred_at,notes,mental:values.mental??[],emotions:values.emotions??[],body:values.body??[],digestion:values.digestion??[],activities:values.activities??[],interest:values.interest?.[0],emotion_notes:emotionNotes,body_notes:bodyNotes,quantity:values.quantity??[],consistency:values.consistency??[],routines:values.routines??[],medicines:selectedMedicines,volume_ml:volume?Number(volume):undefined});setValues({});setNotes('');setEmotionNotes('');setBodyNotes('');setVolume('');setDoses({});setMessage('Registro salvo no seu diário.');onSaved?.();}catch(reason){setError((reason as Error).message);}finally{setBusy(false);}};
 return <section className="panel form-page diary-register">{showTabs&&<div className="journal-tabs segmented large">{(Object.keys(diaryLabels) as Kind[]).map(key=>{const Icon=icons[key];return <button type="button" key={key} className={kind===key?'selected':''} onClick={()=>{setKind(key);setError('');setMessage('');}}><Icon size={17}/>{diaryLabels[key]}</button>;})}</div>}<form className="form-stack" onSubmit={submit}><label>Data e horário<input type="datetime-local" required value={when} onChange={event=>setWhen(event.target.value)}/></label>
 {kind==='checkin'&&<><Choices title="Mental · selecione quantos quiser" values={diaryOptions.mental} selected={values.mental??[]} onChange={set('mental')}/><Choices title="Emoções · selecione quantas quiser" values={diaryOptions.emotions} selected={values.emotions??[]} onChange={set('emotions')}/><label>Observações sobre as emoções<textarea value={emotionNotes} onChange={event=>setEmotionNotes(event.target.value)}/></label><Choices title="Corpo · selecione quantos quiser" values={diaryOptions.body} selected={values.body??[]} onChange={set('body')}/><label>Observações sobre o corpo<textarea value={bodyNotes} onChange={event=>setBodyNotes(event.target.value)}/></label><Choices title="Digestão · selecione quantos quiser" values={diaryOptions.digestion} selected={values.digestion??[]} onChange={set('digestion')}/></>}
 {kind==='activity'&&<><Choices title="Atividade e ambiente · selecione quantos quiser" values={diaryOptions.activities} selected={values.activities??[]} onChange={set('activities')}/><Choices title="Interesse na atividade" values={diaryOptions.interest} selected={values.interest??[]} onChange={set('interest')} single/></>}
 {kind==='bowel'&&<><Choices title="Quantidade · selecione as opções que descrevem o registro" values={diaryOptions.quantity} selected={values.quantity??[]} onChange={set('quantity')}/><Choices title="Consistência · selecione as opções aplicáveis" values={diaryOptions.consistency} selected={values.consistency??[]} onChange={set('consistency')}/></>}
 {kind==='water'&&<label>Quantidade de água (ml)<input type="number" min="1" max="10000" required value={volume} onChange={event=>setVolume(event.target.value)}/></label>}
 {kind==='vitamins'&&<Choices title="Rotina" values={diaryOptions.routines} selected={values.routines??[]} onChange={set('routines')}/>}
 {kind==='medication'&&<fieldset className="diary-choice"><legend>Remédio</legend><div className="medicine-list">{medicines.map(item=><div key={item.name}><label className="checkbox-label"><input type="checkbox" checked={(values.medicines??[]).includes(item.name)} onChange={()=>set('medicines')((values.medicines??[]).includes(item.name)?(values.medicines??[]).filter(value=>value!==item.name):[...(values.medicines??[]),item.name])}/><span><strong>{item.name}</strong><small>{item.composition}</small></span></label>{(values.medicines??[]).includes(item.name)&&<input aria-label={`Dose de ${item.name}`} placeholder="Dose/quantidade tomada (opcional)" value={doses[item.name]??''} onChange={event=>setDoses(current=>({...current,[item.name]:event.target.value}))}/>}</div>)}</div></fieldset>}
 <label>Observações<textarea value={notes} onChange={event=>setNotes(event.target.value)} maxLength={5000}/></label>{error&&<p className="error" role="alert">{error}</p>}{message&&<p className="success"><Check size={16}/>{message}</p>}<Button disabled={busy}>{busy?'Salvando…':'Salvar registro'}</Button></form></section>;
}
