'use client';
import { useEffect,useRef,useState } from 'react';
import { useForm } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';
import { z } from 'zod';
import { Plus,Trash2,Save } from 'lucide-react';
import { Button } from './ui/button';
import { groups,localInput,londonToISO,timezone,nutrients,foodSchema,type EventInput,type HealthEvent,type Food,type MealTemplate,type Nutrition } from '@/lib/domain';
import { saveDraft } from '@/app/actions';
export type Saver=(event:EventInput,id?:string)=>Promise<void>;
const stamp=(date?:string)=>{const now=localInput(new Date().toISOString());return date?date+now.slice(10):now;};
function base(timestamp:string,notes:string,subjective=false):Omit<EventInput,'type'|'data'>{return {timestamp:londonToISO(timestamp),timezone,source:'manual',measurement_type:subjective?'subjective':'measured',estimated:false,notes};}
function ErrorText({error}:{error:string}){return error?<p className="error" role="alert">{error}</p>:null;}
export function WaterForm({onSave,event,date}:{onSave:Saver;event?:HealthEvent;date?:string}){
 const schema=z.object({volume:z.coerce.number().positive('Informe um volume maior que zero').max(10000),timestamp:z.string().min(1),beverage:z.enum(['água','outro líquido']),notes:z.string()});
 const {register,handleSubmit,setValue,formState:{errors,isSubmitting}}=useForm<z.input<typeof schema>,unknown,z.output<typeof schema>>({resolver:zodResolver(schema),defaultValues:{volume:event?.data.kind==='water'?event.data.volume:650,timestamp:event?localInput(event.timestamp):stamp(date),beverage:event?.data.kind==='water'?event.data.beverage:'água',notes:event?.notes??''}});
 const [error,setError]=useState('');return <form onSubmit={handleSubmit(async v=>{try{setError('');await onSave({...base(v.timestamp,v.notes),type:'water',data:{kind:'water',volume:v.volume,beverage:v.beverage}},event?.id);}catch(e){setError((e as Error).message);}})} className="form-stack"><div className="choice-row">{[100,250,500,590,650].map(v=><Button type="button" variant="secondary" key={v} onClick={()=>setValue('volume',v)}>{v} ml</Button>)}</div><label>Volume (ml)<input type="number" step="1" {...register('volume')}/>{errors.volume&&<small className="error">{errors.volume.message}</small>}</label><label>Bebida<select {...register('beverage')}><option>água</option><option>outro líquido</option></select></label><p className="field-help">Somente água pura entra na meta de água.</p><label>Horário · Londres<input type="datetime-local" required {...register('timestamp')}/></label><label>Observação<input {...register('notes')}/></label><ErrorText error={error}/><Button disabled={isSubmitting} type="submit">{isSubmitting?'Salvando…':'Salvar registro'}</Button></form>;
}
const presets=['Bom dia','Check-in geral','Pré-tênis','Pós-tênis','Antes de dormir'];
const moods=['tranquilo','neutro','animado','motivado','satisfeito','bem-humorado','entediado','apático','desanimado','irritado','frustrado','ansioso','acelerado','inquieto','sonolento'];
const environments=['sentado','caminhando','luz externa','muito tempo de tela','pouco tempo de tela','ambiente silencioso','ambiente estimulante','ambiente monótono','ambiente social'];
export type Draft={timestamp:string;preset:string;scores:Record<string,number|null>;activity:string;moods:string[];environment:string[];notes:string};
export function CheckinForm({onSave,event,draft,demo,date}:{onSave:Saver;event?:HealthEvent;draft?:Draft|null;demo:boolean;date?:string}){
 const data=event?.data.kind==='checkin'?event.data:undefined;
 const [value,setValue]=useState<Draft>(()=>event?{timestamp:localInput(event.timestamp),preset:data?.preset??'Check-in geral',scores:data?.scores??{},activity:data?.activity??'',moods:data?.moods??[],environment:data?.environment??[],notes:event.notes}:draft??{timestamp:stamp(date),preset:'Check-in geral',scores:{},activity:'',moods:[],environment:[],notes:''});
 const [busy,setBusy]=useState(false),[error,setError]=useState(''),[status,setStatus]=useState(draft?'Rascunho recuperado':'Todos os campos são opcionais');
 const dirty=useRef(false),pending=useRef<Promise<void>>(Promise.resolve()),timer=useRef<ReturnType<typeof setTimeout>|null>(null);
 useEffect(()=>{if(!dirty.current||event||demo||busy)return;timer.current=setTimeout(()=>{setStatus('Salvando rascunho…');pending.current=pending.current.then(()=>saveDraft(value)).then(()=>setStatus('Rascunho salvo')).catch(()=>setStatus('Não foi possível salvar o rascunho'));},650);return()=>{if(timer.current)clearTimeout(timer.current);};},[value,event,demo,busy]);
 const update=(part:Partial<Draft>)=>{dirty.current=true;setValue(v=>({...v,...part}));};
 const toggle=(key:'moods'|'environment',tag:string)=>update({[key]:value[key].includes(tag)?value[key].filter(t=>t!==tag):[...value[key],tag]});
 return <form className="form-stack" onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');if(timer.current)clearTimeout(timer.current);try{await pending.current;await onSave({...base(value.timestamp,value.notes,true),type:'checkin',data:{kind:'checkin',preset:value.preset,scores:value.scores,activity:value.activity,moods:value.moods,environment:value.environment}},event?.id);}catch(err){setError((err as Error).message);}finally{setBusy(false);}}}>
 <label>Momento<select value={value.preset} onChange={e=>update({preset:e.target.value})}>{presets.map(p=><option key={p}>{p}</option>)}</select></label><label>Horário · Londres<input type="datetime-local" value={value.timestamp} required onChange={e=>update({timestamp:e.target.value})}/></label><p className="field-help" aria-live="polite">{demo?'Demonstração: rascunhos não são guardados.':status}. Deixe em branco o que não quiser informar.</p>
 {Object.entries(groups).map(([group,fields],index)=><details key={`${value.preset}-${group}`} open={index===0||((value.preset==='Pré-tênis'||value.preset==='Pós-tênis')&&group==='Corpo')} className="form-section"><summary>{group}<span>0–10</span></summary><div className="score-grid">{Object.entries(fields).map(([key,label])=><label key={key}>{label}<input type="number" min="0" max="10" step="1" placeholder="—" value={value.scores[key]??''} onChange={e=>update({scores:{...value.scores,[key]:e.target.value===''?null:Number(e.target.value)}})}/>{['stress','anxiety'].includes(key)&&<small>0 = nenhum · 10 = extremo</small>}</label>)}</div>{group==='Emoções'&&<div className="tags">{moods.map(t=><button type="button" aria-pressed={value.moods.includes(t)} className={value.moods.includes(t)?'selected':''} key={t} onClick={()=>toggle('moods',t)}>{t}</button>)}</div>}{group==='Contexto'&&<><label>Atividade atual<select value={value.activity} onChange={e=>update({activity:e.target.value})}><option value="">Não informado</option>{['trabalho focado','trabalho rotineiro','reunião','RapiDocs','leitura','vídeos','redes sociais','dirigindo','caminhando','descansando','sofá','tênis','pré-tênis','pós-tênis','comendo','outro'].map(v=><option key={v}>{v}</option>)}</select></label><div className="tags">{environments.map(t=><button type="button" aria-pressed={value.environment.includes(t)} className={value.environment.includes(t)?'selected':''} key={t} onClick={()=>toggle('environment',t)}>{t}</button>)}</div></>}</details>)}
 <label>Observação<textarea value={value.notes} maxLength={5000} onChange={e=>update({notes:e.target.value})}/></label><ErrorText error={error}/><Button type="submit" disabled={busy}>{busy?'Salvando…':'Salvar check-in'}</Button></form>;
}
const labels:Record<string,string>={calories:'Calorias (kcal)',protein:'Proteína (g)',carbs:'Carboidratos (g)',fat:'Gordura (g)',saturated_fat:'Gordura saturada (g)',fibre:'Fibra (g)',sugar:'Açúcar (g)',sodium:'Sódio (mg)'};
export function FoodForm({onSave}:{onSave:(food:z.infer<typeof foodSchema>)=>Promise<void>}){
 const {register,handleSubmit,formState:{isSubmitting,errors}}=useForm<z.input<typeof foodSchema>,unknown,z.output<typeof foodSchema>>({resolver:zodResolver(foodSchema),defaultValues:{name:'',brand:'',favorite:false,nutrition:Object.fromEntries(nutrients.map(k=>[k,null])) as Nutrition}});
 const [error,setError]=useState('');return <form className="form-stack" onSubmit={handleSubmit(async v=>{try{await onSave(v);}catch(e){setError((e as Error).message);}})}><label>Nome do alimento<input {...register('name')} required/></label><label>Marca<input {...register('brand')}/></label><p className="field-help">Valores por 100 g. Deixe em branco os nutrientes desconhecidos.</p><div className="score-grid">{nutrients.map(k=><label key={k}>{labels[k]}<input type="number" min="0" step="any" {...register(`nutrition.${k}`,{setValueAs:v=>v===''?null:Number(v)})}/></label>)}</div><label className="checkbox-label"><input type="checkbox" {...register('favorite')}/> Favorito</label>{Object.keys(errors).length>0&&<p className="error">Confira o nome e os valores nutricionais.</p>}<ErrorText error={error}/><Button disabled={isSubmitting}>Salvar alimento</Button></form>;
}
export function MealForm({foods,templates,onSave,event,onTemplate,date}:{date?:string;foods:Food[];templates:MealTemplate[];onSave:Saver;event?:HealthEvent;onTemplate:(name:string,items:MealTemplate['items'])=>Promise<void>}){
 const data=event?.data.kind==='meal'?event.data:undefined;
 const [timestamp,setTimestamp]=useState(event?localInput(event.timestamp):stamp(date)),[name,setName]=useState(data?.name??''),[mealType,setMealType]=useState(data?.meal_type??'Almoço'),[items,setItems]=useState<MealTemplate['items']>(data?.items??[]),[notes,setNotes]=useState(event?.notes??''),[hunger,setHunger]=useState<number|null>(data?.hunger??null),[satiety,setSatiety]=useState<number|null>(data?.satiety??null),[foodId,setFoodId]=useState(''),[grams,setGrams]=useState(100),[busy,setBusy]=useState(false),[error,setError]=useState(''),[estimated,setEstimated]=useState(event?.estimated??false),[savedTemplate,setSavedTemplate]=useState(false);
 return <form className="form-stack" onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');try{await onSave({...base(timestamp,notes),estimated,measurement_type:estimated?'estimated':'measured',type:'meal',data:{kind:'meal',name,meal_type:mealType,items,hunger,satiety}},event?.id);}catch(err){setError((err as Error).message);}finally{setBusy(false);}}}>
 {templates.length>0&&<label>Usar refeição salva<select defaultValue="" onChange={e=>{const t=templates.find(t=>t.id===e.target.value);if(t){setItems(t.items);setName(t.name);}}}><option value="">Escolher…</option>{templates.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></label>}
 <div className="score-grid"><label>Tipo<select value={mealType} onChange={e=>setMealType(e.target.value)}>{['Café da manhã','Almoço','Jantar','Lanche','Pré-tênis','Pós-tênis'].map(t=><option key={t}>{t}</option>)}</select></label><label>Horário · Londres<input type="datetime-local" value={timestamp} onChange={e=>setTimestamp(e.target.value)} required/></label></div><label>Nome (opcional)<input value={name} onChange={e=>setName(e.target.value)} placeholder="Ex.: iogurte com banana"/></label>
 <div className="meal-builder"><h3>Alimentos e quantidades</h3>{foods.length===0?<p>Cadastre alimentos na página Alimentação para calcular os nutrientes. Você também pode registrar somente o horário e uma observação.</p>:<><label>Alimento<select value={foodId} onChange={e=>setFoodId(e.target.value)}><option value="">Escolher alimento…</option>{foods.map(f=><option key={f.id} value={f.id}>{f.name}{f.brand?` · ${f.brand}`:''}</option>)}</select></label><div className="inline-fields"><label>Quantidade (g)<input type="number" min="0.1" max="10000" step="any" value={grams} onChange={e=>setGrams(Number(e.target.value))}/></label><Button type="button" variant="secondary" disabled={!foodId||grams<=0||grams>10000} onClick={()=>{const f=foods.find(f=>f.id===foodId)!;setItems([...items,{food_id:f.id,name:f.name,grams,nutrition:f.nutrition}]);setFoodId('');setSavedTemplate(false);}}><Plus size={18}/>Adicionar</Button></div></>}
 {items.map((item,i)=><div className="meal-item" key={i}><span>{item.name}<small>{item.grams} g</small></span><Button type="button" variant="ghost" aria-label={`Remover ${item.name}`} onClick={()=>setItems(items.filter((_,j)=>j!==i))}><Trash2 size={16}/></Button></div>)}</div>
 <div className="score-grid"><label>Fome antes · 0–10<input type="number" min="0" max="10" value={hunger??''} placeholder="—" onChange={e=>setHunger(e.target.value===''?null:Number(e.target.value))}/></label><label>Saciedade · 0–10<input type="number" min="0" max="10" value={satiety??''} placeholder="—" onChange={e=>setSatiety(e.target.value===''?null:Number(e.target.value))}/></label></div><label className="checkbox-label"><input type="checkbox" checked={estimated} onChange={e=>setEstimated(e.target.checked)}/> Valores estimados</label><label>Observação<textarea value={notes} onChange={e=>setNotes(e.target.value)}/></label>
 {items.length>0&&<Button variant="secondary" type="button" disabled={busy||!name.trim()||savedTemplate} onClick={async()=>{setBusy(true);try{await onTemplate(name,items);setSavedTemplate(true);}catch(err){setError((err as Error).message);}finally{setBusy(false);}}}><Save size={16}/>{savedTemplate?'Refeição salva na biblioteca':'Salvar combinação na biblioteca'}</Button>}{items.length>0&&!name.trim()&&<small>Dê um nome para salvar esta combinação.</small>}<ErrorText error={error}/><Button disabled={busy}>{busy?'Salvando…':'Registrar refeição'}</Button></form>;
}
