'use client';
import type { CSSProperties } from 'react';
import { WorkoutDetails } from './workout-details';
import { Dialog,DialogContent,DialogTitle,DialogDescription } from './ui/dialog';
import { isWorkout } from '@/lib/exercise-records';
import { useState } from 'react';
import { Activity, CalendarDays, Clock3, Flame, Footprints, Gauge, HeartPulse, Sparkles, Trash2, TrendingUp } from 'lucide-react';
import { clearExerciseHistory, deleteHealthRecord } from '@/app/actions';
import { dailyActivity } from '@/lib/daily-activity';
import { EChart, lineOption } from './echart';
type RecordRow={id:string;category:string;recorded_on:string;recorded_at:string|null;payload:Record<string,unknown>;source:string};
const normal=(value:string)=>value.normalize('NFD').replace(/[̀-ͯ]/g,'').toLowerCase().replace(/[^a-z0-9]/g,'');
const flatten=(value:unknown,prefix=''):Record<string,unknown>=>value&&typeof value==='object'&&!Array.isArray(value)?Object.entries(value as Record<string,unknown>).reduce((out,[name,item])=>({...out,...flatten(item,prefix?`${prefix} ${name}`:name)}),{} as Record<string,unknown>):prefix?{[prefix]:value}:{};
const value=(payload:Record<string,unknown>,names:string[])=>{const entries=Object.entries(flatten(payload));for(const name of names){const found=entries.find(([field])=>normal(field)===normal(name));if(found){const raw=found[1];if(typeof raw==='number')return raw;if(typeof raw==='string'&&raw.trim()&&!Number.isNaN(Number(raw)))return Number(raw);}}return null;};
const label=(payload:Record<string,unknown>)=>{const entries=Object.entries(flatten(payload));const found=['activity type','modalidade','tipo','workout type','workout name'].map(name=>entries.find(([field])=>normal(field)===normal(name))?.[1]).find(Boolean);return typeof found==='string'?found:'Exercício';};
const average=(values:(number|null)[])=>{const numbers=values.filter((item):item is number=>item!==null);return numbers.length?numbers.reduce((sum,item)=>sum+item,0)/numbers.length:null;};
const display=(number:number|null)=>number===null?'—':new Intl.NumberFormat('pt-BR',{maximumFractionDigits:1}).format(number);
const dataLike=(record:RecordRow)=>record.category==='daily_metrics'||['stand minutes','tempo em pe','stand time minutes','tempo em pé'].some(key=>value(record.payload,[key])!==null);
/* Chart presentation (HIG charts): hairline grid, no vertical lines, 12px secondary ticks, elevated tooltip. */
const dot=(color:string)=>({['--dot' as string]:color}) as CSSProperties;
const series={duracao:'var(--tint-fitness)',calorias:'var(--tint-move)',esforco:'var(--sys-purple)'} as const;
export function ExerciseDashboard({records,date}:{records:RecordRow[];date:string}){
 const [selected,setSelected]=useState<RecordRow|null>(null);
 const [busy,setBusy]=useState(false),[cleared,setCleared]=useState(false),[removed,setRemoved]=useState<string[]>([]);const removeHistory=async()=>{if(!window.confirm('Apagar todos os exercícios atuais? Os próximos registros enviados pelo ChatGPT ou pela página continuarão aparecendo.'))return;setBusy(true);try{await clearExerciseHistory();setCleared(true);}finally{setBusy(false);}};const removeSession=async(id:string)=>{if(!window.confirm('Excluir esta sessão?'))return;setBusy(true);try{await deleteHealthRecord(id);setRemoved(current=>[...current,id]);}finally{setBusy(false);}};
 const visible=records.filter(record=>!removed.includes(record.id)&&(!cleared||!['activity','workout'].includes(record.category))).sort((a,b)=>a.recorded_on.localeCompare(b.recorded_on)||(a.recorded_at??'').localeCompare(b.recorded_at??''));const daily=visible.filter(dataLike).at(-1);const sessions=visible.filter(isWorkout).map(record=>({record,type:label(record.payload),duration:value(record.payload,['duration minutes','duration min','duration','duracao minutos','exercise minutes','workout duration']),active:value(record.payload,['active calories','calorias ativas','kcal ativas','active kcal','active energy','energia ativa']),total:value(record.payload,['total calories','calorias totais','total energy','energia total']),steps:value(record.payload,['steps','passos']),distance:value(record.payload,['distance km','distancia km','distance','distancia']),heart:value(record.payload,['heart rate average','frequencia cardiaca media','fc media']),effort:value(record.payload,['watch effort'])}));
 const minutes=sessions.reduce((total,session)=>total+(session.duration??0),0),calories=sessions.reduce((total,session)=>total+(session.active??0),0),steps=sessions.reduce((total,session)=>total+(session.steps??0),0),effort=average(sessions.map(session=>session.effort));
 const chart=sessions.slice(-20).map(session=>({date:new Date(`${session.record.recorded_on}T12:00:00Z`).toLocaleDateString('pt-BR',{day:'2-digit',month:'short'}),duracao:session.duration,esforco:session.effort,calorias:session.active}));
 const summary=dailyActivity(visible,date);const daySummary=[['Passos',summary.steps,'passos',Footprints],['Distância',summary.distance,'km',Activity],['Horas em pé (anel)',summary.standHours,'h',Clock3],['Calorias ativas',summary.active,'kcal',Flame],['Calorias gastas totais',summary.total,'kcal',HeartPulse]] as const;
 const insight=!sessions.length?'Envie um treino pelo ChatGPT ou registre-o manualmente para começar seu histórico de carga.':effort!==null&&effort>=8?'A intensidade média registrada é alta. Compare a próxima sessão com sono, alimentação e sensação de recuperação antes de aumentar a carga.':`Você já registrou ${sessions.length} ${sessions.length===1?'sessão':'sessões'}. Com mais dados, será possível comparar duração, esforço e recuperação entre modalidades.`;
 return <div className="exercise-dashboard">
  <div className="tennis-hero"><div className="health-hero-lead"><span className="health-hero-icon" aria-hidden><Flame/></span><div><span className="eyebrow">CARGA & RECUPERAÇÃO</span><h1>Exercícios</h1><p>Treinos, calorias, zonas e sinais de esforço reunidos no mesmo lugar.</p></div></div><div className="exercise-actions"><button className="text-link danger-link" disabled={busy||cleared} onClick={removeHistory}>{cleared?'Histórico apagado':'Apagar exercícios antigos'}</button></div></div>
  <section className="panel daily-activity-summary"><div className="panel-heading"><div><h2><Gauge/>Resumo diário</h2><p className="field-help">Indicadores de {new Date(`${date}T12:00:00Z`).toLocaleDateString('pt-BR')}. Sem registro aparece como —.</p></div><button className="button secondary" onClick={()=>setSelected(visible.filter(r=>r.category==='daily_metrics'&&r.recorded_on===date).at(-1)??null)} disabled={!visible.some(r=>r.category==='daily_metrics'&&r.recorded_on===date)}>Metas e detalhes</button></div><div className="daily-activity-grid">{daySummary.map(([name,amount,unit,Icon])=>{const I=Icon;return <article key={name}><I size={18}/><small>{name}</small><strong>{display(amount)} <em>{amount===null?'':unit}</em></strong></article>;})}</div></section>
  <div className="tennis-stats exercise-stats"><article className="metric"><div className="metric-top"><span><Activity size={16}/>Sessões</span></div><div className="metric-value">{sessions.length}</div></article><article className="metric"><div className="metric-top"><span><Clock3 size={16}/>Tempo de treino</span></div><div className="metric-value">{Math.round(minutes)}<span>min</span></div></article><article className="metric"><div className="metric-top"><span><Flame size={16}/>Calorias de treino</span></div><div className="metric-value">{Math.round(calories)}<span>kcal</span></div></article><article className="metric"><div className="metric-top"><span><Footprints size={16}/>Passos em treinos</span></div><div className="metric-value">{steps?Math.round(steps).toLocaleString('pt-BR'):'—'}</div></article><article className="metric"><div className="metric-top"><span><HeartPulse size={16}/>Esforço Watch médio</span></div><div className="metric-value">{display(effort)}{effort===null?null:<span>/10</span>}</div></article></div>
  <section className="panel exercise-insight"><span className="health-insight-icon" aria-hidden><Sparkles/></span><div><span className="subtle">LEITURA DO DIÁRIO</span><h2>Como usar estes dados</h2><p>{insight}</p></div></section>
  <section className="panel"><div className="panel-heading"><h2><TrendingUp/>Carga e esforço</h2><span className="subtle">ÚLTIMAS 20 SESSÕES</span></div>{chart.length?<><div className="exercise-chart"><EChart height="100%" label="Duração, calorias ativas e esforço do Apple Watch nos últimos 20 treinos" option={t=>{const o:any=lineOption(t,{categories:chart.map(c=>c.date),min:0,series:[{name:'Duração (min)',values:chart.map(c=>c.duracao),color:series.duracao},{name:'Calorias ativas',values:chart.map(c=>c.calorias),color:series.calorias},{name:'Esforço Watch',values:chart.map(c=>c.esforco),color:series.esforco}]});o.yAxis=[o.yAxis,{...o.yAxis,min:0,max:10,interval:5,position:'right',splitLine:{show:false}}];o.series[2].yAxisIndex=1;return o;}}/></div><div className="health-chart-legend"><span style={dot(series.duracao)}><i/>Duração</span><span style={dot(series.calorias)}><i/>Calorias ativas</span><span style={dot(series.esforco)}><i/>Esforço Watch</span></div></>:<p className="field-help">Ainda não há sessões suficientes para o gráfico.</p>}</section>
  <section className="panel exercise-history"><div className="panel-heading"><h2><CalendarDays/>Sessões registradas</h2><span className="subtle">{sessions.length} REGISTROS</span></div>{sessions.length?sessions.slice().reverse().slice(0,60).map(session=><article key={session.record.id}><time>{new Intl.DateTimeFormat('pt-BR',{day:'2-digit',month:'short',year:'numeric'}).format(new Date(`${session.record.recorded_on}T12:00:00Z`))}</time><div><strong>{session.type}</strong><small>{[session.duration!==null&&`${display(session.duration)} min`,session.active!==null&&`${display(session.active)} kcal ativas`,session.distance!==null&&`${display(session.distance)} km`,session.heart!==null&&`FC ${display(session.heart)} bpm`,session.effort!==null&&`Esforço ${display(session.effort)}/10`].filter(Boolean).join(' · ')||'Dados do exercício registrados'}</small></div><div className="exercise-row-actions"><button className="button secondary" onClick={()=>setSelected(session.record)}>Detalhes</button><button className="record-delete" aria-label="Excluir sessão" disabled={busy} onClick={()=>removeSession(session.record.id)}><Trash2 size={18}/></button></div></article>):<p className="field-help">Envie a imagem do Apple Fitness pelo ChatGPT.</p>}</section>
  {selected&&<Dialog open onOpenChange={open=>{if(!open)setSelected(null);}}><DialogContent className="tennis-details-dialog"><DialogTitle>{selected.category==='daily_metrics'?'Resumo diário completo':'Detalhes do exercício'}</DialogTitle><DialogDescription>Dados originais do registro de {selected.recorded_on}. Tênis e Saúde utilizam esta mesma sessão.</DialogDescription><WorkoutDetails payload={selected.payload}/></DialogContent></Dialog>}
 </div>;
}
