'use client';
import {Wallet,TrendingUp,ArrowDownLeft,PiggyBank} from 'lucide-react';
import {ResponsiveContainer,BarChart,Bar,XAxis,YAxis,Tooltip,CartesianGrid,AreaChart,Area} from 'recharts';
import {grouped,moneyTotal,type Finance} from '@/lib/personal';
import {monthlyPortfolio,inPounds,type InvestmentSnapshot} from '@/lib/investments';
const money=(v:number)=>new Intl.NumberFormat('en-GB',{style:'currency',currency:'GBP'}).format(v);
const colors=['#619d68','#8e78b3','#e1aa64','#66a9ad','#adb64d','#7595cb'];
export function FinanceInsights({data,history}:{data:Finance;history:InvestmentSnapshot[]}){
 const expenses=moneyTotal(data.rows),income=data.incomeFelipe+data.incomeSara,balance=income-expenses;
 const monthly=monthlyPortfolio(inPounds(history));const latest=monthly.at(-1);const items=latest?.items??[];const total=items.reduce((sum,i)=>sum+i.value,0);
 const missing=(monthlyPortfolio(history).at(-1)?.items??[]).some(i=>i.currency!=='GBP'&&!i.fx);
 const categories=grouped(data.rows,'category').sort((a,b)=>b.value-a.value);
 const chart=monthly.map(point=>({month:point.month,value:point.items.reduce((sum,i)=>sum+i.value,0)}));
 const payments=grouped(data.rows,'payment');
 const due=data.rows.filter(r=>r.day!==null).sort((a,b)=>a.day!-b.day!);
 return <div className="finance-insights">
 <div className="finance-kpis">{[{label:'Receita mensal prevista',value:income,icon:ArrowDownLeft,tone:'green'},{label:'Despesas planejadas',value:expenses,icon:Wallet,tone:'peach'},{label:'Saldo mensal previsto',value:balance,icon:PiggyBank,tone:'violet'},{label:missing?'Investimentos · subtotal':'Total investido',value:total,icon:TrendingUp,tone:'lime'}].map(({label,value,icon:Icon,tone})=><article className={`finance-kpi ${tone}`} key={label}><Icon size={21}/><small>{label}</small><strong>{money(value)}</strong><span>{label.includes('invest')||tone==='lime'?`${items.length} posições com valores em GBP`:'Com base na tabela de gastos'}</span></article>)}</div>
 <div className="finance-visual-grid"><section className="panel finance-budget-chart"><div className="panel-heading"><div><span className="eyebrow">SEU PLANEJAMENTO</span><h2>O mês em perspectiva</h2></div></div><div className="finance-chart"><ResponsiveContainer width="100%" height="100%"><BarChart data={[{name:'Orçamento mensal',Receita:income,Despesas:expenses,Saldo:balance}]}><CartesianGrid vertical={false} stroke="#e8edef"/><XAxis dataKey="name" tickLine={false} axisLine={false}/><YAxis tickFormatter={v=>`£${v>=1000?(v/1000).toFixed(1)+'k':v}`} tickLine={false} axisLine={false} width={60}/><Tooltip formatter={v=>money(Number(v))}/><Bar dataKey="Receita" fill="#6a9e73" radius={[8,8,0,0]}/><Bar dataKey="Despesas" fill="#e2a469" radius={[8,8,0,0]}/><Bar dataKey="Saldo" fill="#9a83ba" radius={[8,8,0,0]}/></BarChart></ResponsiveContainer></div><div className="finance-chart-legend"><span style={{color:'#51865a'}}>● Receita</span><span style={{color:'#b77b3f'}}>● Despesas</span><span style={{color:'#80639f'}}>● Saldo</span></div><p className="field-help">Valores previstos no orçamento, não transações bancárias realizadas.</p></section>
 <section className="panel finance-allocation"><span className="eyebrow">DISTRIBUIÇÃO</span><h2>Para onde vai o orçamento</h2><div className="finance-stack-bar" aria-hidden="true">{categories.map((c,i)=><span key={c.name} style={{width:`${expenses?c.value/expenses*100:0}%`,background:colors[i%colors.length]}}/>)}</div><div className="finance-category-list">{categories.map((c,i)=><div key={c.name}><span><i style={{background:colors[i%colors.length]}}/>{c.name}</span><strong>{money(c.value)}<small>{expenses?(c.value/expenses*100).toFixed(1):0}%</small></strong></div>)}</div></section>
 <section className="panel finance-evolution"><span className="eyebrow">PATRIMÔNIO</span><h2>Evolução dos investimentos</h2>{chart.length>1?<div className="finance-chart"><ResponsiveContainer width="100%" height="100%"><AreaChart data={chart}><CartesianGrid vertical={false} stroke="#e8edef"/><XAxis dataKey="month" tickLine={false} axisLine={false}/><YAxis width={65} tickFormatter={v=>`£${(v/1000).toFixed(1)}k`} axisLine={false} tickLine={false}/><Tooltip formatter={v=>money(Number(v))}/><Area dataKey="value" name="Valor da carteira" stroke="#6d9160" fill="#e2edce" strokeWidth={3}/></AreaChart></ResponsiveContainer></div>:<div className="finance-baseline"><TrendingUp size={34}/><strong>{history.length?money(total):'Seu histórico começa aqui'}</strong><p>{history.length?'Primeiro mês registrado. Envie a próxima atualização para comparar a evolução.':'Adicione seus investimentos para acompanhar a evolução mensal.'}</p></div>}<p className="field-help">{missing?'Há cotações pendentes: o gráfico mostra apenas valores disponíveis. ':' '}Variação da carteira inclui aportes, retiradas e câmbio; não equivale ao rendimento.</p></section>
 <section className="panel finance-payment-plan"><span className="eyebrow">ORGANIZE AS CONTAS</span><h2>Por forma de pagamento</h2><div className="finance-payment-list">{payments.map((p,i)=><div key={p.name}><span>{p.name}</span><strong>{money(p.value)}</strong><div><i style={{width:`${expenses?p.value/expenses*100:0}%`,background:colors[i%colors.length]}}/></div></div>)}</div><h3>Calendário de cobranças</h3><div className="finance-due-list">{due.map(row=><div key={row.id}><span className="finance-day">{String(row.day).padStart(2,'0')}</span><span>{row.item}<small>{row.payment}</small></span><b>{money(row.value)}</b></div>)}</div><small>Dia de cobrança informado no orçamento mensal.</small></section></div>
 </div>;
}
