'use client';
import {Wallet,TrendingUp,ArrowDownLeft,PiggyBank} from 'lucide-react';
import {ResponsiveContainer,BarChart,Bar,XAxis,YAxis,Tooltip,CartesianGrid,AreaChart,Area} from 'recharts';
import {grouped,moneyTotal,type Finance} from '@/lib/personal';
import {monthlyPortfolio,inPounds,type InvestmentSnapshot} from '@/lib/investments';
const money=(v:number)=>new Intl.NumberFormat('en-GB',{style:'currency',currency:'GBP'}).format(v);
// Categorical palette built from the system colours so it flips with Dark Mode.
const colors=['var(--sys-mint)','var(--sys-purple)','var(--sys-orange)','var(--sys-teal)','var(--sys-green)','var(--sys-blue)','var(--sys-pink)','var(--sys-indigo)','var(--sys-yellow)','var(--sys-brown)'];
const axisTick={fontSize:12,fill:'var(--label-2)'};
const tooltipStyle={background:'var(--bg-elevated)',border:'1px solid var(--separator-soft)',borderRadius:12,boxShadow:'var(--shadow-2)',padding:'8px 12px',fontSize:13,lineHeight:'18px'};
const tooltipLabel={color:'var(--label)',fontWeight:600,marginBottom:2};
const tooltipItem={color:'var(--label-2)',padding:0};
const monthNames=['jan','fev','mar','abr','mai','jun','jul','ago','set','out','nov','dez'];
const shortMonth=(month:string)=>{const [year,index]=String(month).split('-');return `${monthNames[Number(index)-1]??index} ${year.slice(2)}`;};
export function FinanceInsights({data,history}:{data:Finance;history:InvestmentSnapshot[]}){
 const expenses=moneyTotal(data.rows),income=data.incomeFelipe+data.incomeSara,balance=income-expenses;
 const monthly=monthlyPortfolio(inPounds(history));const latest=monthly.at(-1);const items=latest?.items??[];const total=items.reduce((sum,i)=>sum+i.value,0);
 const missing=(monthlyPortfolio(history).at(-1)?.items??[]).some(i=>i.currency!=='GBP'&&!i.fx);
 const categories=grouped(data.rows,'category').sort((a,b)=>b.value-a.value);
 const chart=monthly.map(point=>({month:point.month,value:point.items.reduce((sum,i)=>sum+i.value,0)}));
 const payments=grouped(data.rows,'payment');
 const due=data.rows.filter(r=>r.day!==null).sort((a,b)=>a.day!-b.day!);
 const kpis=[{label:'Receita mensal prevista',value:income,icon:ArrowDownLeft,tone:'green'},{label:'Despesas planejadas',value:expenses,icon:Wallet,tone:'peach'},{label:'Saldo mensal previsto',value:balance,icon:PiggyBank,tone:'violet'},{label:missing?'Investimentos · subtotal':'Total investido',value:total,icon:TrendingUp,tone:'lime'}];
 return <div className="finance-insights">
 <div className="finance-kpis">{kpis.map(({label,value,icon:Icon,tone})=><article className={`metric finance-kpi ${tone}${value<0?' negative':''}`} key={label}><div className="metric-top"><span><Icon size={16} strokeWidth={1.9} aria-hidden/>{label}</span></div><div className="metric-value">{money(value)}</div><p className="metric-meta">{label.includes('invest')||tone==='lime'?`${items.length} posições com valores em GBP`:'Com base na tabela de gastos'}</p></article>)}</div>
 <div className="finance-visual-grid">
  <section className="panel finance-budget-chart"><div className="panel-heading"><div><span className="eyebrow">SEU PLANEJAMENTO</span><h2>O mês em perspectiva</h2></div></div><div className="finance-chart"><ResponsiveContainer width="100%" height="100%"><BarChart data={[{name:'Orçamento mensal',Receita:income,Despesas:expenses,Saldo:balance}]} barGap={10} barCategoryGap="28%" margin={{top:8,right:8,left:0,bottom:0}}><CartesianGrid vertical={false} stroke="var(--separator-soft)"/><XAxis dataKey="name" tickLine={false} axisLine={false} tick={axisTick}/><YAxis tickFormatter={v=>`£${v>=1000?(v/1000).toFixed(1)+'k':v}`} tickLine={false} axisLine={false} width={56} tick={axisTick}/><Tooltip formatter={v=>money(Number(v))} cursor={{fill:'var(--fill-4)'}} contentStyle={tooltipStyle} labelStyle={tooltipLabel} itemStyle={tooltipItem}/><Bar dataKey="Receita" fill="var(--sys-green)" radius={[6,6,0,0]} maxBarSize={64}/><Bar dataKey="Despesas" fill="var(--sys-orange)" radius={[6,6,0,0]} maxBarSize={64}/><Bar dataKey="Saldo" fill="var(--tint-finance)" radius={[6,6,0,0]} maxBarSize={64}/></BarChart></ResponsiveContainer></div><div className="finance-chart-legend"><span><i style={{background:'var(--sys-green)'}}/>Receita</span><span><i style={{background:'var(--sys-orange)'}}/>Despesas</span><span><i style={{background:'var(--tint-finance)'}}/>Saldo</span></div><p className="field-help">Valores previstos no orçamento, não transações bancárias realizadas.</p></section>
  <section className="panel finance-allocation"><span className="eyebrow">DISTRIBUIÇÃO</span><h2>Para onde vai o orçamento</h2><div className="finance-stack-bar" aria-hidden="true">{categories.map((c,i)=><span key={c.name} style={{width:`${expenses?c.value/expenses*100:0}%`,background:colors[i%colors.length]}}/>)}</div><div className="finance-category-list">{categories.map((c,i)=><div key={c.name}><span><i style={{background:colors[i%colors.length]}}/>{c.name}</span><strong>{money(c.value)}<small>{expenses?(c.value/expenses*100).toFixed(1):0}%</small></strong></div>)}</div></section>
  <section className="panel finance-evolution"><span className="eyebrow">PATRIMÔNIO</span><h2>Evolução dos investimentos</h2>{chart.length>1?<div className="finance-chart"><ResponsiveContainer width="100%" height="100%"><AreaChart data={chart} margin={{top:8,right:8,left:0,bottom:0}}><defs><linearGradient id="finance-evolution-fill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="var(--tint-invest)" stopOpacity={.28}/><stop offset="100%" stopColor="var(--tint-invest)" stopOpacity={0}/></linearGradient></defs><CartesianGrid vertical={false} stroke="var(--separator-soft)"/><XAxis dataKey="month" tickLine={false} axisLine={false} tick={axisTick} tickFormatter={shortMonth}/><YAxis width={56} tickFormatter={v=>`£${(v/1000).toFixed(1)}k`} axisLine={false} tickLine={false} tick={axisTick}/><Tooltip formatter={v=>money(Number(v))} labelFormatter={v=>shortMonth(String(v))} cursor={{stroke:'var(--separator)'}} contentStyle={tooltipStyle} labelStyle={tooltipLabel} itemStyle={tooltipItem}/><Area dataKey="value" name="Valor da carteira" type="monotone" stroke="var(--tint-invest)" fill="url(#finance-evolution-fill)" strokeWidth={2.5} dot={false} activeDot={{r:5,fill:'var(--tint-invest)',stroke:'var(--bg-2)',strokeWidth:2}}/></AreaChart></ResponsiveContainer></div>:<div className="finance-baseline"><TrendingUp size={34} aria-hidden/><strong>{history.length?money(total):'Seu histórico começa aqui'}</strong><p>{history.length?'Primeiro mês registrado. Envie a próxima atualização para comparar a evolução.':'Adicione seus investimentos para acompanhar a evolução mensal.'}</p></div>}<p className="field-help">{missing?'Há cotações pendentes: o gráfico mostra apenas valores disponíveis. ':' '}Variação da carteira inclui aportes, retiradas e câmbio; não equivale ao rendimento.</p></section>
  <section className="panel finance-payment-plan"><span className="eyebrow">ORGANIZE AS CONTAS</span><h2>Por forma de pagamento</h2><div className="finance-payment-list">{payments.map((p,i)=><div key={p.name}><span>{p.name}</span><strong>{money(p.value)}</strong><div><i style={{width:`${expenses?p.value/expenses*100:0}%`,background:colors[i%colors.length]}}/></div></div>)}</div><h3>Calendário de cobranças</h3><div className="finance-due-list">{due.map(row=><div key={row.id}><span className="finance-day">{String(row.day).padStart(2,'0')}</span><span>{row.item}<small>{row.payment}</small></span><b>{money(row.value)}</b></div>)}</div><small>Dia de cobrança informado no orçamento mensal.</small></section>
 </div>
 </div>;
}
