import { dailyActivity } from '@/lib/daily-activity';
import { sleepQuality } from '@/lib/sleep-quality';
import { dailyMealQualityAverage } from '@/lib/meal-quality';
import { Flame } from 'lucide-react';
type Event={local_date:string;type:string;data:Record<string,unknown>};type RecordRow={category:string;recorded_on:string;recorded_at:string|null;payload:Record<string,unknown>};
type Period='Dia'|'Semana'|'Mês'|'Ano';const periods:Period[]=['Dia','Semana','Mês','Ano'];
const flatten=(value:unknown,prefix=''):Record<string,unknown>=>value&&typeof value==='object'&&!Array.isArray(value)?Object.entries(value as Record<string,unknown>).reduce((out,[name,item])=>({...out,...flatten(item,prefix?`${prefix} ${name}`:name)}),{} as Record<string,unknown>):prefix?{[prefix]:value}:{};
const format=(item:number|null,maximum=1)=>item===null?'—':new Intl.NumberFormat('pt-BR',{maximumFractionDigits:maximum}).format(item);
const start=(date:string,period:Period)=>{const value=new Date(`${date}T12:00:00Z`);if(period==='Dia')return date;if(period==='Semana'){value.setUTCDate(value.getUTCDate()-((value.getUTCDay()+6)%7));}else if(period==='Mês')value.setUTCDate(1);else value.setUTCMonth(0,1);return value.toISOString().slice(0,10);};
const within=(date:string,selected:string,period:Period)=>date>=start(selected,period)&&date<=selected;
const average=(values:(number|null)[])=>{const filled=values.filter((item):item is number=>item!==null);return filled.length?filled.reduce((total,item)=>total+item,0)/filled.length:null;};
const mealCalories=(event:Event)=>event.type!=='meal'?0:(((event.data.items as unknown[]|undefined)??[]).reduce<number>((sum,item)=>{const row=item as {grams?:number;nutrition?:{calories?:number}};return sum+(row.grams??0)*(row.nutrition?.calories??0)/100;},0));
const sleepGrade=(record:RecordRow)=>sleepQuality(record.payload).score;
export function GeneralHealthDashboard({events,records,date}:{events:Event[];records:RecordRow[];date:string}){const byPeriod=(period:Period)=>events.filter(event=>within(event.local_date,date,period)),recordsBy=(period:Period)=>records.filter(record=>within(record.recorded_on,date,period));const consumed=(period:Period)=>{const grouped=new Map<string,number>();for(const event of byPeriod(period).filter(event=>event.type==='meal'))grouped.set(event.local_date,(grouped.get(event.local_date)??0)+mealCalories(event));return average([...grouped.values()]);};const burned=(period:Period)=>{const grouped=new Map<string,RecordRow[]>();for(const record of recordsBy(period)){grouped.set(record.recorded_on,[...(grouped.get(record.recorded_on)??[]),record]);}const days=[...grouped.values()].map(day=>{return dailyActivity(day,day[0].recorded_on).total;});return average(days);};const food=(period:Period)=>dailyMealQualityAverage(byPeriod(period));const sleep=(period:Period)=>average(recordsBy(period).filter(record=>record.category==='sleep').map(sleepGrade));const rows: [string,(period:Period)=>number|null,string][]=[['Calorias consumidas',(period:Period)=>consumed(period),'kcal'],['Calorias gastas',(period:Period)=>burned(period),'kcal'],['Qualidade do sono',(period:Period)=>sleep(period),'/10'],['Qualidade da alimentação',(period:Period)=>food(period),'/10']];return <div className="general-health"><div className="panel-heading general-heading"><div><span className="eyebrow">VISÃO INTEGRADA</span><h2>Saúde geral</h2><p className="field-help">Dia, semana, mês e ano para acompanhar o que muda de verdade.</p></div></div><section className="panel general-table"><div className="panel-heading"><h2><Flame/>Energia, sono e alimentação</h2><span className="subtle">DIA · MÉDIA DIÁRIA POR PERÍODO</span></div><div className="general-head"><span>Indicador</span>{periods.map(period=><span key={period}>{period}</span>)}</div>{rows.map(([title,fn,unit])=><div className="general-row" key={title}><strong>{title}<small>{unit}</small></strong>{periods.map(period=>{const result=fn(period);return <span key={period} data-period={period}>{format(result)}<em>{result===null?'':` ${unit}`}</em></span>})}</div>)}</section></div>}
