'use client';
import { useState } from 'react';
import { Save } from 'lucide-react';
import { saveHealthProfile } from '@/app/actions';
import { Button } from './ui/button';
type Measurement={recorded_on:string;payload:Record<string,unknown>;source:string}|null;
const baseline={
 'Identificação de saúde':'Tipo sanguíneo B+. Altura 1,80 m. Óculos: astigmatismo leve (R −0,50; L −0,25).',
 'Condição e histórico':'Prolapso leve da válvula mitral, conforme relato médico, sem limitações conhecidas. Histórico de entorses no tornozelo no futebol, com recuperação funcional completa.',
 'Histórico familiar relevante':'Avó materna: hipertensão, AVC e tireoide. Avó paterna: diabetes e evento cardíaco. Avô paterno: cirrose de causa não esclarecida.',
 'Capacidade e metabolismo':'VO₂ max 61,2. Resting energy médio: 1.824 kcal/dia. Referência histórica de atividade: 86 min/dia, 11.755 passos/dia e 8,3 km/dia. FC registrada: 41–197 bpm; sono: 42–109 bpm.',
 'Sono e rotina':'Em geral acorda às 7h30 e dorme por volta de 23h. Referência histórica: 9h13 de sono por noite; Core 7h46, REM 35 min e profundo 31 min.',
 'Sensibilidades digestivas':'Algumas massas com glúten podem causar gases e estufamento. Feijão, grão-de-bico e lentilha podem causar gases e diarreia. Churrasco e excesso de carne vermelha podem causar gases. Pilsen/Lager acima de 2 pints pode causar gases e diarreia. Alguns queijos podem desencadear enxaqueca com aura.',
 'Rotina e atividade':'Caminhadas com Caju pela manhã e fim da tarde; trabalho 9h–17h; tênis frequente; alongamento e faixas de resistência; sauna, jacuzzi e, quando necessário, piscina de gelo no clube.',
 'Suplementos':'Dia: vitamina C, vitamina D, biotina, ômega-3 e Lion’s Mane. Noite: magnésio composto, glucosamina com condroitina, BCAA e colágeno. A rotina registrada no diário pode ser ajustada conforme o uso real.',
 'Objetivo':'Manter saúde e atividade ao longo da vida, com mente clara e corpo capaz de caminhar, viajar e jogar tênis.'
};
const cards=[['Tipo sanguíneo','B+'],['VO₂ max','61,2'],['Resting energy','1.824 kcal'],['Altura','1,80 m']];
const sections:[string,string[]][]=[['Corpo e capacidade',['VO₂ max: 61,2','Resting energy médio: 1.824 kcal/dia','Passos médios históricos: 11.755/dia','Distância média histórica: 8,3 km/dia','Exercício médio histórico: 86 min/dia']],['Coração e recuperação',['Prolapso leve da válvula mitral, segundo avaliação médica','Frequência cardíaca registrada: 41–197 bpm','Faixa em sono: 42–109 bpm','Respiração média: 19,5/min']],['Sono e rotina',['Acorda habitualmente às 7h30','Dormir por volta de 23h','Média histórica: 9h13/noite','Caminhadas diárias com Caju','Tênis e mobilidade como base de atividade']],['Histórico familiar relevante',['Avó materna: hipertensão, AVC e tireoide','Avó paterna: diabetes e evento cardíaco','Avô paterno: cirrose de causa não esclarecida']],['Digestão e sensibilidades',['Massas com glúten podem causar desconforto','Leguminosas podem causar gases/diarreia','Carne vermelha/churrasco pode causar gases','Alguns queijos podem desencadear enxaqueca com aura','Pilsen/Lager em excesso pode causar gases/diarreia']],['Visão e referências',['Astigmatismo leve: R −0,50; L −0,25','Tipo sanguíneo B+','Sem outras condições médicas relatadas']],['Objetivo de longo prazo',['Mente clara e corpo saudável','Capacidade para caminhar e viajar','Longevidade ativa com tênis e rotina sustentável']]];
const label=(key:string)=>key.replace(/_/g,' ');
const bodyValue=(key:string,item:unknown)=>typeof item==='string'&&/^\d{4}-\d{2}-\d{2}/.test(item)?new Date(item.slice(0,10)+'T12:00:00Z').toLocaleDateString('pt-BR'):typeof item==='number'?new Intl.NumberFormat('pt-BR',{maximumFractionDigits:2}).format(item):String(item);
export function HealthProfile({initial,measurements}:{initial?:Record<string,unknown>;measurements:Measurement}){const [value,setValue]=useState<Record<string,unknown>>({...baseline,...Object.fromEntries(Object.entries(initial??{}).filter(([key])=>!key.startsWith('personal_')))}),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState('');const body=measurements?Object.entries(measurements.payload).filter(([,item])=>item!==null&&item!==''&&typeof item!=='object'):[];return <div className="profile-layout"><section className="profile-summary">{cards.map(([label,item])=><article key={label}><small>{label}</small><strong>{item}</strong></article>)}</section>{measurements&&<section className="panel body-measurements"><div className="panel-heading"><div><h2>Última bioimpedância e medidas</h2><p className="field-help">Registro de {new Intl.DateTimeFormat('pt-BR',{dateStyle:'medium'}).format(new Date(`${measurements.recorded_on}T12:00:00Z`))} · {measurements.source}</p></div></div><div>{body.map(([key,item])=><article key={key}><small>{label(key)}</small><strong>{bodyValue(key,item)}</strong></article>)}</div></section>}<section className="profile-sections">{sections.map(([title,items])=><article key={title}><h2>{title}</h2><ul>{items.map(item=><li key={item}>{item}</li>)}</ul></article>)}</section><section className="panel form-page"><h2>Detalhes para contextualizar o diário</h2><p className="field-help">Revise e atualize estes dados quando necessário. Eles servem de contexto e não substituem acompanhamento clínico.</p><form className="form-stack" onSubmit={async event=>{event.preventDefault();setBusy(true);setError('');try{await saveHealthProfile(value);setMessage('Perfil de saúde salvo.');}catch(err){setError((err as Error).message);}finally{setBusy(false);}}}>{Object.entries(value).map(([key,text])=><label key={key}>{key}<textarea value={String(text??'')} maxLength={5000} onChange={e=>setValue(current=>({...current,[key]:e.target.value}))}/></label>)}<label>Outra informação de saúde relevante<textarea value={String(value['Outras informações']??'')} maxLength={5000} onChange={e=>setValue(current=>({...current,'Outras informações':e.target.value}))}/></label>{error&&<p className="error">{error}</p>}{message&&<p className="success">{message}</p>}<Button disabled={busy}><Save size={16}/>{busy?'Salvando…':'Salvar perfil'}</Button></form></section></div>}
