'use client';
import { useState } from 'react';
import { Save } from 'lucide-react';
import { saveHealthProfile } from '@/app/actions';
import { Button } from './ui/button';
const baseline={
 'Identificação de saúde':'Tipo sanguíneo B+. Altura 1,80 m. Referência corporal: 78 kg, 14,9% de gordura, IMC 24,2, BMR 1.949 kcal. Óculos: astigmatismo leve (R −0,50; L −0,25).',
 'Condição e histórico':'Prolapso leve da válvula mitral, conforme relato médico, sem limitações conhecidas. Histórico de entorses no tornozelo no futebol, com recuperação funcional completa.',
 'Capacidade e referências':'VO₂ max 52 (referência anterior 45). Média diária histórica: 86 min de exercício, 11.755 passos e 8,3 km. FC registrada: 41–197 bpm; sono: 42–109 bpm. Respiração média: 19,5/min.',
 'Sono e rotina':'Em geral acorda às 7h30 e dorme por volta de 23h. Referência histórica: 9h13 de sono por noite; Core 7h46, REM 35 min e profundo 31 min.',
 'Sensibilidades digestivas':'Algumas massas com glúten podem causar gases e estufamento. Feijão, grão-de-bico e lentilha podem causar gases e diarreia. Churrasco e excesso de carne vermelha podem causar gases. Pilsen/Lager acima de 2 pints pode causar gases e diarreia. Alguns queijos podem desencadear enxaqueca com aura.',
 'Rotina e atividade':'Caminhadas com Caju pela manhã e fim da tarde; trabalho 9h–17h; tênis frequente; alongamento e faixas de resistência; sauna, jacuzzi e, quando necessário, piscina de gelo no clube.',
 'Suplementos':'Dia: vitamina C, vitamina D, biotina, ômega-3 e Lion’s Mane. Noite: magnésio composto, glucosamina com condroitina, BCAA e colágeno. A rotina registrada no diário pode ser ajustada conforme o uso real.',
 'Objetivo':'Manter saúde e atividade ao longo da vida, com mente clara e corpo capaz de caminhar, viajar e jogar tênis.'
};
const cards=[['Tipo sanguíneo','B+'],['VO₂ max','52'],['Altura','1,80 m'],['Referência de gordura','14,9%']];
const sections: [string,string[]][]=[['Corpo e capacidade',['Peso de referência: 78 kg','Massa muscular esquelética: 63,9 kg','Água corporal: 46,3 L','Metabolismo basal: 1.949 kcal','VO₂ max: 52','Passos médios: 11.755/dia']],['Coração e recuperação',['Prolapso leve da válvula mitral, segundo avaliação médica','Frequência cardíaca registrada: 41–197 bpm','Faixa em sono: 42–109 bpm','Respiração média: 19,5/min']],['Sono e rotina',['Acorda habitualmente às 7h30','Dormir por volta de 23h','Média histórica: 9h13/noite','Caminhadas diárias com Caju','Tênis e mobilidade como base de atividade']],['Digestão e sensibilidades',['Massas com glúten podem causar desconforto','Leguminosas podem causar gases/diarreia','Carne vermelha/churrasco pode causar gases','Alguns queijos podem desencadear enxaqueca com aura','Pilsen/Lager em excesso pode causar gases/diarreia']],['Visão e referências',['Astigmatismo leve: R −0,50; L −0,25','Tipo sanguíneo B+','Sem outras condições médicas relatadas']],['Objetivo de longo prazo',['Mente clara e corpo saudável','Capacidade para caminhar e viajar','Longevidade ativa com tênis e rotina sustentável']]];
export function HealthProfile({initial}:{initial?:Record<string,unknown>}){const [value,setValue]=useState<Record<string,unknown>>({...baseline,...initial}),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState('');return <div className="profile-layout"><section className="profile-summary">{cards.map(([label,item])=><article key={label}><small>{label}</small><strong>{item}</strong></article>)}</section><section className="profile-sections">{sections.map(([title,items])=><article key={title}><h2>{title}</h2><ul>{items.map(item=><li key={item}>{item}</li>)}</ul></article>)}</section><section className="panel form-page"><h2>Detalhes para contextualizar o diário</h2><p className="field-help">Revise e atualize estes dados quando necessário. Eles servem de contexto e não substituem acompanhamento clínico.</p><form className="form-stack" onSubmit={async event=>{event.preventDefault();setBusy(true);setError('');try{await saveHealthProfile(value);setMessage('Perfil de saúde salvo.');}catch(err){setError((err as Error).message);}finally{setBusy(false);}}}>{Object.entries(value).map(([key,text])=><label key={key}>{key}<textarea value={String(text??'')} maxLength={5000} onChange={e=>setValue(current=>({...current,[key]:e.target.value}))}/></label>)}<label>Outra informação de saúde relevante<textarea value={String(value['Outras informações']??'')} maxLength={5000} onChange={e=>setValue(current=>({...current,'Outras informações':e.target.value}))}/></label>{error&&<p className="error">{error}</p>}{message&&<p className="success">{message}</p>}<Button disabled={busy}><Save size={16}/>{busy?'Salvando…':'Salvar perfil'}</Button></form></section></div>}
