'use client';
import { useEffect,useState } from 'react';
import Link from 'next/link';
import { useRouter } from 'next/navigation';
import { HeartPulse,LayoutDashboard,Droplets,Utensils,Activity,Clock3,Target,Plus,ArrowUpRight,ChevronLeft,ChevronRight,LogOut,Search,Pencil,Copy,Trash2,Flame,Brain,Footprints,Moon,Check,Menu,X,Trophy } from 'lucide-react';
import { LineChart,Line,XAxis,YAxis,Tooltip,ResponsiveContainer,CartesianGrid } from 'recharts';
import { Button } from './ui/button';
import { Dialog,DialogContent,DialogTitle,DialogDescription } from './ui/dialog';
import { WaterForm,CheckinForm,FoodForm,MealForm,type Draft } from './event-forms';
import { totals,format,metricInfo,nutrientInfo,micronutrients,targetProgress,targetLabel,localDate,localTime,eventTitle,groups,dayTypes,type Targets,type HealthEvent,type Food,type TargetTemplate,type MealTemplate,type Day,type EventInput,type Metric,targetSchema,eventSchema } from '@/lib/domain';
import { saveEvent,deleteEvent,saveFood,saveMealTemplate,saveTargets,logout } from '@/app/actions';
type HealthRecord={id:string;category:string;recorded_on:string;recorded_at:string|null;payload:Record<string,unknown>;source:string};
type Initial={events:HealthEvent[];periodEvents:HealthEvent[];foods:Food[];templates:TargetTemplate[];day:Day;mealTemplates:MealTemplate[];draft:Draft|null;healthRecords:HealthRecord[];periodHealthRecords:HealthRecord[]};
const nav=[['hoje','Hoje',LayoutDashboard],['agua','Água',Droplets],['check-in','Check-in',Activity],['alimentacao','Alimentação',Utensils],['tenis','Tênis',Trophy],['registros','Registros',Activity],['perfil','Perfil',HeartPulse],['timeline','Timeline',Clock3],['metas','Metas',Target]] as const;
const metricIcons={water:Droplets,calories:Flame,protein:Utensils,carbs:Utensils,fat:Utensils,saturated_fat:Utensils,fibre:Utensils,steps:Footprints,exercise:Activity,sleep:Moon};
export default function HealthApp({initial,demo=false,view:initialView}:{initial:Initial;demo?:boolean;view:string}){
 const router=useRouter();const [events,setEvents]=useState(initial.events),[periodEvents,setPeriodEvents]=useState(initial.periodEvents),[foods,setFoods]=useState(initial.foods),[templates,setTemplates]=useState(initial.templates),[mealTemplates,setMealTemplates]=useState(initial.mealTemplates),[day,setDay]=useState(initial.day),[healthRecords,setHealthRecords]=useState(initial.healthRecords),[periodHealthRecords,setPeriodHealthRecords]=useState(initial.periodHealthRecords),[view,setView]=useState(initialView),[modal,setModal]=useState<string|null>(null),[editing,setEditing]=useState<HealthEvent|undefined>(),[notice,setNotice]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[search,setSearch]=useState(''),[category,setCategory]=useState('all'),[mobileNav,setMobileNav]=useState(false),[remove,setRemove]=useState<HealthEvent|null>(null),[checkinKey,setCheckinKey]=useState(0);
 useEffect(()=>{if(!demo){setEvents(initial.events);setPeriodEvents(initial.periodEvents);setFoods(initial.foods);setTemplates(initial.templates);setMealTemplates(initial.mealTemplates);setDay(initial.day);setHealthRecords(initial.healthRecords);setPeriodHealthRecords(initial.periodHealthRecords);setView(initialView);}},[initial,initialView,demo]);
 useEffect(()=>{if(notice){const timer=setTimeout(()=>setNotice(''),4500);return()=>clearTimeout(timer);}},[notice]);
 const selectedEvents=events.filter(e=>e.local_date===day.local_date),sum=totals(selectedEvents);
 const checkins=selectedEvents.filter(e=>e.type==='checkin').sort((a,b)=>a.timestamp.localeCompare(b.timestamp));const latest=checkins.at(-1),scores=latest?.data.kind==='checkin'?latest.data.scores:{};
 const mealCount=selectedEvents.filter(e=>e.type==='meal').length;
 const chart=checkins.map(e=>({time:localTime(e.timestamp),...(e.data.kind==='checkin'?e.data.scores:{})}));
 const filtered=selectedEvents.filter(e=>(category==='all'||category===e.type)&&JSON.stringify(e).toLocaleLowerCase('pt-BR').includes(search.toLocaleLowerCase('pt-BR'))).sort((a,b)=>a.timestamp.localeCompare(b.timestamp));
 const go=(v:string)=>{setMobileNav(false);if(demo)setView(v);else router.push(`/${v}?date=${day.local_date}`);};
 const open=(kind:string,event?:HealthEvent)=>{setEditing(event);setModal(kind);setError('');};
 const save=async(input:EventInput,id?:string)=>{
 const parsed=eventSchema.parse(input);const result=demo?{...parsed,id:id??crypto.randomUUID(),local_date:localDate(new Date(parsed.timestamp))}:await saveEvent(parsed,id);
 setEvents(prev=>[...prev.filter(e=>e.id!==result.id),result]);if(input.type==='checkin')setCheckinKey(k=>k+1);setModal(null);setEditing(undefined);setNotice(`Registro ${id?'atualizado':'salvo'}${result.local_date!==day.local_date?` em ${result.local_date}`:''}.`);
 };
 const quickWater=async(volume:number)=>{setBusy(true);setError('');try{const now=new Date();if(day.local_date!==localDate(now)){open('water');return;}await save({timestamp:now.toISOString(),timezone:'Europe/London',type:'water',source:'manual',measurement_type:'measured',estimated:false,notes:'',data:{kind:'water',volume,beverage:'água'}});}catch(e){setError((e as Error).message);}finally{setBusy(false);}};
 const quickContext=async(activity:string)=>{setBusy(true);try{const now=new Date();await save({timestamp:now.toISOString(),timezone:'Europe/London',type:'checkin',source:'manual',measurement_type:'subjective',estimated:false,notes:'',data:{kind:'checkin',preset:activity,scores:{},activity,moods:[],environment:[]}});}catch(e){setError((e as Error).message);}finally{setBusy(false);}};
 const changeDate=(date:string)=>{if(!date)return;if(demo)setDay({...day,local_date:date});else router.push(`/${view}?date=${date}`);};
 const shiftDate=(n:number)=>{const d=new Date(day.local_date+'T12:00:00Z');d.setUTCDate(d.getUTCDate()+n);changeDate(d.toISOString().slice(0,10));};
 const nutritionMetrics:Metric[]=['calories','protein','carbs','fat','saturated_fat','fibre'];
 const dateRange=(period:'week'|'month'|'year')=>{const d=new Date(`${day.local_date}T12:00:00Z`);const end=day.local_date;if(period==='week'){const offset=(d.getUTCDay()+6)%7;d.setUTCDate(d.getUTCDate()-offset);}else if(period==='month')d.setUTCDate(1);else d.setUTCMonth(0,1);return [d.toISOString().slice(0,10),end] as const;};
 const historicalValue=(record:HealthRecord,metric:Metric)=>{const p=record.payload;const num=(key:string)=>typeof p[key]==='number'?p[key] as number:typeof p[key]==='string'&&p[key].trim()!==''&&!Number.isNaN(Number(p[key]))?Number(p[key]):null;const midpoint=(min:string,max:string)=>{const a=num(min),b=num(max);return a!==null&&b!==null?(a+b)/2:a??b;};if(record.category==='meal_history'){const fields:Partial<Record<Metric,[string,string]>>={calories:['Kcal mín','Kcal máx'],protein:['Proteína mín (g)','Proteína máx (g)'],carbs:['Carbo mín (g)','Carbo máx (g)'],fat:['Gordura mín (g)','Gordura máx (g)'],saturated_fat:['Saturada mín (g)','Saturada máx (g)'],fibre:['Fibra mín (g)','Fibra máx (g)']};const pair=fields[metric];return pair?midpoint(...pair):null;}if(record.category==='hydration_history'&&metric==='water'){const beverage=String(p['Bebida']??'').toLowerCase();return /(water|água)/.test(beverage)?num('Volume (mL)'):null;}return null;};
 const averageFor=(metric:Metric,period:'week'|'month'|'year')=>{const [start,end]=dateRange(period);const daily=new Map<string,number>();for(const event of periodEvents){if(event.local_date<start||event.local_date>end)continue;const value=totals([event])[metric];if(typeof value==='number')daily.set(event.local_date,(daily.get(event.local_date)??0)+value);}for(const record of periodHealthRecords){if(record.recorded_on<start||record.recorded_on>end)continue;const value=historicalValue(record,metric);if(value!==null)daily.set(record.recorded_on,(daily.get(record.recorded_on)??0)+value);}const values=[...daily.values()];return values.length?values.reduce((a,b)=>a+b,0)/values.length:null;};
 const averagePanel=<section className="panel nutrition-averages"><div className="panel-heading"><div><h2>Médias de consumo</h2><p className="field-help">Média diária nos dias que possuem registro, até {new Intl.DateTimeFormat('pt-BR',{dateStyle:'medium',timeZone:'Europe/London'}).format(new Date(`${day.local_date}T12:00:00Z`))}.</p></div><span className="subtle">SEMANA · MÊS · ANO</span></div><div className="average-table"><div className="average-head"><span>Item</span><span>Semana</span><span>Mês</span><span>Ano</span></div>{(['water',...nutritionMetrics] as Metric[]).map(metric=><div className="average-row" key={metric}><strong>{metricInfo[metric][0]}<small>{metricInfo[metric][1]}</small></strong>{(['week','month','year'] as const).map(period=>{const value=averageFor(metric,period);return <span key={period}>{value===null?'—':format(value)} <em>{value===null?'':metricInfo[metric][1]}</em></span>})}</div>)}</div></section>;
 const micronutrientPanel=<section className="panel micronutrients"><div className="panel-heading"><h2>Vitaminas e minerais</h2><span className="subtle">TOTAL DO DIA</span></div><div className="micronutrient-grid">{micronutrients.map(k=><span key={k}><small>{nutrientInfo[k][0]}</small><strong>{sum[k]===undefined?'—':format(sum[k]!)} <em>{nutrientInfo[k][1]}</em></strong></span>)}</div></section>;
 const labelRecord=(key:string)=>({hours:'Horas dormidas',duration_hours:'Horas dormidas',sleep_hours:'Horas dormidas',awake_minutes:'Acordado',rem_minutes:'REM',core_minutes:'Core',deep_minutes:'Profundo',subjective_quality:'Qualidade subjetiva',morning_recovery:'Recuperação ao acordar',heart_rate_min:'FC mínima',heart_rate_max:'FC máxima',heart_rate_average:'FC média',respiratory_rate:'Respiração',spo2:'SpO₂',bedtime:'Hora de dormir',wake_time:'Hora de acordar'}[key]??key.replaceAll('_',' '));
 const unitRecord=(key:string)=>key==='hours'||key==='duration_hours'||key==='sleep_hours'?' h':key.endsWith('_minutes')?' min':key.startsWith('heart_rate')?' bpm':key==='respiratory_rate'?' /min':key==='spo2'?' %':'';
 const sleepFields=(value:Record<string,unknown>,prefix=''):Array<[string,unknown]>=>Object.entries(value).flatMap(([key,item])=>item&&typeof item==='object'&&!Array.isArray(item)?sleepFields(item as Record<string,unknown>,`${prefix}${key}_`):item===null||item===''?[]:[[`${prefix}${key}`,item]]);
 const sleepRecords=healthRecords.filter(record=>record.category==='sleep');
 const sleepPanel=sleepRecords.length?<section className="panel sleep-panel"><div className="panel-heading"><h2>Sono e recuperação</h2><span className="subtle">{sleepRecords.at(-1)?.source?.toUpperCase()}</span></div>{sleepRecords.map(record=><div className="sleep-record" key={record.id}><p className="sleep-date">Noite registrada em {new Intl.DateTimeFormat('pt-BR',{dateStyle:'medium',timeZone:'Europe/London'}).format(new Date(`${record.recorded_on}T12:00:00Z`))}</p><div className="sleep-grid">{sleepFields(record.payload).map(([key,value])=><span key={key}><small>{labelRecord(key)}</small><strong>{String(value)}{unitRecord(key)}</strong></span>)}</div></div>)}</section>:null;
 const card=(key:Metric,large=false)=>{const target=day.targets[key],value=sum[key],progress=target?targetProgress(value??0,target):null;const Icon=metricIcons[key];return <div className={`metric ${large?'metric-large':''}`} key={key}><div className="metric-top"><span><Icon size={17}/>{metricInfo[key][0]}</span>{target&&<small>{target.kind==='maximum'?'LIMITE':target.kind==='range'?'FAIXA':'META'}</small>}</div><div className="metric-value">{value===undefined?'—':format(value)}<span>{metricInfo[key][1]}</span></div><div className="metric-meta">{target?`Meta: ${targetLabel(target)} ${metricInfo[key][1]}`:'Meta não definida'}</div>{target&&<><div className={`progress ${progress?.status==='over'?'over':''}`}><div style={{width:`${Math.min(100,progress!.percent)}%`}}/></div><div className={`metric-foot ${progress?.status==='over'?'over-text':''}`}><span>{value===undefined?'Sem registro':progress?.text}</span>{target.kind!=='maximum'&&value!==undefined&&<span>{Math.round(progress!.percent)}%</span>}</div></>}</div>;};
 const timeline=(compact=false)=><div className="timeline">{(compact?filtered.slice(-5):filtered).map(e=><div className="event" key={e.id}><time>{localTime(e.timestamp)}</time><div className={`event-icon ${e.type}`}>{e.type==='water'?<Droplets size={18}/>:e.type==='meal'?<Utensils size={18}/>:<Activity size={18}/>}</div><div className="event-main"><strong>{eventTitle(e)}</strong><p>{e.data.kind==='meal'?`${e.data.items.length} alimento(s) · ${format(totals([e]).calories??0)} kcal registradas`:e.data.kind==='checkin'?`${Object.values(e.data.scores).filter(v=>v!==null).length} campos informados`:e.data.beverage==='água'?'Hidratação':'Líquido separado da meta de água'}</p>{!compact&&<><small>{e.source} · {e.estimated?'estimado':e.measurement_type==='subjective'?'subjetivo':'medido'}</small>{e.notes&&<p>{e.notes}</p>}</>}</div><div className="event-actions"><Button variant="ghost" aria-label={`Editar ${eventTitle(e)}`} onClick={()=>open(e.type,e)}><Pencil size={16}/></Button>{!compact&&<><Button variant="ghost" disabled={busy} aria-label={`Duplicar ${eventTitle(e)}`} onClick={async()=>{setBusy(true);try{await save({...e,timestamp:new Date().toISOString()});}catch(err){setError((err as Error).message);}finally{setBusy(false);}}}><Copy size={16}/></Button><Button variant="ghost" aria-label={`Excluir ${eventTitle(e)}`} onClick={()=>setRemove(e)}><Trash2 size={16}/></Button></>}</div></div>)}{filtered.length===0&&<div className="empty"><Clock3 size={28}/><h3>Seu dia começa aqui</h3><p>Registre água, uma refeição ou como você está se sentindo.</p><Button variant="secondary" onClick={()=>open('choose')}>Criar primeiro registro</Button></div>}</div>;
 return <div className="app-shell"><aside className={`sidebar ${mobileNav?'mobile-open':''}`}><Link href={demo?'/demo':'/hoje'} className="brand"><HeartPulse size={28}/><span>felipe<span className="brand-dot">.</span><small>SAÚDE & PERFORMANCE</small></span></Link><button className="mobile-close" onClick={()=>setMobileNav(false)} aria-label="Fechar navegação"><X/></button><span className="nav-label">MEU DIÁRIO</span><nav>{nav.map(([key,label,Icon])=><button key={key} className={view===key?'active':''} onClick={()=>go(key)} aria-current={view===key?'page':undefined}><Icon size={20}/>{label}{key==='hoje'&&<span className="nav-today"/>}</button>)}</nav><div className="sidebar-bottom"><div className="profile"><span className="avatar">F</span><span><strong>Felipe</strong><small>{demo?'Demonstração':'Espaço pessoal'}</small></span>{!demo&&<Button variant="ghost" aria-label="Sair" onClick={()=>logout()}><LogOut size={18}/></Button>}</div><small className="timezone">Europe/London</small></div></aside>
 <main className="workspace"><header className="topbar"><button className="mobile-menu" onClick={()=>setMobileNav(!mobileNav)} aria-label="Abrir navegação"><Menu/></button><span>Meu diário <span className="slash">/</span> <strong>{nav.find(n=>n[0]===view)?.[1]}</strong></span><span className="topbar-note"><button className="refresh-button" onClick={()=>router.refresh()} title="Atualizar dados">Atualizar</button><span className="tiny-dot"/>{demo?'DADOS FICTÍCIOS':'ESPAÇO PRIVADO'}</span></header>
 {demo&&<div className="demo-banner"><span><strong>Modo demonstração.</strong> Dados fictícios; alterações desaparecem ao recarregar. Não insira dados pessoais.</span><Link href="/login">Acesso privado <ArrowUpRight size={14}/></Link></div>}
 <div className="content"><div className="page-heading"><div><span className="eyebrow">{day.local_date===localDate()?'SEU DIA, EM PERSPECTIVA':'SEU DIÁRIO'}</span><h1>{view==='hoje'?'Como está o seu dia?':nav.find(n=>n[0]===view)?.[1]}</h1><p>{new Intl.DateTimeFormat('pt-BR',{dateStyle:'full',timeZone:'Europe/London'}).format(new Date(day.local_date+'T12:00:00Z'))}</p></div><div className="heading-actions"><div className="date-picker"><button onClick={()=>shiftDate(-1)} aria-label="Dia anterior"><ChevronLeft size={16}/></button><input aria-label="Data do diário" type="date" value={day.local_date} onChange={e=>changeDate(e.target.value)}/><button onClick={()=>shiftDate(1)} aria-label="Próximo dia"><ChevronRight size={16}/></button></div><Button onClick={()=>open('choose')}><Plus size={18}/>Registrar</Button></div></div>
 {error&&<p className="error error-box" role="alert">{error}</p>}
 {view==='hoje'&&<><div className="day-strip"><div><span className="tiny-dot"/><strong>Tipo do dia</strong><select aria-label="Tipo do dia" value={day.day_type} onChange={async e=>{const type=e.target.value;setBusy(true);try{if(!demo)await saveTargets(day.local_date,type,day.targets,false);setDay({...day,day_type:type});setNotice('Tipo do dia atualizado.');}catch(err){setError((err as Error).message);}finally{setBusy(false);}}}>{dayTypes.map(type=><option key={type}>{type}</option>)}</select><span>Metas ajustadas ao seu ritmo</span></div><button onClick={()=>go('metas')}>Ajustar metas <ArrowUpRight size={15}/></button></div><div className="overview-grid"><section className="panel hydration"><div className="panel-heading"><h2><Droplets size={19}/> Hidratação</h2><span className="subtle">ÁGUA PURA</span></div><div className="water-main"><div><span className="water-number">{format(sum.water??0)}</span><span className="water-unit"> ml</span><p>{day.targets.water?`de ${targetLabel(day.targets.water)} ml`:'Defina sua meta diária'}</p></div><div className="water-ring" style={{background:`conic-gradient(#60c5e8 ${Math.min(100,day.targets.water?targetProgress(sum.water??0,day.targets.water).percent:0)}%,#dceef5 0)`}}><span>{day.targets.water?`${Math.round(targetProgress(sum.water??0,day.targets.water).percent)}%`:'—'}</span></div></div><div className="water-buttons"><Button variant="secondary" disabled={busy} onClick={()=>quickWater(650)}><Plus size={17}/>650 ml <small>Copo</small></Button><Button variant="secondary" disabled={busy} onClick={()=>quickWater(590)}><Plus size={17}/>590 ml <small>Garrafa</small></Button></div><button className="text-link" onClick={()=>open('water')}>Outro volume <Plus size={14}/></button></section>
 <section className="panel current-state"><div className="panel-heading"><h2><Brain size={19}/> Agora</h2><span className="subtle">{latest?`CHECK-IN ÀS ${localTime(latest.timestamp)}`:'SEM CHECK-IN'}</span></div><div className="current-grid">{Object.entries(groups.Mental).slice(0,6).map(([key,label])=><div key={key}><span>{label}</span><strong>{scores[key]??'—'}<small>/10</small></strong><div className="mini-track"><i style={{width:`${(scores[key]??0)*10}%`}}/></div></div>)}</div><div className="context-buttons">{['comendo','trabalhando Santander','trabalhando RapiDocs','tocando clarinete','caminhando com Caju','tênis'].map(activity=><Button key={activity} variant="secondary" disabled={busy} onClick={()=>quickContext(activity)}>{activity}</Button>)}</div><Button variant="secondary" onClick={()=>open('checkin')}><Plus size={16}/>Como você está agora?</Button></section></div>
 {sleepPanel}<section className="nutrition-section"><div className="section-heading"><div><h2>Nutrição</h2><span>{mealCount} {mealCount===1?'refeição registrada':'refeições registradas'}</span></div><button onClick={()=>open('meal')}>Registrar refeição <Plus size={16}/></button></div><div className="nutrition-grid">{nutritionMetrics.map(k=>card(k))}</div>{micronutrientPanel}<p className="data-note">Totais consideram somente nutrientes informados. Ausência de registro não significa consumo zero. Valores inferidos pelo ChatGPT aparecem como estimados.</p></section>
 <div className="lower-grid"><section className="panel"><div className="panel-heading"><h2>Seu ritmo ao longo do dia</h2><span className="subtle">CHECK-INS</span></div>{chart.length>0?<><div className="chart-legend"><span><i style={{background:'#287d85'}}/>Energia</span><span><i style={{background:'#7f6cce'}}/>Clareza</span><span><i style={{background:'#d39444'}}/>Motivação</span></div><div className="chart"><ResponsiveContainer width="100%" height="100%"><LineChart data={chart} margin={{left:-26,right:12,top:10,bottom:0}}><CartesianGrid vertical={false} stroke="#e9edef"/><XAxis dataKey="time" axisLine={false} tickLine={false} tick={{fontSize:12}}/><YAxis domain={[0,10]} ticks={[0,5,10]} axisLine={false} tickLine={false} tick={{fontSize:12}}/><Tooltip/><Line name="Energia" dataKey="energy" stroke="#287d85" strokeWidth={2.5} dot={{r:4}} connectNulls={false}/><Line name="Clareza" dataKey="clarity" stroke="#7f6cce" strokeWidth={2.5} dot={{r:4}} connectNulls={false}/><Line name="Motivação" dataKey="motivation" stroke="#d39444" strokeWidth={2.5} dot={{r:4}} connectNulls={false}/></LineChart></ResponsiveContainer></div></>:<div className="empty compact"><Activity/><p>Seus check-ins formarão o gráfico do dia.</p></div>}</section><section className="panel activity-panel"><h2>Movimento & descanso</h2>{(['steps','exercise','sleep'] as Metric[]).map(k=><div className="activity-row" key={k}>{k==='steps'?<Footprints size={20}/>:k==='sleep'?<Moon size={20}/>:<Activity size={20}/>}<span>{metricInfo[k][0]}<small>{day.targets[k]?`Meta: ${targetLabel(day.targets[k]!)} ${metricInfo[k][1]}`:'Sem registro nesta etapa'}</small></span><strong>—</strong></div>)}<p className="field-help">Sono e atividade serão conectados nos próximos módulos.</p></section></div>
 <section className="panel timeline-panel"><div className="panel-heading"><h2>Timeline do dia <span className="count">{selectedEvents.length}</span></h2><button onClick={()=>go('timeline')}>Ver todos <ArrowUpRight size={16}/></button></div>{timeline(true)}</section></>}
 {view==='agua'&&<><div className="standalone-metric">{card('water',true)}</div><div className="quick-actions"><Button disabled={busy} onClick={()=>quickWater(650)}>+650 ml · Copo</Button><Button disabled={busy} onClick={()=>quickWater(590)}>+590 ml · Garrafa</Button><Button variant="secondary" onClick={()=>open('water')}>Outro volume</Button></div><section className="panel"><h2>Registros de água</h2>{selectedEvents.filter(e=>e.type==='water').map(e=><div className="library-row" key={e.id}><span>{localTime(e.timestamp)} · {eventTitle(e)}</span><Button variant="ghost" onClick={()=>open('water',e)}>Editar</Button></div>)}{!selectedEvents.some(e=>e.type==='water')&&<p>Nenhum registro neste dia.</p>}</section></>}
 {view==='check-in'&&<section className="panel form-page"><h2>Check-in agora</h2><p className="field-help">Registre apenas o que faz sentido neste momento.</p><CheckinForm date={day.local_date} key={checkinKey} demo={demo} draft={checkinKey===0?initial.draft:null} onSave={save}/></section>}
 {view==='alimentacao'&&<>{averagePanel}<div className="section-heading"><h2>Sua alimentação</h2><Button onClick={()=>open('meal')}><Plus size={18}/>Registrar refeição</Button></div><div className="nutrition-grid">{nutritionMetrics.map(k=>card(k))}</div>{micronutrientPanel}<section className="panel library"><div className="panel-heading"><h2>Biblioteca de alimentos</h2><Button variant="secondary" onClick={()=>open('food')}><Plus size={16}/>Novo alimento</Button></div><p className="field-help">Informações nutricionais por 100 g. Os registros preservam os valores usados no dia.</p>{foods.map(f=><div className="library-row" key={f.id}><span><strong>{f.name}</strong><small>{f.brand||'Alimento personalizado'}</small></span><span>{typeof f.nutrition.calories!=='number'?'—':format(f.nutrition.calories)} kcal / 100 g</span></div>)}{foods.length===0&&<div className="empty"><Utensils/><p>Cadastre seus alimentos para montar refeições em poucos toques.</p></div>}</section><section className="panel library"><h2>Refeições salvas</h2>{mealTemplates.length===0?<p className="field-help">Ao montar uma refeição, dê um nome e salve a combinação na biblioteca.</p>:mealTemplates.map(t=><div key={t.id} className="library-row"><span>{t.name}<small>{t.items.length} alimento(s)</small></span><Button variant="secondary" onClick={()=>open('meal')}>Usar refeição</Button></div>)}</section></>}
 {view==='timeline'&&<section className="panel"><div className="filters"><label className="search"><Search size={18}/><input aria-label="Buscar registros" placeholder="Buscar alimento, nota, check-in…" value={search} onChange={e=>setSearch(e.target.value)}/></label><select aria-label="Filtrar categoria" value={category} onChange={e=>setCategory(e.target.value)}><option value="all">Todas as categorias</option><option value="water">Água</option><option value="meal">Alimentação</option><option value="checkin">Check-in</option></select></div>{timeline()}</section>}
 {view==='metas'&&<TargetsForm day={day} templates={templates} onSave={async(type,targets,asTemplate)=>{if(!demo)await saveTargets(day.local_date,type,targets,asTemplate);setDay({...day,day_type:type,targets});if(asTemplate)setTemplates(prev=>prev.map(t=>t.day_type===type?{...t,targets}:t));setNotice('Metas atualizadas.');}}/>}
 <footer className="page-footer"><HeartPulse size={15}/><span>Seu histórico se constrói um registro de cada vez.</span><span>Horários de Londres</span></footer></div></main>
 <div className="mobile-quick"><button onClick={()=>quickWater(650)} disabled={busy}><Droplets size={21}/><span>+650 ml</span></button><button onClick={()=>open('meal')}><Utensils size={21}/><span>Comida</span></button><button onClick={()=>open('checkin')}><Activity size={21}/><span>Check-in</span></button><button onClick={()=>open('choose')}><Plus size={21}/><span>Registrar</span></button></div>
 {notice&&<div className="toast" role="status"><Check size={18}/>{notice}</div>}
 <Dialog open={!!modal} onOpenChange={v=>{if(!v){setModal(null);setEditing(undefined);}}}><DialogContent><DialogTitle>{modal==='choose'?'O que deseja registrar?':modal==='water'?'Registrar água':modal==='checkin'?'Check-in':modal==='food'?'Novo alimento':'Registrar refeição'}</DialogTitle><DialogDescription>{modal==='choose'?'Escolha um registro para adicionar ao seu dia.':'Horários em Europe/London.'}</DialogDescription>{modal==='choose'?<div className="register-options">{[['water','Água','Copo, garrafa ou outro volume',Droplets],['meal','Alimentação','Uma refeição ou lanche',Utensils],['checkin','Check-in','Como você está se sentindo',Activity]].map(([key,label,description,Icon])=>{const I=Icon as typeof Droplets;return <button key={key as string} onClick={()=>open(key as string)}><I size={24}/><span><strong>{label as string}</strong><small>{description as string}</small></span><Plus size={18}/></button>;})}<p className="field-help">Fezes, sono, tênis e demais registros entram nas próximas etapas.</p></div>:modal==='water'?<WaterForm date={day.local_date} event={editing} onSave={save}/>:modal==='checkin'?<CheckinForm date={day.local_date} event={editing} onSave={save} draft={checkinKey===0?initial.draft:null} demo={demo}/>:modal==='food'?<FoodForm onSave={async f=>{const food=demo?{...f,id:crypto.randomUUID()}:await saveFood(f);setFoods([...foods,food]);setModal(null);setNotice('Alimento salvo.');}}/>:<MealForm date={day.local_date} foods={foods} templates={mealTemplates} event={editing} onSave={save} onTemplate={async(name,items)=>{const t=demo?{id:crypto.randomUUID(),name,items}:await saveMealTemplate({name,items});setMealTemplates([...mealTemplates,t]);setNotice('Combinação salva.');}}/>}</DialogContent></Dialog>
 <Dialog open={!!remove} onOpenChange={v=>{if(!v)setRemove(null);}}><DialogContent><DialogTitle>Excluir registro?</DialogTitle><DialogDescription>{remove?eventTitle(remove):''}. Ele deixará de contar nos totais do dia.</DialogDescription><div className="choice-row"><Button variant="secondary" onClick={()=>setRemove(null)}>Cancelar</Button><Button variant="destructive" disabled={busy} onClick={async()=>{if(!remove)return;setBusy(true);try{if(!demo)await deleteEvent(remove.id);setEvents(events.filter(e=>e.id!==remove.id));setRemove(null);setNotice('Registro excluído.');}catch(err){setError((err as Error).message);}finally{setBusy(false);}}}>Excluir</Button></div></DialogContent></Dialog>
 </div>;
}
function TargetsForm({day,templates,onSave}:{day:Day;templates:TargetTemplate[];onSave:(type:string,targets:Targets,asTemplate:boolean)=>Promise<void>}){
 const [type,setType]=useState(day.day_type),[targets,setTargets]=useState<Targets>(day.targets),[asTemplate,setAsTemplate]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('');
 useEffect(()=>{setType(day.day_type);setTargets(day.targets);},[day]);
 return <section className="panel targets-form"><h2>Metas do dia</h2><p className="field-help">Valores iniciais fornecidos no seu briefing. Edite conforme seu acompanhamento pessoal.</p><form className="form-stack" onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');try{for(const t of Object.values(targets))targetSchema.parse(t);await onSave(type,targets,asTemplate);}catch{setError('Não foi possível salvar. Confira os valores das metas e sua conexão.');}finally{setBusy(false);}}}><label>Tipo de dia<select value={type} onChange={e=>{setType(e.target.value);setTargets(templates.find(t=>t.day_type===e.target.value)?.targets??{});}}>{dayTypes.map(t=><option key={t}>{t}</option>)}</select></label><div className="target-list">{Object.entries(metricInfo).map(([key,[label,unit]])=>{const k=key as Metric,t=targets[k];return <div className="target-row" key={key}><label className="checkbox-label"><input type="checkbox" checked={!!t} onChange={e=>{const next={...targets};if(e.target.checked)next[k]={kind:'exact',min:1,max:null};else delete next[k];setTargets(next);}}/><span>{label}<small>{unit}</small></span></label>{t&&<><select aria-label={`Tipo de meta de ${label}`} value={t.kind} onChange={e=>setTargets({...targets,[k]:{kind:e.target.value as typeof t.kind,min:t.min??1,max:t.max??t.min??1}})}><option value="minimum">Mínimo</option><option value="maximum">Máximo</option><option value="range">Intervalo</option><option value="exact">Alvo</option></select>{t.kind!=='maximum'&&<input aria-label={`Mínimo ou alvo de ${label}`} type="number" min="0.1" step="any" required value={t.min??''} onChange={e=>setTargets({...targets,[k]:{...t,min:e.target.value===''?null:Number(e.target.value)}})}/>}<span>{t.kind==='range'?'até':''}</span>{(t.kind==='maximum'||t.kind==='range')&&<input aria-label={`Máximo de ${label}`} type="number" min="0.1" step="any" required value={t.max??''} onChange={e=>setTargets({...targets,[k]:{...t,max:e.target.value===''?null:Number(e.target.value)}})}/>}</>}</div>;})}</div><label className="checkbox-label"><input type="checkbox" checked={asTemplate} onChange={e=>setAsTemplate(e.target.checked)}/> Usar também como modelo para próximos dias deste tipo</label><p className="field-help">Dias já configurados preservam suas metas.</p>{error&&<p className="error" role="alert">{error}</p>}<Button disabled={busy}>{busy?'Salvando…':'Salvar metas'}</Button></form></section>;
}
