'use client';
import { defaultHealthProfile,defaultHealthCards,defaultHealthSections } from '@/lib/health-profile-defaults';
import { useEffect,useState } from 'react';
import { Save } from 'lucide-react';
import { saveHealthProfile } from '@/app/actions';
import { Button } from './ui/button';
type Measurement={recorded_on:string;payload:Record<string,unknown>;source:string}|null;
const label=(key:string)=>key.replace(/_/g,' ');
const bodyValue=(key:string,item:unknown)=>typeof item==='string'&&/^\d{4}-\d{2}-\d{2}/.test(item)?new Date(item.slice(0,10)+'T12:00:00Z').toLocaleDateString('pt-BR'):typeof item==='number'?new Intl.NumberFormat('pt-BR',{maximumFractionDigits:2}).format(item):String(item);
export function HealthProfile({initial,measurements}:{initial?:Record<string,unknown>;measurements:Measurement}){const [value,setValue]=useState<Record<string,unknown>>({...(initial?.personal_health_initialized?{}:defaultHealthProfile),...Object.fromEntries(Object.entries(initial??{}).filter(([key])=>!key.startsWith('personal_')))}),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState('');useEffect(()=>{setValue({...(initial?.personal_health_initialized?{}:defaultHealthProfile),...Object.fromEntries(Object.entries(initial??{}).filter(([key])=>!key.startsWith('personal_')))});},[JSON.stringify(initial)]);const display=initial?.personal_health_display as {cards?:string[][];sections?:[string,string[]][]}|undefined;const cards=display?.cards??defaultHealthCards,sections=display?.sections??defaultHealthSections;const body=measurements?Object.entries(measurements.payload).filter(([,item])=>item!==null&&item!==''&&typeof item!=='object'):[];return <div className="profile-layout"><section className="profile-summary">{cards.map(([label,item])=><article className="metric" key={label}><div className="metric-top"><span>{label}</span></div><div className="metric-value">{item}</div></article>)}</section>{measurements&&<section className="panel body-measurements"><div className="panel-heading"><div><h2>Última bioimpedância e medidas</h2><p className="field-help">Registro de {new Intl.DateTimeFormat('pt-BR',{dateStyle:'medium'}).format(new Date(`${measurements.recorded_on}T12:00:00Z`))} · {measurements.source}</p></div></div><div>{body.map(([key,item])=><article key={key}><small>{label(key)}</small><strong>{bodyValue(key,item)}</strong></article>)}</div></section>}<section className="profile-sections">{sections.map(([title,items])=><article key={title}><h2>{title}</h2><ul>{items.map(item=><li key={item}>{item}</li>)}</ul></article>)}</section><section className="panel form-page"><h2>Detalhes para contextualizar o diário</h2><p className="field-help">Revise e atualize estes dados quando necessário. Eles servem de contexto e não substituem acompanhamento clínico.</p><form className="form-stack" onSubmit={async event=>{event.preventDefault();setBusy(true);setError('');try{await saveHealthProfile(value);setMessage('Perfil de saúde salvo.');}catch(err){setError((err as Error).message);}finally{setBusy(false);}}}>{Object.entries(value).map(([key,text])=><label key={key}>{key}<textarea value={String(text??'')} maxLength={5000} onChange={e=>setValue(current=>({...current,[key]:e.target.value}))}/></label>)}<label>Outra informação de saúde relevante<textarea value={String(value['Outras informações']??'')} maxLength={5000} onChange={e=>setValue(current=>({...current,'Outras informações':e.target.value}))}/></label>{error&&<p className="error">{error}</p>}{message&&<p className="success">{message}</p>}<Button disabled={busy}><Save size={16} strokeWidth={1.9}/>{busy?'Salvando…':'Salvar perfil'}</Button></form></section></div>}
