'use client';
import { InvestmentOverview } from './investment-overview';
import { useRouter } from 'next/navigation';
import { useEffect,useState } from 'react';
import { ChevronDown,NotebookText,PencilLine,TrendingUp } from 'lucide-react';
import { LineChart,Line,XAxis,YAxis,Tooltip,ResponsiveContainer,CartesianGrid } from 'recharts';
import { investmentChange,monthlyAsset,monthlyPortfolio,inPounds,investmentType,investmentsSchema,type InvestmentSnapshot } from '@/lib/investments';
import { saveInvestment } from '@/app/actions';
const money=(v:number,c:string)=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:c}).format(v);
const axisTick={fontSize:12,fill:'var(--label-2)'};
const tooltipStyle={background:'var(--bg-elevated)',border:'1px solid var(--separator-soft)',borderRadius:12,boxShadow:'var(--shadow-2)',padding:'8px 12px',fontSize:13,lineHeight:'18px'};
const tooltipLabel={color:'var(--label)',fontWeight:600,marginBottom:2};
const tooltipItem={color:'var(--label-2)',padding:0};
const tooltipCursor={stroke:'var(--separator)'};
const lineDot={r:4,fill:'var(--tint-invest)',stroke:'var(--bg-2)',strokeWidth:2};
const activeDot={r:6,fill:'var(--tint-invest)',stroke:'var(--bg-2)',strokeWidth:2};
const compactNumber=(v:unknown)=>Number(v).toLocaleString('pt-BR',{maximumFractionDigits:0});
export function InvestmentsDashboard({initial,embedded=false}:{initial:unknown;embedded?:boolean}){
 const router=useRouter();
 const parsed=investmentsSchema.safeParse(initial);const [history,setHistory]=useState<InvestmentSnapshot[]>(parsed.success?parsed.data:[]),[selected,setSelected]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 useEffect(()=>{const result=investmentsSchema.safeParse(initial);if(result.success)setHistory(result.data);},[initial]);
 const ids=[...new Set(history.flatMap(s=>s.items.map(i=>i.asset_id)))];const asset=selected||ids[0]||'';const converted=inPounds(history);const comparison=investmentChange(converted,asset);const monthly=monthlyAsset(converted,asset);const totals=monthlyPortfolio(converted).map(m=>({date:m.month+'-15T12:00:00Z',value:m.totals.reduce((sum,t)=>sum+t.value,0)}));
 const [form,setForm]=useState({asset_id:'',name:'',account:'',currency:'GBP',value:'',net_flow:'',date:new Date().toISOString().slice(0,10),notes:''});
 return <div className="finance-page investments-page">
  {!embedded&&<header className="page-heading"><div><span className="eyebrow">FINANCEIRO</span><h1>Investimentos</h1><p>Atualizações enviadas pelo GPT e evolução de cada investimento.</p></div></header>}
  <p className="field-help">Envie o print ao Felipe MCP e peça para registrar seus investimentos. Apenas valores legíveis são registrados. Ausência de um ativo em um print não significa saldo zero.</p>
  {!embedded&&<InvestmentOverview history={history}/>}
  <section className="panel investment-panel"><div className="panel-heading"><div><h2>Evolução mensal · total em libras</h2><p className="field-help">Último saldo conhecido por ativo. Atualizações parciais mantêm os saldos anteriores; aportes, resgates e câmbio podem alterar a variação.</p></div></div><div className="investment-chart"><ResponsiveContainer width="100%" height="100%"><LineChart data={totals} margin={{top:8,right:8,left:0,bottom:0}}><CartesianGrid vertical={false} stroke="var(--separator-soft)"/><XAxis dataKey="date" tickLine={false} axisLine={false} tick={axisTick} tickFormatter={v=>new Date(v).toLocaleDateString('pt-BR',{month:'short',year:'numeric'})}/><YAxis domain={['auto','auto']} width={64} tickLine={false} axisLine={false} tick={axisTick} tickFormatter={compactNumber}/><Tooltip labelFormatter={v=>new Date(String(v)).toLocaleDateString('pt-BR',{month:'long',year:'numeric'})} formatter={v=>money(Number(v),'GBP')} cursor={tooltipCursor} contentStyle={tooltipStyle} labelStyle={tooltipLabel} itemStyle={tooltipItem}/><Line dataKey="value" name="Total em libras" type="monotone" stroke="var(--tint-invest)" strokeWidth={2.5} dot={lineDot} activeDot={activeDot}/></LineChart></ResponsiveContainer></div></section>
  <div className="investment-groups"><div className="section-heading"><div><h2>Investimentos por tipo</h2></div></div>{['Cripto','Ações','ETFs','Fundos','Renda fixa','Caixa','Outros'].map(type=>{const matching=ids.filter(id=>investmentType(investmentChange(history,id).current!)===type);return matching.length?<section className="investment-group" key={type}><h3>{type}</h3><div className="investment-cards">{matching.map(id=>{const c=investmentChange(converted,id),item=c.current;const original=investmentChange(history,id).current!;return <button type="button" className={`panel investment-card ${asset===id?'selected':''}`} aria-pressed={asset===id} key={id} onClick={()=>setSelected(id)}><small>{original.account}</small><h2>{original.name}</h2><strong>{item?money(item.value,'GBP'):'Cotação pendente'}</strong><span className={c.delta===null?undefined:c.delta>=0?'up':'down'}>{c.delta===null?'Primeira atualização':`${c.delta>=0?'+':''}${money(c.delta,'GBP')} desde a última atualização`}</span><small>{new Date(original.date).toLocaleDateString('pt-BR',{timeZone:'Europe/London'})}</small></button>})}</div></section>:null;})}</div>
  {comparison.current?<section className="panel investment-panel"><div className="panel-heading"><div><h2>{comparison.current.name} · evolução mensal</h2><p className="field-help">Valores em libras, usando a cotação gravada em cada atualização. Pode incluir aportes e resgates; não é uma taxa de rentabilidade.</p></div></div>{comparison.adjusted!==null&&<p>Variação descontando o aporte/resgate informado: {money(comparison.adjusted,comparison.current.currency)}</p>}<div className="investment-chart"><ResponsiveContainer width="100%" height="100%"><LineChart data={monthly} margin={{top:8,right:8,left:0,bottom:0}}><CartesianGrid stroke="var(--separator-soft)" vertical={false}/><XAxis dataKey="date" tickLine={false} axisLine={false} tick={axisTick} tickFormatter={v=>new Date(v).toLocaleDateString('pt-BR')}/><YAxis width={72} domain={['auto','auto']} tickLine={false} axisLine={false} tick={axisTick} tickFormatter={compactNumber}/><Tooltip labelFormatter={v=>new Date(String(v)).toLocaleString('pt-BR')} formatter={v=>money(Number(v),comparison.current!.currency)} cursor={tooltipCursor} contentStyle={tooltipStyle} labelStyle={tooltipLabel} itemStyle={tooltipItem}/><Line dataKey="value" name="Valor" type="monotone" stroke="var(--tint-invest)" strokeWidth={2.5} dot={lineDot} activeDot={activeDot}/></LineChart></ResponsiveContainer></div><div className="personal-table-scroll"><table className="summary-table"><thead><tr><th>Mês · última atualização</th><th>Valor</th><th>Variação desde o mês anterior registrado</th></tr></thead><tbody>{monthly.slice().reverse().map(point=><tr key={point.id}><td>{new Date(point.date).toLocaleString('pt-BR',{timeZone:'Europe/London'})}</td><td>{money(point.value,point.currency)}</td><td>{point.delta==null?'Primeiro mês':`${point.delta>=0?'+':''}${money(point.delta,point.currency)}`}</td></tr>)}</tbody></table></div></section>
  :<section className="panel empty compact"><TrendingUp aria-hidden/><h3>Aguardando a primeira atualização</h3><p>Envie seus prints pelo GPT ou registre um valor abaixo para iniciar o gráfico.</p></section>}
  <details className="information-card"><summary><span className="information-icon" aria-hidden><NotebookText/></span><span><strong>Observações dos registros</strong></span><ChevronDown className="expand-arrow" aria-hidden/></summary><div className="information-body investment-notes">{history.slice().sort((a,b)=>Date.parse(b.as_of)-Date.parse(a.as_of)).map(snapshot=><article key={snapshot.id}><h3>{new Date(snapshot.as_of).toLocaleDateString('pt-BR',{timeZone:'Europe/London'})}</h3><p className="field-help">{snapshot.notes||'Sem observações.'}</p>{snapshot.items.filter(i=>i.fx).map(i=><p className="field-help" key={i.asset_id}>{i.name}: taxa registrada {i.fx!.rate} GBP por unidade da moeda de origem · {i.fx!.date} · <a href={i.fx!.source}>Fonte</a></p>)}</article>)}</div></details>
  <details className="information-card"><summary><span className="information-icon" aria-hidden><PencilLine/></span><span><strong>Registrar atualização manual</strong></span><ChevronDown className="expand-arrow" aria-hidden/></summary><div className="information-body"><form className="finance-form" onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');try{const snapshot:InvestmentSnapshot={id:crypto.randomUUID(),as_of:form.date+'T12:00:00Z',items:[{asset_id:form.asset_id,name:form.name,account:form.account,currency:form.currency,value:Number(form.value),net_flow:form.net_flow===''?null:Number(form.net_flow)}],notes:form.notes};const saved=await saveInvestment(snapshot);setHistory([...history,saved.snapshot]);router.refresh();setSelected(form.asset_id);setMessage('Atualização salva.');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}><label>Investimento existente<select value={ids.includes(form.asset_id)?form.asset_id:''} onChange={e=>{const item=investmentChange(history,e.target.value).current;if(item)setForm({...form,asset_id:item.asset_id,name:item.name,account:item.account,currency:item.currency});else setForm({...form,asset_id:'',name:'',account:''});}}><option value="">Novo investimento</option>{ids.map(id=><option key={id} value={id}>{investmentChange(history,id).current?.name} · {id}</option>)}</select></label><div className="personal-form-grid">{([['asset_id','Identificador estável (ex.: wise-fundo-gbp)','text'],['name','Nome','text'],['account','Conta / plataforma','text'],['currency','Moeda (GBP, BRL, USD…)','text'],['value','Valor atual','number'],['net_flow','Aporte (+) / resgate (−) desde o anterior, se conhecido','number'],['date','Data de referência','date'],['notes','Observações','text']] as const).map(([key,label,type])=><label key={key}>{label}<input type={type} step={type==='number'?'any':undefined} min={key==='value'?0:undefined} required={!['net_flow','notes'].includes(key)} value={form[key]} onChange={e=>setForm({...form,[key]:e.target.value})}/></label>)}</div><button disabled={busy} className={embedded?'button tinted':'button primary'}>{busy?'Salvando…':'Salvar atualização'}</button><p role="status" className="field-help">{message}</p>{error&&<p className="error" role="alert">{error}</p>}</form></div></details>
 </div>;
}
