'use client';
import type { CSSProperties } from 'react';
import { sleepData,sleepNights } from '@/lib/sleep-data';
import { formatSleepDuration } from '@/lib/sleep-duration';
import { sleepQuality } from '@/lib/sleep-quality';
import { BedDouble, CalendarDays, ChartColumn, HeartPulse, Layers, Moon, TrendingUp } from 'lucide-react';
import { LineChart,Line,XAxis,YAxis,Tooltip,ResponsiveContainer,CartesianGrid } from 'recharts';
type RecordRow={id:string;category:string;recorded_on:string;recorded_at:string|null;payload:Record<string,unknown>;source:string};
type Sleep={id:string;date:string;hours:number|null;rem:number|null;core:number|null;deep:number|null;awake:number|null;recovery:number|null;quality:number|null;explanation:string;hr:number|null;resp:number|null;spo2:number|null;source:string;details:Record<string,unknown>};
type Field=keyof Pick<Sleep,'hours'|'rem'|'core'|'deep'|'awake'|'recovery'|'quality'|'hr'|'resp'|'spo2'>;
const key=(value:string)=>value.normalize('NFD').replace(/[̀-ͯ]/g,'').toLowerCase().replace(/[^a-z0-9]/g,'');
const flattened=(value:unknown,prefix=''):Record<string,unknown>=>value&&typeof value==='object'&&!Array.isArray(value)?Object.entries(value as Record<string,unknown>).reduce((all,[name,item])=>({...all,...flattened(item,prefix?`${prefix} ${name}`:name)}),{} as Record<string,unknown>):prefix?{[prefix]:value}:{};
const raw=(payload:Record<string,unknown>,aliases:string[])=>{const all=flattened(payload);for(const alias of aliases){const sought=key(alias);const found=Object.entries(all).find(([name])=>{const candidate=key(name);return candidate===sought||candidate.endsWith(sought)||candidate.includes(sought);});if(found)return found[1];}return null;};
const numeric=(value:unknown)=>{if(typeof value==='number'&&Number.isFinite(value))return value;if(typeof value!=='string')return null;const clean=value.trim().replace(',','.');const clock=clean.match(/^(\d+)\s*h(?:\s*(\d+)\s*(?:m|min)?)?$/i);if(clock)return Number(clock[1])+Number(clock[2]??0)/60;const result=Number(clean.replace(/[^0-9.-]/g,''));return Number.isFinite(result)?result:null;};
const average=(values:(number|null)[])=>{const numbers=values.filter((value):value is number=>value!==null);return numbers.length?numbers.reduce((sum,value)=>sum+value,0)/numbers.length:null;};
const formatAverage=(value:number|null,unit:string)=>unit==='h'||unit==='min'?formatSleepDuration(value===null?null:unit==='h'?value*60:value):format(value);
const format=(value:number|null)=>value===null?'—':new Intl.NumberFormat('pt-BR',{maximumFractionDigits:1}).format(value);
const rangeStart=(days:number)=>{const now=new Date();now.setHours(12,0,0,0);now.setDate(now.getDate()-days+1);return now.toISOString().slice(0,10);};
/* Chart presentation (HIG charts): hairline grid, no vertical lines, 12px secondary ticks, elevated tooltip. */
const axis={axisLine:false,tickLine:false,tick:{fontSize:12,fill:'var(--label-2)'}} as const;
const tooltip={contentStyle:{background:'var(--bg-elevated)',border:'1px solid var(--separator-soft)',borderRadius:12,boxShadow:'var(--shadow-2)',padding:'8px 12px',fontSize:13,lineHeight:'18px'},labelStyle:{color:'var(--label-2)',fontWeight:600,marginBottom:4},itemStyle:{color:'var(--label)',padding:0},cursor:{stroke:'var(--separator)'}} as const;
const line=(color:string)=>({stroke:color,strokeWidth:2.5,dot:{r:3,strokeWidth:0,fill:color},activeDot:{r:5,strokeWidth:0,fill:color}});
const dot=(color:string)=>({['--dot' as string]:color}) as CSSProperties;
const stageColor={deep:'var(--sys-purple)',core:'var(--sys-blue)',rem:'var(--sys-cyan)',awake:'var(--sys-orange)'} as const;
type Stage=[keyof typeof stageColor,number|null,string];
export function SleepDashboard({records}:{records:RecordRow[]}){const mapped:Sleep[]=sleepNights(records).map(record=>({id:record.id,date:record.recorded_on,hours:sleepData(record.payload).total===null?null:sleepData(record.payload).total!/60,rem:sleepData(record.payload).rem,core:sleepData(record.payload).core,deep:sleepData(record.payload).deep,awake:sleepData(record.payload).awake,recovery:numeric(raw(record.payload,['morning recovery','recuperacao ao acordar','recovery'])),quality:sleepQuality(record.payload).score,explanation:sleepQuality(record.payload).explanation,hr:numeric(raw(record.payload,['heart rate average','heart rate min','fc repouso','fc media'])),resp:numeric(raw(record.payload,['respiratory rate','respiracao min'])),spo2:numeric(raw(record.payload,['spo2','spo2 percent'])),source:record.source,details:flattened(record.payload)}));const sessions=mapped.filter(session=>session.hours!==null||session.rem!==null||session.core!==null||session.deep!==null||session.awake!==null).sort((a,b)=>a.date.localeCompare(b.date));const latest=sessions.at(-1);const period=(days:number)=>sessions.filter(session=>session.date>=rangeStart(days));const stat=(field:Field,days:number)=>average(period(days).map(session=>session[field]));const chart=sessions.slice(-30).map(session=>({date:new Date(`${session.date}T12:00:00Z`).toLocaleDateString('pt-BR',{day:'2-digit',month:'short'}),nota:session.quality,sono:session.hours,profundo:session.deep===null?null:session.deep/60,rem:session.rem===null?null:session.rem/60}));const cards=[['Nota da noite',latest?.quality??null,'/10',Moon],['Sono total',latest?.hours==null?null:latest.hours*60,'duration',Moon],['Profundo',latest?.deep??null,'duration',BedDouble],['REM',latest?.rem??null,'duration',BedDouble],['Core',latest?.core??null,'duration',BedDouble],['Acordado',latest?.awake??null,'duration',Moon],['Recuperação',latest?.recovery??null,'/10',HeartPulse]] as const;const stages=([['deep',latest?.deep??null,'Profundo'],['core',latest?.core??null,'Core'],['rem',latest?.rem??null,'REM'],['awake',latest?.awake??null,'Acordado']] as Stage[]).filter((stage):stage is [keyof typeof stageColor,number,string]=>typeof stage[1]==='number'&&stage[1]>0);
 return <div className="sleep-dashboard">
  <div className="tennis-hero"><div className="health-hero-lead"><span className="health-hero-icon" aria-hidden><Moon/></span><div><span className="eyebrow">RECUPERAÇÃO</span><h1>Sono</h1><p>Acompanhe suas noites, estágios e sinais de recuperação.</p></div></div></div>
  {!sessions.length?<section className="panel empty"><Moon size={30}/><h3>Ainda não há sono para exibir</h3><p>Envie uma imagem do Apple Health pelo ChatGPT ou registre os dados manualmente.</p></section>:<>
  <section className="sleep-latest">
   <div className="panel sleep-night">
    <span className="subtle">ÚLTIMA NOITE · {new Intl.DateTimeFormat('pt-BR',{dateStyle:'medium'}).format(new Date(`${latest!.date}T12:00:00Z`))}</span>
    <div className="sleep-kpis">{cards.map(([label,value,unit,Icon])=><article key={label}><Icon size={18}/><small>{label}</small><strong>{unit==='duration'?formatSleepDuration(value):format(value)} <em>{unit==='duration'?'':unit}</em></strong></article>)}</div>
    {stages.length>0&&<div className="sleep-stages" aria-hidden><div className="sleep-stage-bar">{stages.map(([stage,minutes])=><i key={stage} className={`stage-${stage}`} style={{flexGrow:minutes}}/>)}</div><div className="health-chart-legend">{stages.map(([stage,,label])=><span key={stage} style={dot(stageColor[stage])}><i/>{label}</span>)}</div></div>}
   </div>
   <section className="panel sleep-averages"><div className="panel-heading"><h2><ChartColumn/>Médias diárias</h2><span className="subtle">DIAS COM REGISTRO</span></div><div className="sleep-average-grid">{([['Sono','hours','h'],['Profundo','deep','min'],['REM','rem','min'],['Qualidade','quality','/10'],['Recuperação','recovery','/10']] as [string,Field,string][]).map(([label,field,unit])=>{const cell=(value:number|null,period:string)=><div><strong>{formatAverage(value,unit)}<em> {unit==='/10'?unit:''}</em></strong><span>{period}</span></div>;return <article key={label}><small>{label}</small>{cell(stat(field,7),'semana')}{cell(stat(field,30),'mês')}{cell(average(sessions.map(session=>session[field])),'histórico')}</article>;})}</div></section>
  </section>
  <section className="panel"><div className="panel-heading"><h2><TrendingUp/>Histórico das notas</h2><span className="subtle">ÚLTIMAS 30 NOITES · /10</span></div><p className="field-help">Estimativa do diário, não uma avaliação clínica. Duração vale até 5 pontos; profundo e REM, 2 cada; tempo acordado, 1. Campos ausentes são excluídos do cálculo.</p><p className="field-help">{latest?.explanation}</p><div className="sleep-chart"><ResponsiveContainer width="100%" height="100%"><LineChart data={chart} margin={{left:-25,right:12,top:8,bottom:0}}><CartesianGrid vertical={false} stroke="var(--separator-soft)"/><XAxis dataKey="date" {...axis} minTickGap={24}/><YAxis domain={[0,10]} ticks={[0,5,10]} {...axis}/><Tooltip {...tooltip}/><Line name="Nota do sono" dataKey="nota" {...line('var(--tint-sleep)')} connectNulls={false}/></LineChart></ResponsiveContainer></div><div className="health-chart-legend"><span style={dot('var(--tint-sleep)')}><i/>Nota do sono</span></div></section>
  <section className="panel"><div className="panel-heading"><h2><Layers/>Duração e estágios</h2><span className="subtle">ÚLTIMAS 30 NOITES</span></div><div className="sleep-chart"><ResponsiveContainer width="100%" height="100%"><LineChart data={chart} margin={{left:-25,right:12,top:8,bottom:0}}><CartesianGrid vertical={false} stroke="var(--separator-soft)"/><XAxis dataKey="date" {...axis} minTickGap={24}/><YAxis domain={[0,10]} ticks={[0,5,10]} {...axis}/><Tooltip {...tooltip} formatter={(value)=>formatSleepDuration(value==null?null:Number(value)*60)}/><Line name="Sono total" dataKey="sono" {...line('var(--tint-sleep)')} connectNulls/><Line name="Profundo" dataKey="profundo" {...line(stageColor.deep)} connectNulls/><Line name="REM" dataKey="rem" {...line(stageColor.rem)} connectNulls/></LineChart></ResponsiveContainer></div><div className="health-chart-legend"><span style={dot('var(--tint-sleep)')}><i/>Sono total</span><span style={dot(stageColor.deep)}><i/>Profundo</span><span style={dot(stageColor.rem)}><i/>REM</span></div></section>
  <section className="panel sleep-history"><div className="panel-heading"><h2><CalendarDays/>Noites registradas</h2><span className="subtle">{sessions.length} NOITES</span></div>{sessions.slice().reverse().slice(0,60).map(session=><article key={session.id}><time>{new Intl.DateTimeFormat('pt-BR',{day:'2-digit',month:'short',year:'numeric'}).format(new Date(`${session.date}T12:00:00Z`))}</time><div><strong>{formatSleepDuration(session.hours===null?null:session.hours*60)} de sono · Nota {format(session.quality)}/10</strong><p className="field-help">{session.explanation}</p><small>{[session.deep!==null&&`Profundo ${formatSleepDuration(session.deep)}`,session.rem!==null&&`REM ${formatSleepDuration(session.rem)}`,session.core!==null&&`Core ${formatSleepDuration(session.core)}`,session.awake!==null&&`Acordado ${format(session.awake)} min`,session.spo2!==null&&`SpO₂ ${format(session.spo2)}%`].filter(Boolean).join(' · ')||Object.entries(session.details).filter(([,value])=>value!==null&&value!==''&&typeof value!=='object').map(([key,value])=>`${key.replace(/[_-]/g,' ')}: ${String(value)}`).join(' · ')||'Dados de sono registrados'}</small></div></article>)}</section>
  </>}
 </div>;
}
