import {secondsDuration} from '@/lib/exercise-records';
const labels:Record<string,string>={duration_seconds:'Duração exata',duration_minutes:'Duração (min)',started_at:'Início',ended_at:'Fim',active_calories:'Calorias ativas (kcal)',total_calories:'Calorias totais (kcal)',heart_rate_average:'FC média (bpm)',watch_effort:'Esforço Apple Watch /10',watch_effort_label:'Classificação Apple Watch',effort:'Esforço percebido /10',location:'Local',weather:'Condições do ambiente',temperature_c:'Temperatura (°C)',humidity_percent:'Umidade (%)',air_quality_index:'Índice de qualidade do ar',steps:'Passos',distance_km:'Distância (km)',stand_hours:'Horas com meta em pé atingida',stand_hours_goal:'Meta de horas em pé',exercise_minutes:'Minutos de exercício (anel)',exercise_minutes_goal:'Meta de exercício (min)',active_calories_goal:'Meta de calorias ativas',idle_hours:'Horas sem meta em pé atingida',snapshot_at:'Horário do resumo',capture_time:'Horário da captura',exercise_chart_total_text:'Rodapé do gráfico (original)',measurement_notes:'Notas da medição',time_precision:'Precisão dos horários',source:'Fonte',notes:'Observações',type:'Tipo',match_type:'Tipo de partida',score:'Placar',outcome:'Resultado',result:'Resultado',analysis:'Análise',opponent_or_partner:'Adversário / parceiro',sets:'Sets',felipe:'Você',adversario:'Adversário',physical_energy:'Energia física',clarity:'Clareza mental',performance:'Desempenho',activity_type:'Atividade',kind:'Tipo de registro',record_type:'Tipo de registro'};
function Leaves({value}:{value:Record<string,unknown>}){return <dl className="workout-data-grid">{Object.entries(value).map(([key,v])=>v==null?null:<div key={key} data-key={key}><dt>{labels[key]??key.replaceAll('_',' ')}</dt><dd>{v&&typeof v==='object'?Array.isArray(v)?<div>{v.map((item,index)=><div key={index}>{typeof item==='object'&&item?<Leaves value={item as Record<string,unknown>}/>:String(item)}</div>)}</div>:<Leaves value={v as Record<string,unknown>}/>:key==='duration_seconds'?secondsDuration(v):typeof v==='number'?new Intl.NumberFormat('pt-BR',{maximumFractionDigits:2}).format(v):typeof v==='string'&&/^\d{4}-\d{2}-\d{2}T/.test(v)&&Number.isFinite(Date.parse(v))?new Intl.DateTimeFormat('pt-BR',{dateStyle:'short',timeStyle:'short',timeZone:'Europe/London'}).format(new Date(v)):String(v)}</dd></div>)}</dl>}
export function WorkoutDetails({payload,omit=[],title='Todos os dados registrados'}:{payload:Record<string,unknown>;omit?:string[];title?:string}){
 const zones=Array.isArray(payload.heart_rate_zones)?payload.heart_rate_zones as Record<string,number>[]:[];
 const recovery=Array.isArray(payload.post_workout_heart_rate)?payload.post_workout_heart_rate as Record<string,number>[]:[];
 const other=Object.fromEntries(Object.entries(payload).filter(([k,v])=>v!=null&&v!==''&&!['heart_rate_zones','post_workout_heart_rate',...omit].includes(k)));
 return <div className="workout-details">{zones.length>0&&<section><h3>Zonas de frequência cardíaca</h3><div className="workout-zones">{zones.map((z,i)=><div key={i}><strong>Zona {z.zone}</strong><span>{secondsDuration(z.duration_seconds)}</span><small>{z.max_bpm_exclusive!=null?`< ${z.max_bpm_exclusive}`:z.max_bpm!=null?`${z.min_bpm}–${z.max_bpm}`:`${z.min_bpm}+`} bpm</small></div>)}</div></section>}{recovery.length>0&&<section><h3>FC após o exercício</h3><div className="workout-recovery">{recovery.map((r,i)=><article key={i}><small>{r.elapsed_minutes===0?'Ao terminar':`${r.elapsed_minutes} min depois`}</small><strong>{r.bpm} <small>bpm</small></strong></article>)}</div></section>}{Object.keys(other).length>0&&<section><h3>{title}</h3><Leaves value={other}/></section>}</div>;
}
