export const defaultHealthProfile={
 'Identificação de saúde':'Tipo sanguíneo B+. Altura 1,80 m. Óculos: astigmatismo leve (R −0,50; L −0,25).',
 'Condição e histórico':'Prolapso leve da válvula mitral, conforme relato médico, sem limitações conhecidas. Histórico de entorses no tornozelo no futebol, com recuperação funcional completa.',
 'Histórico familiar relevante':'Avó materna: hipertensão, AVC e tireoide. Avó paterna: diabetes e evento cardíaco. Avô paterno: cirrose de causa não esclarecida.',
 'Capacidade e metabolismo':'VO₂ max 61,2. Resting energy médio: 1.824 kcal/dia. Referência histórica de atividade: 86 min/dia, 11.755 passos/dia e 8,3 km/dia. FC registrada: 41–197 bpm; sono: 42–109 bpm.',
 'Sono e rotina':'Em geral acorda às 7h30 e dorme por volta de 23h. Referência histórica: 9h13 de sono por noite; Core 7h46, REM 35 min e profundo 31 min.',
 'Sensibilidades digestivas':'Algumas massas com glúten podem causar gases e estufamento. Feijão, grão-de-bico e lentilha podem causar gases e diarreia. Churrasco e excesso de carne vermelha podem causar gases. Pilsen/Lager acima de 2 pints pode causar gases e diarreia. Alguns queijos podem desencadear enxaqueca com aura.',
 'Rotina e atividade':'Caminhadas com Caju pela manhã e fim da tarde; trabalho 9h–17h; tênis frequente; alongamento e faixas de resistência; sauna, jacuzzi e, quando necessário, piscina de gelo no clube.',
 'Suplementos':'Dia: vitamina C, vitamina D, biotina, ômega-3 e Lion’s Mane. Noite: magnésio composto, glucosamina com condroitina, BCAA e colágeno. A rotina registrada no diário pode ser ajustada conforme o uso real.',
 'Objetivo':'Manter saúde e atividade ao longo da vida, com mente clara e corpo capaz de caminhar, viajar e jogar tênis.'
};
export const defaultHealthCards=[['Tipo sanguíneo','B+'],['VO₂ max','61,2'],['Resting energy','1.824 kcal'],['Altura','1,80 m']];
export const defaultHealthSections:[string,string[]][]=[['Corpo e capacidade',['VO₂ max: 61,2','Resting energy médio: 1.824 kcal/dia','Passos médios históricos: 11.755/dia','Distância média histórica: 8,3 km/dia','Exercício médio histórico: 86 min/dia']],['Coração e recuperação',['Prolapso leve da válvula mitral, segundo avaliação médica','Frequência cardíaca registrada: 41–197 bpm','Faixa em sono: 42–109 bpm','Respiração média: 19,5/min']],['Sono e rotina',['Acorda habitualmente às 7h30','Dormir por volta de 23h','Média histórica: 9h13/noite','Caminhadas diárias com Caju','Tênis e mobilidade como base de atividade']],['Histórico familiar relevante',['Avó materna: hipertensão, AVC e tireoide','Avó paterna: diabetes e evento cardíaco','Avô paterno: cirrose de causa não esclarecida']],['Digestão e sensibilidades',['Massas com glúten podem causar desconforto','Leguminosas podem causar gases/diarreia','Carne vermelha/churrasco pode causar gases','Alguns queijos podem desencadear enxaqueca com aura','Pilsen/Lager em excesso pode causar gases/diarreia']],['Visão e referências',['Astigmatismo leve: R −0,50; L −0,25','Tipo sanguíneo B+','Sem outras condições médicas relatadas']],['Objetivo de longo prazo',['Mente clara e corpo saudável','Capacidade para caminhar e viajar','Longevidade ativa com tênis e rotina sustentável']]];
