export type Lang='pt'|'en';
export const LANG_COOKIE='lang';
export const locales:Record<Lang,string>={pt:'pt-BR',en:'en-GB'};
export const readLang=(value:string|undefined|null):Lang=>value==='en'?'en':'pt';

const pt={
 'nav.hoje':'Hoje','nav.saude':'Saúde','nav.financeiro':'Financeiro','nav.financeiro.short':'Finanças','nav.tenis':'Tênis','nav.caju':'Caju','nav.minhas-informacoes':'Minhas informações','nav.minhas-informacoes.short':'Perfil',
 'shell.tagline':'Painel pessoal','shell.myPanel':'Meu painel','shell.sections':'Seções','shell.mainNav':'Navegação principal','shell.refresh':'Atualizar','shell.refreshTitle':'Atualizar dados','shell.demoData':'Dados fictícios','shell.privateSpace':'Espaço privado','shell.personalSpace':'Espaço pessoal','shell.demo':'Demonstração','shell.logout':'Sair','shell.back':'Voltar para {label}',
 'shell.demoBanner':'Dados fictícios; alterações desaparecem ao recarregar. Não insira dados pessoais.','shell.demoMode':'Modo demonstração.','shell.privateAccess':'Acesso privado','shell.language':'Idioma',
 'login.eyebrow':'Seu espaço pessoal','login.title':'Um dia de cada vez.','login.lead':'Saúde, finanças, carro, documentos, viagens e rotina. Tudo no mesmo lugar.','login.email':'E-mail','login.password':'Senha','login.enter':'Entrar','login.entering':'Entrando…','login.setupTitle':'Seu espaço está preparado','login.setup':'O acesso aos seus dados será liberado quando o Supabase estiver conectado. Por enquanto, explore uma demonstração fictícia.','login.demo':'Explorar demonstração','login.note':'Seus registros exigem uma sessão autenticada.','login.footer':'Feito para acompanhar o seu ritmo','login.league':'Ver a liga de tênis',
 'today.eyebrow':'SEU DIA, EM PERSPECTIVA','today.title':'Como está o seu dia?',
 'league.title':'Liga de tênis','league.eyebrow':'BOX LEAGUE','league.public':'Página pública','league.share':'Compartilhar','league.copied':'Link copiado','league.manage':'Gerenciar liga','league.season':'Temporada','league.seasons':'Temporadas','league.current':'Atual','league.past':'Encerrada','league.upcoming':'Em breve','league.live':'Em andamento',
 'league.standings':'Classificação','league.pos':'#','league.player':'Jogador','league.played':'J','league.won':'V','league.lost':'D','league.sets':'Sets','league.points':'Pts','league.form':'Últimos',
 'league.box':'Tabela do box','league.boxHint':'Linha = sets do jogador da linha contra o da coluna.','league.results':'Resultados','league.noResults':'Nenhum resultado registrado nesta temporada ainda.','league.players':'Jogadores','league.status':'Status da temporada',
 'league.matchesPlayed':'{played} de {total} jogos','league.daysLeft':'{days} dias restantes','league.ended':'Encerrada em {date}','league.startsIn':'Começa em {date}','league.pending':'Jogos pendentes','league.pendingNone':'Todos os confrontos foram jogados.','league.yourPending':'Seus jogos pendentes','league.images':'Imagens','league.pointsRule':'Ordem: vitórias, saldo de sets, sets ganhos e confronto direto. Pontos: 1 por set ganho + 1 por vitória.',
 'league.hand':'Mão','league.backhand':'Backhand','league.racket':'Raquete','league.strings':'Corda','league.level':'Nível','league.since':'Joga desde','league.favouriteShot':'Golpe favorito','league.favouritePlayer':'Ídolo','league.sex':'Sexo','league.country':'País','league.record':'Campanha','league.vs':'vs','league.leader':'Líder','league.champion':'Campeão','league.progress':'Progresso','league.notes':'Observações','league.empty':'Nenhuma temporada cadastrada.','league.allSeasons':'Todas as temporadas','league.publicNote':'Página pública: sem telefones nem dados privados.','league.showAll':'Mostrar todos ({count})','league.showLess':'Mostrar menos',
 'hand.Destro':'Destro','hand.Canhoto':'Canhoto','backhand.Uma mão':'Uma mão','backhand.Duas mãos':'Duas mãos',
 'tennis.title':'Tênis','tennis.lead':'Na grama de Wimbledon: resultados, programação e a sua campanha.','tennis.register':'Registrar partida','tennis.league':'Liga','tennis.leagueLead':'Box league: classificação, jogos pendentes e temporadas.'
};
const en:Record<keyof typeof pt,string>={
 'nav.hoje':'Today','nav.saude':'Health','nav.financeiro':'Finance','nav.financeiro.short':'Finance','nav.tenis':'Tennis','nav.caju':'Caju','nav.minhas-informacoes':'My information','nav.minhas-informacoes.short':'Profile',
 'shell.tagline':'Personal dashboard','shell.myPanel':'My dashboard','shell.sections':'Sections','shell.mainNav':'Main navigation','shell.refresh':'Refresh','shell.refreshTitle':'Refresh data','shell.demoData':'Sample data','shell.privateSpace':'Private space','shell.personalSpace':'Personal space','shell.demo':'Demo','shell.logout':'Sign out','shell.back':'Back to {label}',
 'shell.demoBanner':'Sample data; changes disappear on reload. Do not enter personal data.','shell.demoMode':'Demo mode.','shell.privateAccess':'Private access','shell.language':'Language',
 'login.eyebrow':'Your personal space','login.title':'One day at a time.','login.lead':'Health, finance, car, documents, travel and routine. All in one place.','login.email':'Email','login.password':'Password','login.enter':'Sign in','login.entering':'Signing in…','login.setupTitle':'Your space is ready','login.setup':'Access to your data opens once Supabase is connected. Meanwhile, explore a sample demo.','login.demo':'Explore the demo','login.note':'Your records require a signed-in session.','login.footer':'Made to keep up with your pace','login.league':'See the tennis league',
 'today.eyebrow':'YOUR DAY, IN PERSPECTIVE','today.title':'How is your day going?',
 'league.title':'Tennis league','league.eyebrow':'BOX LEAGUE','league.public':'Public page','league.share':'Share','league.copied':'Link copied','league.manage':'Manage league','league.season':'Season','league.seasons':'Seasons','league.current':'Current','league.past':'Finished','league.upcoming':'Upcoming','league.live':'In progress',
 'league.standings':'Standings','league.pos':'#','league.player':'Player','league.played':'P','league.won':'W','league.lost':'L','league.sets':'Sets','league.points':'Pts','league.form':'Form',
 'league.box':'Box table','league.boxHint':'Row = sets of the row player against the column player.','league.results':'Results','league.noResults':'No results recorded for this season yet.','league.players':'Players','league.status':'Season status',
 'league.matchesPlayed':'{played} of {total} matches','league.daysLeft':'{days} days left','league.ended':'Ended on {date}','league.startsIn':'Starts on {date}','league.pending':'Matches to play','league.pendingNone':'Every match has been played.','league.yourPending':'Your matches to play','league.images':'Images','league.pointsRule':'Order: wins, set difference, sets won and head-to-head. Points: 1 per set won + 1 per win.',
 'league.hand':'Plays','league.backhand':'Backhand','league.racket':'Racket','league.strings':'Strings','league.level':'Level','league.since':'Playing since','league.favouriteShot':'Favourite shot','league.favouritePlayer':'Idol','league.sex':'Sex','league.country':'Country','league.record':'Record','league.vs':'vs','league.leader':'Leader','league.champion':'Champion','league.progress':'Progress','league.notes':'Notes','league.empty':'No seasons yet.','league.allSeasons':'All seasons','league.publicNote':'Public page: no phone numbers or private data.','league.showAll':'Show all ({count})','league.showLess':'Show less',
 'hand.Destro':'Right-handed','hand.Canhoto':'Left-handed','backhand.Uma mão':'One-handed','backhand.Duas mãos':'Two-handed',
 'tennis.title':'Tennis','tennis.lead':'On the Wimbledon grass: results, order of play and your campaign.','tennis.register':'Log a match','tennis.league':'League','tennis.leagueLead':'Box league: standings, matches to play and seasons.'
};
export const messages={pt,en};
export type MessageKey=keyof typeof pt;
export function translate(lang:Lang,key:MessageKey|string,vars:Record<string,string|number>={}){const table=messages[lang] as Record<string,string>;const text=table[key]??(messages.pt as Record<string,string>)[key]??key;return text.replace(/\{(\w+)\}/g,(_,name)=>String(vars[name]??''));}
