import { z } from 'zod';
export const expenseSchema=z.object({id:z.string().min(1).max(100),item:z.string().trim().min(1).max(150),category:z.string().trim().min(1).max(80),value:z.number().finite().nonnegative().max(10000000),type:z.enum(['Fixo','Variável']),payment:z.string().trim().min(1).max(100),day:z.number().int().min(1).max(31).nullable()});
export const financeSchema=z.object({rows:z.array(expenseSchema).max(500),incomeFelipe:z.number().finite().nonnegative(),incomeSara:z.number().finite().nonnegative()});
export type Finance=z.infer<typeof financeSchema>;
export const tripSchema=z.object({id:z.string().min(1).max(100),place:z.string().trim().min(1).max(200),country:z.string().max(100),date:z.string().regex(/^$|^\d{4}-\d{2}-\d{2}$/),rating:z.number().min(0).max(10).nullable(),details:z.string().max(10000)});
const carDate=z.string().refine(value=>value===''||(/^\d{4}-\d{2}-\d{2}$/.test(value)&&Number.isFinite(Date.parse(value))&&new Date(value+'T12:00:00Z').toISOString().slice(0,10)===value),'Data inválida');
const carSite=z.string().max(500).refine(value=>{if(!value)return true;try{return ['http:','https:'].includes(new URL(value).protocol);}catch{return false;}},'Informe um site com https://');
const avatar=z.string().max(120000).refine(value=>value===''||/^data:image\/jpeg;base64,[A-Za-z0-9+/]+={0,2}$/.test(value),'Foto inválida');
export const previousCarSchema=z.object({id:z.string().min(1).max(100),model:z.string().trim().min(1).max(200),registration:z.string().max(40).default(''),purchase:carDate.default(''),sold:carDate.default(''),km:z.number().finite().nonnegative().max(10000000).nullable().default(null),photo:avatar.default(''),notes:z.string().max(10000).default('')});
export const carSchema=z.object({model:z.string().max(200).default('Mitsubishi Eclipse Cross'),registration:z.string().max(40).default(''),purchase:carDate.default(''),insurance:carDate.default(''),permit:carDate.default(''),notes:z.string().max(10000).default(''),km:z.number().finite().nonnegative().max(10000000).nullable().default(null),insuranceSite:carSite.default(''),insuranceExpiry:carDate.default(''),permitSite:carSite.default(''),permitExpiry:carDate.default(''),photo:avatar.default(''),previous:z.array(previousCarSchema).max(20).default([])}).superRefine((car,ctx)=>{if(car.insurance&&car.insuranceExpiry&&car.insuranceExpiry<car.insurance)ctx.addIssue({code:'custom',path:['insuranceExpiry'],message:'O vencimento do seguro deve ser após a contratação.'});if(car.permit&&car.permitExpiry&&car.permitExpiry<car.permit)ctx.addIssue({code:'custom',path:['permitExpiry'],message:'A expiração do Parking Permit deve ser após a contratação.'});for(const [index,previous] of car.previous.entries())if(previous.purchase&&previous.sold&&previous.sold<previous.purchase)ctx.addIssue({code:'custom',path:['previous',index,'sold'],message:'A venda deve ser após a compra.'});});
export type CarProfile=z.infer<typeof carSchema>;
export type PreviousCar=z.infer<typeof previousCarSchema>;

export type Trip=z.infer<typeof tripSchema>;
const source:[string,string,number,string,number|null,boolean?][]=[
['Rent','House',1520,'Santander',1],['Council Tax','House',168,'Santander',20],['Water','House',60,'Santander',1],['Energy','House',115,'Santander',20],['Grocery','Grocery',500,'Revolut',null],['Vitamins / Medicines','Shopping',35,'Wise',null,true],['Church','Church',30,'Wise',null,true],['Parking','House',75,'Santander',1],['Extras Sara','Shopping',50,'Wise',null,true],['Extras Felipe','Shopping',50,'Wise',null,true],['Extras Caju','Caju',75,'Wise',null],['Extras Home','Shopping',25,'Wise',null,true],['Internet Mobile','Subscription',37,'Santander',5],['Road Tax','Car',17.5,'Santander',1],['Apple Storage','Subscription',9,'Santander',22],['Youtube','Subscription',20,'Santander',11],['Amazon Prime','Subscription',8.99,'Santander',1],['ChatGPT','Subscription',20,'Santander',4],['Caju Insurance','Caju',23.63,'Santander',26],['Caju Vets4Pets','Caju',20,'Santander',1],['David Lloyd','Fitness',320,'Santander',1],['Gifts for Sara','Shopping',15,'Wise',null,true],['Gifts for Felipe','Shopping',15,'Wise',null,true],['Fuel','Car',125,'Wise',null],['Car insurance','Car',107,'Santander',18],['Beauty Felipe','Beauty',20,'Wise',null,true],['Beauty Sara','Beauty',20,'Wise',null,true],['Entreteniment','Entreteniment',200,'Wise',null,true],['Internet home','House',15,'Santander',28],['Land in Sao Carlos','Property',170,'Santander',null],['IPTU Sao Carlos','Property',10,'Santander',null]];
export const initialFinance:Finance={incomeFelipe:4300,incomeSara:1000,rows:source.map(([item,category,value,payment,day,variable],i)=>({id:`original-${i}`,item,category,value,payment:payment==='Santander'?'Direct Debit Santander':payment==='Wise'?'Wise Jar':payment,day,type:variable?'Variável':'Fixo'}))};
export function moneyTotal(rows:Finance['rows']){return rows.reduce((sum,row)=>sum+Math.round(row.value*100),0)/100;}
export function grouped(rows:Finance['rows'],key:'category'|'payment'){return [...new Set(rows.map(row=>row[key]))].sort().map(name=>({name,value:moneyTotal(rows.filter(row=>row[key]===name))}));}
