import { resourceNames } from './site-crud';
const resource={type:'string',enum:resourceNames};
const schema=(properties:Record<string,unknown>,required:string[])=>({type:'object',properties,required,additionalProperties:false});
const tool=(name:string,description:string,inputSchema:unknown,readOnlyHint:boolean,destructiveHint=false)=>({name,title:name.replaceAll('_',' '),description,inputSchema,annotations:{readOnlyHint,destructiveHint,openWorldHint:false},securitySchemes:[{type:'oauth2',scopes:[readOnlyHint?'health:read':'health:write']}]});
const id={type:'string',description:'UUID do item para tabelas. Para criação, gere uma vez e reutilize em tentativas. Seções pessoais não usam id: edite o item pelo caminho.'};
const expected_version={type:'string',description:'Versão exata retornada por consultar_dados_site; protege contra sobrescrever alterações mais recentes.'};
export const siteTools=[
 tool('estrutura_do_site','Descobre TODOS os cadastros do site, campos, formatos e instruções. Use antes de editar uma seção desconhecida. Inclui saúde, nutrição, sódio, sono, exercício, tênis, metas, carro completo, fotos, documentos, manutenção, financiamento, contas, preferências, financeiro, investimentos e viagens.',schema({},[]),true),
 tool('consultar_dados_site','Consulta qualquer seção ou tabela do site, com versão para edição. Tabelas retornam IDs e paginação: percorra next_offset para encontrar registros antigos. Para perfil pessoal retorna a seção completa, incluindo listas e objetos aninhados.',schema({resource,id,date_from:{type:'string'},date_to:{type:'string'},category:{type:'string'},offset:{type:'integer',minimum:0},limit:{type:'integer',minimum:1,maximum:100}},['resource']),true),
 tool('adicionar_dados_site','Cria registro em tabela com id UUID e data completo conforme estrutura_do_site. Para seções pessoais, prefira editar_dados_site com op add para incluir um item sem substituir os existentes. Este método substitui a seção pessoal inteira por data, exigindo expected_version. Nunca invente informações; preserve o histórico e campos não solicitados.',schema({resource,id,expected_version,data:{description:'Dados completos conforme esquema retornado por estrutura_do_site.'}},['resource','data']),false),
 tool('editar_dados_site','Edita QUALQUER campo de qualquer cadastro após consultar_dados_site. operations é JSON Pointer: replace /registration, replace /extra/financing/apr, replace /rows/0/value, add /previous/-, remove /extra/documents/0. Para arrays raiz use /0/rating ou /-. Consultar o ID do item antes de escolher o índice. Alterações explícitas do usuário já autorizam a operação; só esclareça alvos ambíguos. Preserve tudo que não foi solicitado. Campos calculados dependem dos registros de origem.',schema({resource,id,expected_version,operations:{type:'array',minItems:1,maxItems:100,items:{type:'object',required:['op','path'],properties:{op:{type:'string',enum:['add','replace','remove']},path:{type:'string'},value:{description:'Novo valor JSON, obrigatório em add/replace. Para remover campo obrigatório, use string vazia ou null quando o esquema permitir.'}}}}},['resource','expected_version','operations']),false,true),
 tool('excluir_dados_site','Exclui um registro de tabela identificado por id OU limpa TODA a seção pessoal indicada. Para excluir apenas uma linha do orçamento, um documento, uma viagem ou snapshot, use editar_dados_site com remove no caminho desse item. Execute somente quando o usuário pedir claramente esta exclusão. O pedido explícito já é autorização; pergunte só se houver ambiguidade. Exige versão consultada e retorna o resultado real.',schema({resource,id,expected_version},['resource','expected_version']),false,true)
];
