import { defaultHealthProfile,defaultHealthCards,defaultHealthSections } from './health-profile-defaults';
import { createHash } from 'node:crypto';
import { z } from 'zod';
import type { SupabaseClient } from '@supabase/supabase-js';
import { eventSchema,foodSchema,itemSchema,targetSchema,dayTypes,metricInfo,localDate } from './domain';
import { carSchema,financeSchema,tripSchema,initialFinance } from './personal';
import { billsSchema,datesSchema,preferencesSchema,dateValue,defaultBills } from './life';
import { investmentsSchema } from './investments';
import { updateProfile } from './profile-store';
const requiredDate=dateValue.refine(v=>v!=='','Data obrigatória');
const targets=z.record(z.enum(Object.keys(metricInfo) as [string,...string[]]),targetSchema);
export const healthDisplaySchema=z.object({cards:z.array(z.tuple([z.string().max(100),z.string().max(1000)])).max(50),sections:z.array(z.tuple([z.string().max(200),z.array(z.string().max(5000)).max(100)])).max(50)});
const recordSchema=z.object({category:z.enum(['daily_metrics','workout','meal_history','hydration_history','checkin_history','sleep','activity','bowel','supplement','tennis','schedule','body_metrics','profile_history']),recorded_on:requiredDate,recorded_at:z.string().datetime({offset:true}).nullable(),payload:z.record(z.string(),z.unknown()),source:z.string().min(1).max(100)});
const daySchema=z.object({local_date:requiredDate,day_type:z.enum(dayTypes),targets});
const templateSchema=z.object({name:z.string().min(1).max(200),day_type:z.enum(dayTypes),targets});
const planSchema=daySchema.extend({agenda:z.array(z.string().max(2000)).max(200),rationale:z.string().max(10000)});
const healthSchema=z.record(z.string().max(200),z.unknown()).refine(v=>Object.keys(v).every(k=>!k.startsWith('personal_')),'Use a seção específica para dados pessoais.');
const draftSchema=z.object({payload:z.record(z.string(),z.unknown())});
export const resources={
 perfil_saude:{key:'health',schema:healthSchema,empty:{},description:'Textos e informações de saúde em Minhas informações. Campos livres, usando os nomes já existentes.'},
 resumo_perfil:{key:'personal_health_display',schema:healthDisplaySchema,empty:{cards:[],sections:[]},description:'Cards de tipo sanguíneo, VO2max, metabolismo, altura e listas de referências do perfil. cards = [[rótulo,valor]], sections = [[título,[informações]]].'},
 carro:{key:'personal_car',schema:carSchema,empty:{model:''},description:'Todos os campos do carro, avatar em photo (URL HTTPS da imagem ou data:image/jpeg;base64), carros anteriores em previous, financiamento/MOT/Tax/seguro/documentos/manutenções em extra.'},
 financeiro:{key:'personal_finance',schema:financeSchema,empty:{rows:[],incomeFelipe:0,incomeSara:0},description:'Linhas do orçamento, salários, categorias, valores, tipos, formas e datas de pagamento. Edite uma linha pelo índice após consultar o id.'},
 investimentos:{key:'personal_investments',schema:investmentsSchema,empty:[],description:'Histórico de snapshots de investimentos e todos os itens. Para novo print prefira registrar_investimentos; para correções ou exclusões use edição por caminho.'},
 viagens:{key:'personal_trips',schema:z.array(tripSchema).max(1000),empty:[],description:'Lugares, país, data, nota e detalhes.'},
 contas:{key:'personal_bills',schema:billsSchema,empty:[],description:'Energia, gás, água, internet, Council Tax e outras contas.'},
 documentos_datas:{key:'personal_dates',schema:datesSchema,empty:[],description:'Documentos, visto, passaporte, garantias, assinaturas, consultas e respectivos vencimentos.'},
 preferencias:{key:'personal_preferences',schema:preferencesSchema,empty:{},description:'Preferências pessoais. Chaves como Comida.Favoritas, Filmes.Gêneros, Viagem.Clima, Carros.Marcas, Música.Artistas, Restaurantes.Ambiente.'},
 eventos:{table:'events',schema:eventSchema,description:'Água, refeições (ingredientes, quantidades e todos os nutrientes), check-ins. local_date é calculada de timestamp em Europe/London.'},
 registros:{table:'health_records',schema:recordSchema,description:'Sono, exercícios, resumo diário, tênis e sets/check-ins, suplementos, fezes, medidas e importações. Todos os detalhes ficam em payload.'},
 dias_metas:{table:'days',schema:daySchema,description:'Tipo de dia e metas, incluindo sódio. Seletor id = UUID retornado na consulta.'},
 modelos_metas:{table:'target_templates',schema:templateSchema,description:'Metas por tipo de dia, incluindo sódio.'},
 agenda:{table:'day_plans',schema:planSchema,description:'Agenda semanal por data, tipo de dia, metas e justificativa.'},
 alimentos:{table:'foods',schema:foodSchema,description:'Dados nutricionais de alimentos legados. A biblioteca não aparece no menu.'},
 refeicoes_salvas:{table:'meal_templates',schema:z.object({name:z.string().min(1).max(200),items:z.array(itemSchema).max(100)}),description:'Combinações legadas de refeições.'},
 rascunho_checkin:{table:'checkin_drafts',schema:draftSchema,description:'Rascunho do check-in; não é o check-in já registrado.'}
} as const;
export type Resource=keyof typeof resources;
export const resourceNames=Object.keys(resources) as Resource[];
const canonical=(v:any):string=>Array.isArray(v)?'['+v.map(canonical).join(',')+']':v&&typeof v==='object'?'{'+Object.keys(v).sort().map(k=>JSON.stringify(k)+':'+canonical(v[k])).join(',')+'}':JSON.stringify(v);
export const version=(v:unknown)=>createHash('sha256').update(canonical(v)).digest('hex');
const forbidden=new Set(['__proto__','prototype','constructor']);
const operationSchema=z.object({op:z.enum(['add','replace','remove']),path:z.string().max(1000),value:z.unknown().optional()});
export function patchData(current:unknown,raw:unknown){let result=structuredClone(current);for(const op of z.array(operationSchema).min(1).max(100).parse(raw)){
 if(op.op!=='remove'&&op.value===undefined)throw new Error('Informe value.');
 if(op.path===''){if(op.op==='remove')throw new Error('Para apagar a seção use excluir_dados_site.');result=structuredClone(op.value);continue;}
 if(!op.path.startsWith('/'))throw new Error('Use caminhos JSON Pointer, como /extra/mot/next.');
 const parts=op.path.slice(1).split('/').map(p=>p.replace(/~1/g,'/').replace(/~0/g,'~'));if(parts.some(p=>forbidden.has(p)))throw new Error('Caminho inválido.');
 let parent:any=result;for(const key of parts.slice(0,-1)){if(!parent||typeof parent!=='object'||!Object.hasOwn(parent,key))throw new Error('Caminho não encontrado. Consulte os dados atuais.');parent=parent[key];}
 const key=parts.at(-1)!;if(!parent||typeof parent!=='object')throw new Error('Caminho inválido.');
 if(Array.isArray(parent)){const index=key==='-'?parent.length:/^(0|[1-9]\d*)$/.test(key)?Number(key):-1;if(index<0||index>parent.length||(op.op!=='add'&&index===parent.length))throw new Error('Índice inválido.');if(op.op==='add')parent.splice(index,0,structuredClone(op.value));else if(op.op==='remove')parent.splice(index,1);else parent[index]=structuredClone(op.value);}
 else {if(op.op!=='add'&&!Object.hasOwn(parent,key))throw new Error('Campo não encontrado.');if(op.op==='remove')delete parent[key];else parent[key]=structuredClone(op.value);}
 }return result;}
function schemaJSON(schema:any):any{const d=schema._def;switch(d.typeName){case 'ZodEffects':return schemaJSON(d.schema);case 'ZodDefault':return {...schemaJSON(d.innerType),default:d.defaultValue()};case 'ZodOptional':return schemaJSON(d.innerType);case 'ZodNullable':return {anyOf:[schemaJSON(d.innerType),{type:'null'}]};case 'ZodObject':return {type:'object',required:Object.entries(d.shape()).filter(([,s]:any)=>!s.isOptional()).map(([k])=>k),properties:Object.fromEntries(Object.entries(d.shape()).map(([k,s])=>[k,schemaJSON(s)]))};case 'ZodRecord':return {type:'object',additionalProperties:schemaJSON(d.valueType)};case 'ZodArray':return {type:'array',items:schemaJSON(d.type)};case 'ZodTuple':return {type:'array',prefixItems:d.items.map(schemaJSON)};case 'ZodEnum':return {type:'string',enum:d.values};case 'ZodLiteral':return {const:d.value};case 'ZodDiscriminatedUnion':return {oneOf:d.options.map(schemaJSON)};case 'ZodString':return {type:'string'};case 'ZodNumber':return {type:'number'};case 'ZodBoolean':return {type:'boolean'};default:return {};}}
export function catalog(){return {resources:resourceNames.map(name=>({resource:name,description:resources[name].description,schema:schemaJSON(resources[name].schema)})),instructions:'Consulte antes de editar. Use version retornada como expected_version. Caminhos JSON Pointer: /registration, /extra/mot/next, /rows/0/value, /0/items/0/value; add /- insere em uma lista. Campos obrigatórios podem ser limpos com string vazia ou null conforme esquema. Não altere IDs de proprietário ou campos internos. Números calculados (médias, gráficos, notas automáticas) mudam ao editar os registros de origem, não têm valor independente.'};}
function section(profile:Record<string,any>,resource:Resource){const config=resources[resource] as any;if(config.key==='health')return {...(profile.personal_health_initialized?{}:defaultHealthProfile),...Object.fromEntries(Object.entries(profile).filter(([k])=>!k.startsWith('personal_')))};if(resource==='financeiro'&&!profile[config.key])return initialFinance;if(resource==='contas'&&!profile[config.key])return defaultBills;if(resource==='resumo_perfil'&&!profile[config.key])return {cards:defaultHealthCards,sections:defaultHealthSections};return config.schema.parse(profile[config.key]??config.empty);}
function guarded(query:any,row:any){if(row.updated_at)return query.eq('updated_at',row.updated_at);for(const [key,value] of Object.entries(row)){if(['user_id','id'].includes(key))continue;query=value===null?query.is(key,null):query.eq(key,typeof value==='object'?JSON.stringify(value):value);}return query;}

export async function siteRead(db:SupabaseClient,userId:string,args:any){const resource=z.enum(resourceNames as [Resource,...Resource[]]).parse(args.resource),config=resources[resource] as any;
 if(config.key){const result=await db.from('health_profiles').select('profile').eq('user_id',userId).maybeSingle();if(result.error)throw new Error('Falha ao consultar.');const data=section(result.data?.profile??{},resource);return {resource,data,version:version(data)};}
 let query=db.from(config.table).select('*').eq('user_id',userId);if(args.id&&resource!=='rascunho_checkin')query=query.eq('id',z.string().uuid().parse(args.id));
 const dateField=resource==='registros'?'recorded_on':['eventos','dias_metas','agenda'].includes(resource)?'local_date':null;
 if(dateField&&args.date_from)query=query.gte(dateField,requiredDate.parse(args.date_from));if(dateField&&args.date_to)query=query.lte(dateField,requiredDate.parse(args.date_to));if(resource==='registros'&&args.category)query=query.eq('category',recordSchema.shape.category.parse(args.category));
 const offset=z.number().int().min(0).parse(args.offset??0),limit=z.number().int().min(1).max(100).parse(args.limit??50);const result=await query.order(resource==='rascunho_checkin'?'user_id':'id').range(offset,offset+limit);if(result.error)throw new Error('Falha ao consultar os dados.');
 let profile:any={};if(['dias_metas','modelos_metas'].includes(resource)){const p=await db.from('health_profiles').select('profile').eq('user_id',userId).maybeSingle();if(p.error)throw new Error('Falha ao consultar metas.');profile=p.data?.profile??{};}
 const rows=(result.data??[]).slice(0,limit).map(row=>{const data={...row};delete data.user_id;if(['dias_metas','modelos_metas'].includes(resource)){const k=resource==='dias_metas'?'personal_sodium_date_'+row.local_date:'personal_sodium_type_'+row.day_type;const typeKey='personal_sodium_type_'+row.day_type;const sodium=Object.hasOwn(profile,k)?profile[k]:Object.hasOwn(profile,typeKey)?profile[typeKey]:{kind:'maximum',min:null,max:2000};data.targets={...row.targets,...(sodium?{sodium}:{})};}return {data,version:version(data)};});return {resource,items:rows,next_offset:(result.data?.length??0)>limit?offset+limit:null};
}
function safeJSON(value:any,depth=0){if(depth>40)throw new Error('Dados muito aninhados.');if(value&&typeof value==='object'){for(const [key,child] of Object.entries(value)){if(forbidden.has(key))throw new Error('Campo reservado.');safeJSON(child,depth+1);}}}
const metadata=new Set(['id','user_id','created_at','updated_at','local_date','confidence','import_source','source_record_id']);
function checkRetained(before:any,after:any,path=''){if(before&&typeof before==='object'&&after&&typeof after==='object'){for(const key of Object.keys(before)){if(!Object.hasOwn(after,key)){if(path===''&&metadata.has(key))continue;throw new Error('Campo desconhecido: '+path+'/'+key);}checkRetained(before[key],after[key],path+'/'+key);}}}
function validateResource(config:any,resource:Resource,candidate:any){safeJSON(candidate);const data=config.schema.parse(candidate);checkRetained(candidate,data);const lists=resource==='financeiro'?[data.rows]:resource==='carro'?[data.previous,data.extra.documents,data.extra.maintenance,data.extra.motHistory]:Array.isArray(data)?[data]:[];for(const list of lists){const ids=list.map((row:any)=>row.id).filter(Boolean);if(new Set(ids).size!==ids.length)throw new Error('IDs duplicados: cada item precisa de ID único.');}if(resource==='investimentos'){const ids=new Set(),assets=new Map();for(const snapshot of data){if(ids.has(snapshot.id))throw new Error('ID de atualização duplicado.');ids.add(snapshot.id);for(const item of snapshot.items){const identity=item.account+'|'+item.currency;if(assets.has(item.asset_id)&&assets.get(item.asset_id)!==identity)throw new Error('Não misture contas ou moedas sob o mesmo asset_id.');assets.set(item.asset_id,identity);}}}return data;}
export async function siteWrite(db:SupabaseClient,userId:string,mode:'add'|'edit'|'delete',args:any){const resource=z.enum(resourceNames as [Resource,...Resource[]]).parse(args.resource),config=resources[resource] as any;
 if(config.key){let answer:any;await updateProfile(db,userId,profile=>{const current=section(profile,resource);if(args.expected_version!==version(current))throw new Error('Dados alterados ou versão ausente. Consulte novamente antes de salvar.');const candidate=mode==='delete'?config.empty:mode==='add'?args.data:patchData(current,args.operations);const data=validateResource(config,resource,candidate);const next={...profile};if(config.key==='health'){for(const key of Object.keys(next))if(!key.startsWith('personal_'))delete next[key];Object.assign(next,data);next.personal_health_initialized=true;}else next[config.key]=data;answer={resource,saved:mode!=='delete',deleted:mode==='delete',data,version:version(data)};return next;});return answer;}
 const id=resource==='rascunho_checkin'?userId:z.string().uuid().parse(args.id);const idKey=resource==='rascunho_checkin'?'user_id':'id';
 const previous=await db.from(config.table).select('*').eq('user_id',userId).eq(idKey,id).maybeSingle();if(previous.error)throw new Error('Não foi possível consultar o item.');
 if(mode==='add'&&previous.data)throw new Error('ID já existente. Consulte o item para verificar ou editar; não crie duplicatas.');if(mode!=='add'&&!previous.data)throw new Error('Item não encontrado; nenhuma alteração realizada.');
 const read=mode==='add'?null:await siteRead(db,userId,{resource,id,limit:1});const current=read?.items?.[0]?.data;if(mode!=='add'&&args.expected_version!==version(current))throw new Error('Versão desatualizada. Consulte novamente.');
 let query=db.from(config.table);if(mode==='delete'){let del=query.delete().eq('user_id',userId).eq(idKey,id);del=guarded(del,previous.data);const removed=await del.select(idKey);if(removed.error||!removed.data?.length)throw new Error('Não foi possível excluir; consulte novamente.');if(['dias_metas','modelos_metas'].includes(resource)){const key=resource==='dias_metas'?'personal_sodium_date_'+current.local_date:'personal_sodium_type_'+current.day_type;await updateProfile(db,userId,p=>{const next={...p};delete next[key];return next;});}return {resource,id,deleted:true};}
 if(mode==='edit')for(const op of args.operations??[]){const root=String(op.path).split('/')[1];if(metadata.has(root)&&!(root==='local_date'&&['dias_metas','agenda'].includes(resource)))throw new Error('Campo interno não editável: '+root);}
 const candidate=mode==='add'?args.data:patchData(current,args.operations);if(mode==='edit'&&(candidate.id!==current.id||candidate.user_id!==undefined))throw new Error('Não altere IDs internos.');
 const data=validateResource(config,resource,candidate) as any;if(resource==='eventos')data.local_date=localDate(new Date(data.timestamp));const sodium=data.targets?.sodium;if(['dias_metas','modelos_metas'].includes(resource)){delete data.targets.sodium;}
 const write=mode==='add'?query.insert({...data,[idKey]:id,user_id:userId}):guarded(query.update(data).eq('user_id',userId).eq(idKey,id),previous.data);const result=await write.select().single();if(result.error)throw new Error('Não foi possível salvar: '+result.error.message);
 if(['dias_metas','modelos_metas'].includes(resource)){const key=resource==='dias_metas'?'personal_sodium_date_'+data.local_date:'personal_sodium_type_'+data.day_type;await updateProfile(db,userId,p=>({...p,[key]:sodium??null}));}
 return {id,saved:true,...await siteRead(db,userId,{resource,id,limit:1})};
}
