import { personalData } from '@/lib/personal-data';
import { LifeInformation } from '@/components/life-information';
import { CarInformation } from '@/components/car-information';
import { FinanceDashboard,TravelDashboard } from '@/components/personal-dashboard';
import { HeartPulse,Car,Wallet,Plane,ChevronDown } from 'lucide-react';
import { HealthProfile } from '@/components/health-profile';
import { AppFrame } from '@/components/app-frame';
import { supabase,healthService,healthUserId } from '@/lib/supabase/server';
export const dynamic='force-dynamic';
export default async function Page(){const session=await supabase();const {data:{user}}=await session.auth.getUser();const healthUser=healthUserId()??user?.id;const db=healthUserId()?healthService():session;const personal=await personalData();const [profile,measurements]=healthUser?await Promise.all([db.from('health_profiles').select('profile').eq('user_id',healthUser).maybeSingle(),db.from('health_records').select('recorded_on,payload,source').eq('user_id',healthUser).eq('category','body_metrics').order('recorded_on',{ascending:false}).limit(1)]):[{data:null},{data:[]}];if(profile.error||measurements.error)throw new Error('Não foi possível carregar suas informações. Tente atualizar.');return <AppFrame title="Minhas informações"><div className="content"><div className="page-heading"><div><span className="eyebrow">DADOS PRIVADOS</span><h1>Minhas informações</h1><p>Saúde, carro e finanças. Seus detalhes organizados em um só lugar.</p></div></div><div className="information-sections"><details className="information-card"><summary><span className="information-icon"><HeartPulse/></span><span><strong>Saúde</strong><small>Perfil, medidas corporais e histórico de saúde</small></span><ChevronDown className="expand-arrow"/></summary><div className="information-body"><HealthProfile initial={personal} measurements={measurements.data?.[0]??null}/></div></details><details className="information-card car-information-card"><summary><span className="information-icon"><Car/></span><span><strong>Carro</strong><small>Seu Eclipse Cross, documentos e carros anteriores</small></span><ChevronDown className="expand-arrow"/></summary><div className="information-body"><CarInformation initial={personal.personal_car}/></div></details><details className="information-card"><summary><span className="information-icon"><Wallet/></span><span><strong>Financeiro</strong><small>Planejamento, despesas e formas de pagamento</small></span><ChevronDown className="expand-arrow"/></summary><div className="information-body"><FinanceDashboard initial={personal.personal_finance}/></div></details><details className="information-card"><summary><span className="information-icon"><Plane/></span><span><strong>Viagens</strong><small>Lugares visitados, notas e lembranças</small></span><ChevronDown className="expand-arrow"/></summary><div className="information-body"><TravelDashboard initial={personal.personal_trips}/></div></details><LifeInformation profile={personal}/></div></div></AppFrame>}
